import {
  mdiAccountCheck,
  mdiAccountCog,
  mdiAccountCircle,
  mdiAccountGroup,
  mdiAccountQuestion,
  mdiAirFilter,
  mdiAirHumidifier,
  mdiAirPurifier,
  mdiApple,
  mdiBathtub,
  mdiBed,
  mdiBedDouble,
  mdiBedKing,
  mdiBedSingle,
  mdiCalendar,
  mdiCamera,
  mdiCar,
  mdiCarDefrostFront,
  mdiCarDoorLock,
  mdiCarElectric,
  mdiCarSeat,
  mdiCart,
  mdiCheckboxBlankCircleOutline,
  mdiCheckboxMarkedCircle,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiClipboardList,
  mdiClose,
  mdiCog,
  mdiDesktopTower,
  mdiDishwasher,
  mdiDoor,
  mdiDoorOpen,
  mdiDumbbell,
  mdiEvStation,
  mdiFan,
  mdiFanAuto,
  mdiFanOff,
  mdiFanSpeed1,
  mdiFanSpeed2,
  mdiFanSpeed3,
  mdiFire,
  mdiFoodForkDrink,
  mdiFormDropdown,
  mdiFormatListCheckbox,
  mdiGarage,
  mdiGrill,
  mdiGuitarElectric,
  mdiHammerWrench,
  mdiHome,
  mdiHomeAssistant,
  mdiHomeThermometer,
  mdiLaptopAccount,
  mdiLeaf,
  mdiLightbulb,
  mdiLightbulbGroup,
  mdiLock,
  mdiLockClock,
  mdiMapMarker,
  mdiMapMarkerCheck,
  mdiMonitor,
  mdiMotionSensor,
  mdiMovieOpen,
  mdiMusic,
  mdiNintendoSwitch,
  mdiNumeric,
  mdiPause,
  mdiPercent,
  mdiPlay,
  mdiPopcorn,
  mdiPotSteam,
  mdiPower,
  mdiProjector,
  mdiProgressClock,
  mdiRecordCircle,
  mdiRemote,
  mdiRobotVacuum,
  mdiShield,
  mdiShieldAlert,
  mdiShieldHome,
  mdiShieldMoon,
  mdiShieldOff,
  mdiShower,
  mdiShowerHead,
  mdiSilverwareForkKnife,
  mdiSmoke,
  mdiSofa,
  mdiSpeaker,
  mdiSpeakerMultiple,
  mdiStairs,
  mdiStop,
  mdiStringLights,
  mdiTelevisionPlay,
  mdiThermometer,
  mdiTimerCog,
  mdiToggleSwitch,
  mdiTumbleDryer,
  mdiVacuum,
  mdiVolumeHigh,
  mdiVolumeOff,
  mdiWardrobeOutline,
  mdiWashingMachine,
  mdiWater,
  mdiWaterPercent,
  mdiWeatherCloudy,
  mdiWeatherNight,
  mdiWindowClosed,
  mdiWindowOpen,
} from '@mdi/js'
import type { IconKey } from '../../constants/atAGlance'

const ICON_PATHS = {
  air: mdiAirFilter,
  bath: mdiBathtub,
  bed: mdiBedDouble,
  camera: mdiCamera,
  car: mdiCar,
  checklist: mdiClipboardList,
  contact: mdiDoor,
  'contact-open': mdiDoorOpen,
  deck: mdiFan,
  door: mdiDoor,
  'door-open': mdiDoorOpen,
  dumbbell: mdiDumbbell,
  garage: mdiGarage,
  grill: mdiGrill,
  home: mdiHome,
  kitchen: mdiPotSteam,
  light: mdiLightbulb,
  media: mdiMovieOpen,
  music: mdiMusic,
  office: mdiMonitor,
  presence: mdiAccountCheck,
  'presence-off': mdiCheckboxBlankCircleOutline,
  security: mdiShield,
  settings: mdiCog,
  sofa: mdiSofa,
  sparkles: mdiLightbulbGroup,
  stairs: mdiStairs,
  theater: mdiPopcorn,
  thermostat: mdiThermometer,
  utensils: mdiSilverwareForkKnife,
  vacuum: mdiRobotVacuum,
  weather: mdiWeatherCloudy,
} satisfies Record<IconKey, string>

const MATERIAL_ICON_PATHS: Record<string, string> = {
  'mdi:account-check': mdiAccountCheck,
  'mdi:account-cog': mdiAccountCog,
  'mdi:account-circle': mdiAccountCircle,
  'mdi:account-group': mdiAccountGroup,
  'mdi:account-question': mdiAccountQuestion,
  'mdi:air-filter': mdiAirFilter,
  'mdi:air-humidifier': mdiAirHumidifier,
  'mdi:air-purifier': mdiAirPurifier,
  'mdi:apple': mdiApple,
  'mdi:bathtub': mdiBathtub,
  'mdi:bed': mdiBed,
  'mdi:bed-double': mdiBedDouble,
  'mdi:bed-king': mdiBedKing,
  'mdi:bed-single': mdiBedSingle,
  'mdi:calendar': mdiCalendar,
  'mdi:camera': mdiCamera,
  'mdi:car': mdiCar,
  'mdi:car-defrost-front': mdiCarDefrostFront,
  'mdi:car-door-lock': mdiCarDoorLock,
  'mdi:car-electric': mdiCarElectric,
  'mdi:car-seat': mdiCarSeat,
  'mdi:cart': mdiCart,
  'mdi:checkbox-blank-circle-outline': mdiCheckboxBlankCircleOutline,
  'mdi:checkbox-marked-circle': mdiCheckboxMarkedCircle,
  'mdi:chevron-down': mdiChevronDown,
  'mdi:chevron-left': mdiChevronLeft,
  'mdi:chevron-right': mdiChevronRight,
  'mdi:chevron-up': mdiChevronUp,
  'mdi:clipboard-list': mdiClipboardList,
  'mdi:close': mdiClose,
  'mdi:cog': mdiCog,
  'mdi:desktop-tower': mdiDesktopTower,
  'mdi:dishwasher': mdiDishwasher,
  'mdi:door': mdiDoor,
  'mdi:door-open': mdiDoorOpen,
  'mdi:dumbbell': mdiDumbbell,
  'mdi:ev-station': mdiEvStation,
  'mdi:fan': mdiFan,
  'mdi:fan-auto': mdiFanAuto,
  'mdi:fan-off': mdiFanOff,
  'mdi:fan-speed-1': mdiFanSpeed1,
  'mdi:fan-speed-2': mdiFanSpeed2,
  'mdi:fan-speed-3': mdiFanSpeed3,
  'mdi:fire': mdiFire,
  'mdi:food-fork-drink': mdiFoodForkDrink,
  'mdi:form-dropdown': mdiFormDropdown,
  'mdi:format-list-checkbox': mdiFormatListCheckbox,
  'mdi:garage': mdiGarage,
  'mdi:grill': mdiGrill,
  'mdi:guitar-electric': mdiGuitarElectric,
  'mdi:hammer-wrench': mdiHammerWrench,
  'mdi:home': mdiHome,
  'mdi:home-assistant': mdiHomeAssistant,
  'mdi:home-thermometer': mdiHomeThermometer,
  'mdi:laptop-account': mdiLaptopAccount,
  'mdi:leaf': mdiLeaf,
  'mdi:lightbulb': mdiLightbulb,
  'mdi:lightbulb-group': mdiLightbulbGroup,
  'mdi:lock': mdiLock,
  'mdi:lock-clock': mdiLockClock,
  'mdi:map-marker': mdiMapMarker,
  'mdi:map-marker-check': mdiMapMarkerCheck,
  'mdi:monitor': mdiMonitor,
  'mdi:motion-sensor': mdiMotionSensor,
  'mdi:movie-open': mdiMovieOpen,
  'mdi:music': mdiMusic,
  'mdi:nintendo-switch': mdiNintendoSwitch,
  'mdi:numeric': mdiNumeric,
  'mdi:pause': mdiPause,
  'mdi:percent': mdiPercent,
  'mdi:play': mdiPlay,
  'mdi:popcorn': mdiPopcorn,
  'mdi:pot-steam': mdiPotSteam,
  'mdi:power': mdiPower,
  'mdi:projector': mdiProjector,
  'mdi:progress-clock': mdiProgressClock,
  'mdi:record-circle': mdiRecordCircle,
  'mdi:remote': mdiRemote,
  'mdi:robot-vacuum': mdiRobotVacuum,
  'mdi:shield': mdiShield,
  'mdi:shield-alert': mdiShieldAlert,
  'mdi:shield-home': mdiShieldHome,
  'mdi:shield-moon': mdiShieldMoon,
  'mdi:shield-off': mdiShieldOff,
  'mdi:shower': mdiShower,
  'mdi:shower-head': mdiShowerHead,
  'mdi:silverware-fork-knife': mdiSilverwareForkKnife,
  'mdi:smoke': mdiSmoke,
  'mdi:sofa': mdiSofa,
  'mdi:speaker': mdiSpeaker,
  'mdi:speaker-multiple': mdiSpeakerMultiple,
  'mdi:stairs': mdiStairs,
  'mdi:stop': mdiStop,
  'mdi:string-lights': mdiStringLights,
  'mdi:television-play': mdiTelevisionPlay,
  'mdi:thermometer': mdiThermometer,
  'mdi:thermostat': mdiThermometer,
  'mdi:timer-cog': mdiTimerCog,
  'mdi:toggle-switch': mdiToggleSwitch,
  'mdi:tumble-dryer': mdiTumbleDryer,
  'mdi:vacuum': mdiVacuum,
  'mdi:volume-high': mdiVolumeHigh,
  'mdi:volume-off': mdiVolumeOff,
  'mdi:washing-machine': mdiWashingMachine,
  'mdi:wardrobe-outline': mdiWardrobeOutline,
  'mdi:water': mdiWater,
  'mdi:water-percent': mdiWaterPercent,
  'mdi:weather-cloudy': mdiWeatherCloudy,
  'mdi:weather-night': mdiWeatherNight,
  'mdi:window-closed': mdiWindowClosed,
  'mdi:window-open': mdiWindowOpen,
}

export const DOOR_CLOSED_TRANSFORM = 'translate(12 12) scale(1.2 1.03) translate(-12 -12)'

export function materialIconPath(name: string | IconKey | undefined) {
  if (!name) return mdiHome
  if (name in ICON_PATHS) return ICON_PATHS[name as IconKey]
  return MATERIAL_ICON_PATHS[name] ?? mdiHome
}