import type { RoomSourceKind } from '../constants/roomPages'
import { roomCardFamilyArticleId, roomCardFamilySurfaceId } from './roomCardFamilies'
import type { ManualArticle, ManualFamilyGuideArticle } from './types'

export const ROOM_CARD_FAMILY_GUIDE_ARTICLES_BY_KIND = {
  air: {
    id: roomCardFamilyArticleId('air'),
    kind: 'family-guide',
    sectionId: 'rooms',
    parentId: 'device-families',
    title: 'Air quality and purifier cards',
    summary: 'Read particulate summaries and use the shared purifier sheet without confusing air quality with purifier power.',
    icon: 'mdi:air-purifier',
    status: 'current',
    aliases: ['air quality card', 'air purifier card', 'particulate', 'PM2.5'],
    visibleLabels: ['Air Quality', 'Air Purifier', 'Fan Modes', 'Auto Modes', 'Manual Modes'],
    ownsSurfaceIds: [roomCardFamilySurfaceId('air')],
    keywords: ['air', 'purifier', 'particulate', 'fan mode', 'auto', 'manual', 'sleep'],
    tasks: [
      'What does an Air Quality card report?',
      'How do I change an air purifier mode?',
      'Why do Air Quality and Air Purifier open the same sheet?',
    ],
    coversRoutes: ['living-room', 'guest-room', 'master-bedroom', 'office', 'music-room', 'theater-room'],
    blocks: [],
    familyGuide: {
      cardKind: 'air',
      purpose: 'Air cards combine two related ideas without treating them as the same state. A header Air Quality card summarizes particulate and the derived air-quality reading. A body Air Purifier card emphasizes the configured purifier mode and fan state. Both are entry points to the same room-specific purifier controls, so either can be used when the compact summary needs more context.',
      appearsOn: {
        routeTypes: ['Room header summaries', 'Room Climate sections'],
        explanation: 'Air Quality appears in the horizontal header on rooms that have a particulate sensor. Air Purifier appears in that room’s Climate section when controllable purifier mode and fan entities are configured. Rooms without that hardware do not show placeholder air cards.',
      },
      actionSemantics: [
        'Selecting either configured air opener opens the focused purifier sheet; selecting the card itself does not immediately change purifier power or speed.',
        'Fan Modes chooses Manual, Sleep, or Auto. Auto reveals Default, Quiet, and Efficient choices, while Manual reveals Off, Low, Medium, and High fan percentages.',
      ],
      persistentStateMeanings: [
        { label: 'Good or low particulate', meaning: 'The reported air sample is comparatively clean; purifier mode may still be Off, Sleep, Manual, or Auto.' },
        { label: 'Elevated or poor particulate', meaning: 'The sensor is reporting more fine particles. Open the sheet to compare the reading with the current purifier mode rather than assuming the fan failed.' },
        { label: 'Manual, Sleep, or Auto', meaning: 'This is the purifier operating strategy. It is separate from the measured air-quality summary and remains selected until Home Assistant reports another mode.' },
        { label: 'Unavailable or unknown', meaning: 'The required sensor or control state is missing, so the summary or affected choices are muted instead of guessing.' },
      ],
      unavailableAndDisabledBehavior: 'The opener is muted when its primary displayed entity is missing, unknown, or unavailable. Inside the sheet, each mode group disables independently: missing fan mode disables Fan Modes, missing auto mode disables Auto Modes, and a missing fan state disables Manual speeds. A missing optional control must not make another available control look confirmed.',
      optimisticAndConfirmationBehavior: 'Purifier choices send one Home Assistant service command and the persistent selected highlight follows the state that Home Assistant reports back. The card does not invent a cleaner reading or a new fan mode. If a command is slow, leave the sheet open and wait for the active option and subtitle to confirm; an unchanged highlight means confirmation has not arrived.',
      safetyAndLimitations: {
        title: 'Air readings are guidance, not a safety instrument',
        text: 'A compact particulate or quality label cannot identify smoke, gas, allergens, or every hazardous condition. Use appropriate dedicated alarms and follow household safety procedures. Do not repeatedly switch modes while the purifier is still responding, and do not assume an Off manual speed means the room air is good.',
      },
      troubleshootingChecks: [
        'If Air Quality and Air Purifier open the same destination, treat that as intentional and compare the reading, mode, and fan state inside the shared sheet.',
        'If Auto Modes are missing, confirm Fan Modes currently reports Auto; if Manual speeds are missing, confirm it reports Manual.',
        'If a mode remains unselected after one command, wait for Home Assistant confirmation, then check the purifier integration before trying again.',
        'If the particulate summary is unavailable while modes work, investigate the room sensor separately from the purifier controls.',
      ],
      screenshotIds: ['guest-room-page-context', 'room-air-sheet'],
      relatedArticleIds: ['thermostat-and-contacts', 'device-families', 'room-living-room'],
    },
  },
  appliance: {
    id: roomCardFamilyArticleId('appliance'),
    kind: 'family-guide',
    sectionId: 'rooms',
    parentId: 'device-families',
    title: 'Appliance cards',
    summary: 'Understand the dishwasher card, its changing progress summary, and commands that remain inside its detail sheet.',
    icon: 'mdi:dishwasher',
    status: 'current',
    aliases: ['dishwasher card', 'appliance status', 'dishwasher progress'],
    visibleLabels: ['Appliances', 'Dishwasher', 'Start', 'Resume', 'Stop'],
    ownsSurfaceIds: [roomCardFamilySurfaceId('appliance')],
    keywords: ['appliance', 'dishwasher', 'program', 'progress', 'clean', 'door', 'supply'],
    tasks: [
      'How do I open the dishwasher controls?',
      'What does the dishwasher progress card mean?',
      'Why is a dishwasher command disabled?',
    ],
    coversRoutes: ['kitchen'],
    blocks: [],
    familyGuide: {
      cardKind: 'appliance',
      purpose: 'Appliance cards present a stable room entry point for equipment whose useful controls are too detailed for a one-tap tile. The current configured appliance is the Kitchen dishwasher. Its card changes from the selected program summary to active operation progress when a run or pause is reported, while the focused sheet owns program options and start, resume, or stop commands.',
      appearsOn: {
        routeTypes: ['Room body Appliance sections'],
        explanation: 'The dishwasher is a full-width card in the Kitchen Appliances section. It is not duplicated in the room header because operation, door, program, supply, and clean state need more space than a compact summary can safely explain.',
      },
      actionSemantics: [
        'Selecting the available dishwasher card opens the dishwasher sheet; the card itself never starts, resumes, or stops a cycle.',
        'Inside the sheet, program and option changes are separate from run commands. Start begins the selected program, Resume continues a paused run, and Stop interrupts the active operation.',
      ],
      persistentStateMeanings: [
        { label: 'Ready or idle', meaning: 'No active progress is reported. The selected program and current clean or door context are the useful preparation states.' },
        { label: 'Run or pause with percentage', meaning: 'The card temporarily emphasizes operation progress and shows the reported completion percentage.' },
        { label: 'Clean', meaning: 'The appliance reports a completed clean load; a separate unopened-clean indicator may preserve that message until the door is opened.' },
        { label: 'Unavailable', meaning: 'Both the selected-program and operation sources are unusable, so the opener is disabled rather than presenting stale controls.' },
      ],
      unavailableAndDisabledBehavior: 'The card remains usable when one supporting dishwasher entity is temporarily missing but the primary program or operation state still provides a coherent view. It becomes unavailable when both key sources cannot be read. Individual sheet controls also disable when their required option, door, or operation precondition is not satisfied; disabled controls must not be treated as an invitation to repeat another command.',
      optimisticAndConfirmationBehavior: 'Dishwasher commands briefly show the requested Start, Resume, or Stop operation while Home Assistant and the appliance update. That temporary state clears when the live operation changes or confirms it and reverts if confirmation never arrives. Program, progress, door, clean, and supply facts continue to come from Home Assistant rather than being invented by the app.',
      safetyAndLimitations: {
        title: 'Check the appliance before changing a cycle',
        text: 'Starting or resuming can move water and heat the appliance, while Stop can interrupt a load. Confirm the door is closed, the selected program is appropriate, and nobody is servicing the machine. The dashboard does not replace appliance warnings, leak protection, or physical controls.',
      },
      troubleshootingChecks: [
        'If the card shows Unavailable, check whether both the selected program and operation state are missing before troubleshooting the entire Kitchen page.',
        'If Start is disabled, verify the door and selected program in the sheet and correct those prerequisites first.',
        'If progress does not advance, compare the operation label with the physical appliance before issuing another run command.',
        'If Clean persists after unloading, confirm the door-open event reached Home Assistant instead of manually clearing unrelated helpers.',
      ],
      screenshotIds: ['kitchen-page-context', 'room-dishwasher-sheet'],
      relatedArticleIds: ['media-appliances-vehicle', 'room-kitchen', 'troubleshooting'],
    },
  },
  climate: {
    id: roomCardFamilyArticleId('climate'),
    kind: 'family-guide',
    sectionId: 'rooms',
    parentId: 'device-families',
    title: 'Climate cards and room sheets',
    summary: 'Open room climate summaries and distinguish shared thermostat sheets from SleepyPod bed controls.',
    icon: 'mdi:thermostat',
    status: 'current',
    aliases: ['room climate card', 'temperature range', 'SleepyPod card', 'bed climate'],
    visibleLabels: ['Climate', 'Whole Home', 'Rooms', 'Alarms', 'Schedule'],
    ownsSurfaceIds: [roomCardFamilySurfaceId('climate')],
    keywords: ['climate', 'temperature', 'thermostat', 'heating', 'cooling', 'idle', 'SleepyPod'],
    tasks: [
      'How do I open a room climate sheet?',
      'What does a heating or cooling climate color mean?',
      'Why does a SleepyPod card open different controls?',
    ],
    coversRoutes: ['living-room', 'guest-room', 'master-bedroom', 'gym', 'hallway', 'office', 'kitchen', 'dining-room', 'music-room', 'theater-room', 'downstairs-hallway', 'guest-bathroom', 'master-bathroom', 'entryway'],
    blocks: [],
    familyGuide: {
      cardKind: 'climate',
      purpose: 'Climate cards summarize comfort state and open the controls appropriate to the configured equipment. Most room-header Climate cards open a shared room sheet containing the virtual thermostat and its related readings. Master Bedroom SleepyPod cards are also climate family members, but they open a bed-side sheet with temperature stages, alarms, and schedule behavior rather than the ordinary room thermostat.',
      appearsOn: {
        routeTypes: ['Room header summaries', 'Room body sleep-device sections'],
        explanation: 'A Climate summary appears in most room headers when a room range is configured. SleepyPod climate cards appear in the Master Bedroom body. Rooms without a configured climate source omit the card instead of displaying a generic thermostat.',
      },
      actionSemantics: [
        'Selecting a standard Climate summary opens the matching room climate sheet; it does not immediately alter a setpoint or HVAC mode.',
        'Selecting a SleepyPod side opens its dedicated sheet, where bed temperature, alarms, and scheduled stages remain scoped to that side.',
      ],
      persistentStateMeanings: [
        { label: 'Heating', meaning: 'The configured climate source reports active heating; warm color is a persistent equipment-state cue, not tap feedback.' },
        { label: 'Cooling', meaning: 'The configured source reports active cooling and uses the cool climate treatment.' },
        { label: 'Idle', meaning: 'The climate control is available but is not currently heating or cooling toward the target.' },
        { label: 'Off', meaning: 'The controlled climate source is off. A separate occupancy cue can still show that the room is occupied.' },
      ],
      unavailableAndDisabledBehavior: 'A missing room climate source mutes the opener and prevents the sheet from implying that controls are usable. Within a room or bed sheet, individual controls disable when their backing entity, side, schedule, or supported feature is unavailable. A room can still report sensors even when a setpoint control is disabled, so read each section independently.',
      optimisticAndConfirmationBehavior: 'Interactive thermostat and bed controls may show the intended setpoint or choice immediately while confirmation is pending. That temporary intent clears when Home Assistant reports a changed live value or confirms it and reverts when no confirmation arrives. Header summaries continue to follow live room state; opening a sheet alone does not create a temporary temperature change.',
      safetyAndLimitations: {
        title: 'Comfort commands can affect shared equipment',
        text: 'A room sheet participates in Home Assistant-owned thermostat logic, contact safeguards, occupancy tracking, and whole-home mode decisions. Do not use a room control to bypass an open-door warning or equipment safety limit. Bed climate changes affect the selected side only but can still disrupt an active sleep schedule.',
      },
      troubleshootingChecks: [
        'If the room range looks wrong, compare the room sheet sensors, contact state, occupancy, and whole-home mode before changing a target.',
        'If a SleepyPod side is muted, verify that side is available and powered rather than changing the other side.',
        'If a setpoint briefly changes and returns, wait for Home Assistant confirmation and inspect the controlling automation or integration.',
        'If a room has no Climate card, verify the route configuration instead of expecting every room to receive a placeholder.',
      ],
      screenshotIds: ['guest-room-page-context', 'room-climate-sheet'],
      relatedArticleIds: ['thermostat-and-contacts', 'thermostat-page-guide', 'wake-alarms'],
    },
  },
  contact: {
    id: roomCardFamilyArticleId('contact'),
    kind: 'family-guide',
    sectionId: 'rooms',
    parentId: 'device-families',
    title: 'Contact and access cards',
    summary: 'Read door and window summaries, open sensor details, and recognize the garage cards that toggle immediately.',
    icon: 'mdi:door',
    status: 'current',
    aliases: ['contact sensor card', 'door card', 'window card', 'garage door card'],
    visibleLabels: ['Door', 'Doors', 'Window', 'Windows', 'Left Door', 'Right Door'],
    ownsSurfaceIds: [roomCardFamilySurfaceId('contact')],
    keywords: ['contact', 'door', 'window', 'open', 'closed', 'garage', 'toggle'],
    tasks: [
      'What does an open contact card mean?',
      'How do I see which door or window is open?',
      'Why does a garage door card act immediately?',
    ],
    coversRoutes: ['living-room', 'guest-room', 'master-bedroom', 'gym', 'office', 'kitchen', 'dining-room', 'back-deck', 'music-room', 'theater-room', 'downstairs-hallway', 'garage', 'entryway'],
    blocks: [],
    familyGuide: {
      cardKind: 'contact',
      purpose: 'Contact cards report physical openings such as doors, windows, and grouped garage access points. Most header cards are detail openers: they lead to a sheet that identifies the specific sensor or sensors behind the compact summary. The Garage body also uses contact-kind cards for Left Door and Right Door, but those two are deliberate immediate cover toggles rather than read-only detail openers.',
      appearsOn: {
        routeTypes: ['Room header summaries', 'Room body Garage Doors section'],
        explanation: 'Door, Doors, Window, or Windows appears in the header when the room has configured contact sensors. The Garage route adds two body cards for the controllable garage covers. The same family name therefore includes both sensing and physical access behavior.',
      },
      actionSemantics: [
        'Selecting a header contact summary opens the matching detail sheet and does not change the physical opening.',
        'Selecting Left Door or Right Door sends a direct toggle command with no detail sheet or confirmation. Read the current state and verify the doorway before using those body cards.',
      ],
      persistentStateMeanings: [
        { label: 'All Closed or Closed', meaning: 'Every contact represented by the summary currently reports closed.' },
        { label: 'One or more Open', meaning: 'At least one represented contact reports open; grouped summaries include an open count when available.' },
        { label: 'Opening or Closing', meaning: 'A controllable garage cover is moving and should be allowed to finish before another toggle.' },
        { label: 'Unknown or unavailable', meaning: 'Home Assistant cannot provide a reliable physical state, so the card is muted and must not be assumed closed.' },
      ],
      unavailableAndDisabledBehavior: 'A header opener is disabled when its primary contact state is unavailable. Detail sheets can still show which individual sensor is missing when the group is available enough to open. Direct garage cards are disabled when their cover state is missing or unavailable; the app does not send a blind toggle when it cannot show a usable state.',
      optimisticAndConfirmationBehavior: 'Contact summaries follow live sensor reports and do not temporarily claim that a door or window closed before confirmation. Garage toggles also leave the persistent state tied to Home Assistant confirmation, because movement and obstruction can prevent the requested result. After selecting a garage card, watch for Opening, Closing, Open, or Closed rather than treating the tap itself as success.',
      safetyAndLimitations: {
        title: 'A garage toggle can move a real door',
        text: 'Confirm the doorway is clear and that people, pets, and vehicles are safe before using Left Door or Right Door. A sensor label is not a substitute for visual inspection. Never interpret Unknown or Unavailable as Closed, especially when climate or security behavior depends on the same contact.',
      },
      troubleshootingChecks: [
        'If a grouped card says Open, open its detail sheet and identify the exact contact before changing climate or security settings.',
        'If a garage door does not move, wait for the displayed state to settle and inspect the physical opener or obstruction before toggling again.',
        'If a contact is unavailable, check that sensor or cover integration rather than assuming every item in the group failed.',
        'If climate pauses after a door closes, confirm the contact has actually returned to Closed in Home Assistant.',
      ],
      screenshotIds: ['back-deck-page-context', 'room-contact-sheet'],
      relatedArticleIds: ['thermostat-and-contacts', 'security-access-controls', 'room-garage'],
    },
  },
  fan: {
    id: roomCardFamilyArticleId('fan'),
    kind: 'family-guide',
    sectionId: 'rooms',
    parentId: 'device-families',
    title: 'Fan cards',
    summary: 'Use the bathroom fan cards as direct toggles and wait for the live switch state to confirm the result.',
    icon: 'mdi:fan',
    status: 'current',
    aliases: ['bathroom fan', 'exhaust fan', 'fan toggle'],
    visibleLabels: ['Fan', 'Climate'],
    ownsSurfaceIds: [roomCardFamilySurfaceId('fan')],
    keywords: ['fan', 'bathroom', 'toggle', 'switch', 'ventilation', 'direct action'],
    tasks: [
      'How do I toggle a bathroom fan?',
      'Why does the Fan card open no sheet?',
      'What should I check when a fan stays on?',
    ],
    coversRoutes: ['guest-bathroom', 'master-bathroom'],
    blocks: [],
    familyGuide: {
      cardKind: 'fan',
      purpose: 'Fan cards provide a deliberately simple direct action for the bathroom exhaust switches. They show the current switch state and send one toggle command when selected. Unlike vent, climate, purifier, or humidifier cards, the current fan cards do not open a detail sheet because there are no additional configured modes or settings to present.',
      appearsOn: {
        routeTypes: ['Room body Climate sections'],
        explanation: 'The Guest Bathroom and Master Bathroom Climate sections each include a Fan card beside the room vent and heated towel control. The card remains in the body rather than the header because it is an immediate device command, not a whole-room summary.',
      },
      actionSemantics: [
        'Selecting an available Fan card immediately toggles the configured switch through Home Assistant. There is no confirmation dialog and no intermediate detail page.',
        'The same action means turn on when the live switch is Off and turn off when it is On; the service target remains the configured bathroom fan.',
      ],
      persistentStateMeanings: [
        { label: 'On', meaning: 'Home Assistant reports the fan switch energized, so the card uses its active climate treatment.' },
        { label: 'Off', meaning: 'Home Assistant reports the fan switch off and the card remains muted.' },
        { label: 'Unavailable', meaning: 'The switch cannot be read or controlled, so the card has no click action.' },
      ],
      unavailableAndDisabledBehavior: 'When the switch is missing, unknown, or unavailable, the Fan card is muted and non-clickable. The dashboard does not fall back to a guessed command or a generic fan service. Because this is a direct toggle, there is no separate sheet that can remain partly usable when the primary switch is unavailable.',
      optimisticAndConfirmationBehavior: 'The fan card follows the live Home Assistant switch state rather than forcing a local On or Off result. The command is sent immediately, but the persistent active color changes only when the switch report changes. Wait for that confirmation; if it never arrives, the visible state remains the best available truth and a second toggle could reverse an already delayed command.',
      safetyAndLimitations: {
        title: 'Direct toggles have no confirmation',
        text: 'A selection can start or stop ventilation immediately. Check whether the room needs continued moisture removal and avoid rapid repeated toggles. The card controls only the configured switch; it does not measure humidity, guarantee airflow, or coordinate automatically with the towel rack or room vent.',
      },
      troubleshootingChecks: [
        'If the card remains Off after one selection, wait for the switch report before selecting it again.',
        'If the card is unavailable, check the bathroom switch connection and Home Assistant entity rather than the room climate sheet.',
        'If the fan runs unexpectedly, review Home Assistant automations or physical switch use because the app card sends only a direct toggle.',
        'If ventilation is weak while the card says On, inspect the physical fan and airflow; the card reports electrical state only.',
      ],
      screenshotIds: ['guest-bathroom-page-context'],
      relatedArticleIds: ['media-appliances-vehicle', 'room-guest-bathroom', 'room-master-bathroom'],
    },
  },
  grill: {
    id: roomCardFamilyArticleId('grill'),
    kind: 'family-guide',
    sectionId: 'rooms',
    parentId: 'device-families',
    title: 'Grill cards',
    summary: 'Open grill details only while the grill is active, then read probes and use supported cooking switches carefully.',
    icon: 'mdi:grill',
    status: 'current',
    aliases: ['Bear Grills', 'pellet grill', 'grill probe', 'Super Smoke'],
    visibleLabels: ['Bear Grills', 'Probe 1', 'Pellet Level', 'Keep Warm', 'Super Smoke'],
    ownsSurfaceIds: [roomCardFamilySurfaceId('grill')],
    keywords: ['grill', 'pellet', 'probe', 'keep warm', 'super smoke', 'conditional opener'],
    tasks: [
      'When can I open the grill sheet?',
      'How do I read the grill probe and pellet level?',
      'Why is the grill card muted while off?',
    ],
    coversRoutes: ['back-deck'],
    blocks: [],
    familyGuide: {
      cardKind: 'grill',
      purpose: 'The grill card is a conditional detail opener for the Back Deck pellet grill. It keeps the room page quiet while the grill is off, unknown, or unavailable, then opens a compact sheet during an active session. The sheet combines the reported grill state, temperature probe, pellet level, and the supported Keep Warm and Super Smoke switches.',
      appearsOn: {
        routeTypes: ['Room body Grill sections'],
        explanation: 'Bear Grills appears only in the Back Deck Grill section. It is not a permanent header summary because the focused controls are relevant only during an active cook and the card intentionally becomes status-only when the grill is not available for interaction.',
      },
      actionSemantics: [
        'Selecting the card opens the grill sheet only when the displayed grill state is active and not one of the configured disabled states.',
        'Probe and pellet cards are read-only. Keep Warm and Super Smoke are direct switch toggles inside the sheet and do not open another confirmation layer.',
      ],
      persistentStateMeanings: [
        { label: 'Off', meaning: 'The grill is not active. The opener is disabled and the muted card acts only as a status report.' },
        { label: 'Active cooking state', meaning: 'The grill reports an operating state, so the card can open the detail sheet.' },
        { label: 'Keep Warm or Super Smoke On', meaning: 'The corresponding grill feature switch is enabled and remains highlighted until Home Assistant reports it off.' },
        { label: 'Unknown or unavailable', meaning: 'The grill session cannot be trusted, so the opener and affected detail controls are disabled.' },
      ],
      unavailableAndDisabledBehavior: 'Off, Unknown, and Unavailable are explicit disabled states for the room card. The sheet cannot be opened from those states. Once open, a missing probe or pellet sensor remains a disabled readout while an independently available switch can still be used. The app does not invent a temperature, pellet percentage, or cooking state.',
      optimisticAndConfirmationBehavior: 'The grill opener and detail cards follow live Home Assistant state. Keep Warm and Super Smoke send direct toggle commands, and their persistent selected appearance changes with the returned switch state rather than a local guess. Wait for the feature card to confirm before selecting it again, especially when the grill connection is slow.',
      safetyAndLimitations: {
        title: 'The dashboard does not supervise a cook',
        text: 'Grills involve heat, fire, fuel, and food-safety risks. Stay physically present, follow manufacturer guidance, and use the grill’s own alarms and shutdown procedures. Probe and pellet values can be delayed or unavailable. Do not enable cooking features remotely unless the grill and surrounding area have been checked.',
      },
      troubleshootingChecks: [
        'If the card is muted, confirm whether the grill reports Off, Unknown, or Unavailable before expecting the sheet to open.',
        'If a probe or pellet reading is unavailable, inspect that sensor independently; another switch in the sheet may still be connected.',
        'If Keep Warm or Super Smoke does not confirm, wait for the live switch state and check the grill integration before toggling again.',
        'If the physical grill state disagrees with the page, trust the appliance controls and stop using remote commands until reporting recovers.',
      ],
      screenshotIds: ['back-deck-page-context', 'room-grill-sheet'],
      relatedArticleIds: ['media-appliances-vehicle', 'room-back-deck', 'troubleshooting'],
    },
  },
  humidifier: {
    id: roomCardFamilyArticleId('humidifier'),
    kind: 'family-guide',
    sectionId: 'rooms',
    parentId: 'device-families',
    title: 'Humidifier cards and schedules',
    summary: 'Read power, humidity, water, and tank warnings, then use Controls, Schedules, and Info safely.',
    icon: 'mdi:air-humidifier',
    status: 'current',
    aliases: ['humidifier card', 'water low', 'tank removed', 'humidifier activities'],
    visibleLabels: ['Humidifier', 'Controls', 'Schedules', 'Info', 'Water Low', 'Tank Removed'],
    ownsSurfaceIds: [roomCardFamilySurfaceId('humidifier')],
    keywords: ['humidifier', 'humidity', 'mist', 'warm', 'schedule', 'timer', 'tank', 'water'],
    tasks: [
      'How do I open humidifier controls?',
      'What do Water Low and Tank Removed mean?',
      'How do humidifier schedules confirm their settings?',
    ],
    coversRoutes: ['master-bedroom'],
    blocks: [],
    familyGuide: {
      cardKind: 'humidifier',
      purpose: 'The Humidifier card summarizes the Master Bedroom device without hiding important water and tank warnings. Selecting it opens one shared modal with Controls, Schedules, and Info. Controls owns immediate power, mode, target humidity, mist, warmth, display, and timer choices; Schedules owns reusable activities; Info reports supporting device state.',
      appearsOn: {
        routeTypes: ['Room body Climate sections'],
        explanation: 'The configured humidifier appears in the Master Bedroom Climate section. It is kept out of the header because its warning hierarchy and multi-tab workflow need more room than a compact status chip. Future configured humidifiers can reuse the same family behavior.',
      },
      actionSemantics: [
        'Selecting the available card opens the Humidifier modal and does not toggle power directly.',
        'Controls sends focused device commands. Schedules creates, edits, enables, or disables timed activities, while Info remains read-only.',
      ],
      persistentStateMeanings: [
        { label: 'Off', meaning: 'Power is off. The card remains available for opening the modal and reviewing schedules or device information.' },
        { label: 'On or Humidifying', meaning: 'Power is on; Humidifying additionally indicates that mist output is currently active.' },
        { label: 'Water Low', meaning: 'The water warning takes priority over the ordinary On summary and uses a warning treatment.' },
        { label: 'Tank Removed', meaning: 'The tank warning takes highest priority and uses a danger treatment because normal humidifying cannot continue.' },
      ],
      unavailableAndDisabledBehavior: 'The card is disabled when the configured humidifier mapping is missing or its power state is unknown or unavailable. Inside the modal, controls disable according to the entities and options they need. Saving a schedule is disabled while data is invalid or already being saved, and conflicts are shown rather than silently overwriting another activity.',
      optimisticAndConfirmationBehavior: 'Humidifier controls can show the intended power, mode, target, mist, warmth, display, or timer choice immediately while confirmation is pending. The temporary value clears when Home Assistant changes or confirms the live state and reverts if it never confirms. Schedule saves remain visibly in progress and the persisted activity list is the confirmation that Home Assistant accepted the change.',
      safetyAndLimitations: {
        title: 'Resolve water and tank warnings first',
        text: 'Do not repeatedly start the humidifier when Water Low or Tank Removed is shown. Refill and reseat the device according to manufacturer instructions. High humidity can cause condensation or mold, and warm mist can create heat risk. Schedules may cross midnight, so review days, start, end, and mode before enabling an overnight activity.',
      },
      troubleshootingChecks: [
        'If the card says Tank Removed or Water Low, correct the physical condition before troubleshooting modes or schedules.',
        'If a control briefly changes and returns, wait for Home Assistant confirmation and check the humidifier integration.',
        'If a schedule cannot save, review its days, time range, mode settings, and any displayed conflict.',
        'If the card is unavailable but the device works physically, verify the configured power and supporting entities rather than creating a second schedule.',
      ],
      screenshotIds: ['master-bedroom-page-context', 'room-humidifier-sheet'],
      relatedArticleIds: ['humidifier-schedule', 'room-master-bedroom', 'schedule-systems'],
    },
  },
  laundry: {
    id: roomCardFamilyArticleId('laundry'),
    kind: 'family-guide',
    sectionId: 'rooms',
    parentId: 'device-families',
    title: 'Laundry status cards',
    summary: 'Read washer and dryer helper state without expecting a remote start, stop, or detail sheet.',
    icon: 'mdi:washing-machine',
    status: 'current',
    aliases: ['washer card', 'dryer card', 'laundry helper', 'laundry status'],
    visibleLabels: ['Washing Machine', 'Dryer', 'Appliances'],
    ownsSurfaceIds: [roomCardFamilySurfaceId('laundry')],
    keywords: ['laundry', 'washer', 'dryer', 'status only', 'running', 'notification'],
    tasks: [
      'What do the laundry cards report?',
      'Can I start the washer from the room page?',
      'Why does a laundry card have no disclosure arrow?',
    ],
    coversRoutes: ['garage'],
    blocks: [],
    familyGuide: {
      cardKind: 'laundry',
      purpose: 'Laundry cards are status-only summaries for the Garage washing machine and dryer helpers. They make current helper state visible beside other Garage appliances without pretending the machines support safe remote cycle control. The cards do not open a sheet, navigate elsewhere, or send a service command when selected.',
      appearsOn: {
        routeTypes: ['Room body Appliance sections'],
        explanation: 'Washing Machine and Dryer appear in the Garage Appliances section. They are body cards rather than header summaries because they are useful while doing laundry but are not primary navigation targets or whole-room conditions.',
      },
      actionSemantics: [
        'There is no action on the current laundry cards. Selecting or tapping the surface does not start, stop, pause, acknowledge, or reset either appliance.',
        'Home Assistant automations and helpers own cycle detection and any notifications; the app only displays their resulting state.',
      ],
      persistentStateMeanings: [
        { label: 'On or active helper', meaning: 'Home Assistant currently considers the appliance cycle started or running according to the configured helper logic.' },
        { label: 'Off or inactive helper', meaning: 'No active cycle is represented by the helper. This does not prove the appliance is empty or safe to open.' },
        { label: 'Unavailable or unknown', meaning: 'The helper cannot be read, so the card is muted and should not be used to infer cycle completion.' },
      ],
      unavailableAndDisabledBehavior: 'Because the family is status-only, there is no command to disable. Missing, unknown, or unavailable helper state simply mutes the card and displays an unavailable result. The dashboard does not substitute physical appliance state, clear a helper, or expose a fallback action.',
      optimisticAndConfirmationBehavior: 'Laundry cards show no temporary requested state because the user cannot issue a laundry command from them. Every visible change is confirmation from Home Assistant’s helper or automation path. If the card changes later than the physical machine, the delay belongs to the sensing and helper logic rather than a pending app action.',
      safetyAndLimitations: {
        title: 'Status does not replace checking the appliance',
        text: 'A helper can lag, miss vibration, or remain active after a cycle. Check the washer or dryer directly before opening, unloading, or servicing it. The dashboard does not provide remote start or stop and should not be modified to duplicate appliance safety logic that belongs in Home Assistant or the appliance itself.',
      },
      troubleshootingChecks: [
        'If the card stays active after a cycle, inspect the Home Assistant helper and its sensing automation rather than tapping the card.',
        'If the card never becomes active, verify the appliance detector and helper updates while the machine is actually running.',
        'If the card is unavailable, check the helper entity and automation dependencies separately for the washer or dryer.',
        'If a completion notification disagrees with the card, compare their source automation traces before changing the dashboard.',
      ],
      screenshotIds: ['garage-page-context'],
      relatedArticleIds: ['media-appliances-vehicle', 'room-garage', 'automation-catalog'],
    },
  },
  light: {
    id: roomCardFamilyArticleId('light'),
    kind: 'family-guide',
    sectionId: 'rooms',
    parentId: 'device-families',
    title: 'Light cards, brightness, and details',
    summary: 'Open room light sheets, adjust brightness, reach individual details, and recognize direct towel-rack toggles.',
    icon: 'mdi:lightbulb-group',
    status: 'current',
    aliases: ['room light card', 'brightness slider', 'light details', 'towel rack'],
    visibleLabels: ['Light', 'Lights', 'Brightness', 'Living Room Lights', 'Towel Rack'],
    ownsSurfaceIds: [roomCardFamilySurfaceId('light')],
    keywords: ['light', 'brightness', 'details', 'group', 'individual', 'toggle', 'towel rack'],
    tasks: [
      'How do I open a room light sheet?',
      'How do I adjust brightness or open light details?',
      'Why does a Towel Rack card toggle immediately?',
    ],
    coversRoutes: ['living-room', 'guest-room', 'master-bedroom', 'gym', 'hallway', 'office', 'kitchen', 'dining-room', 'back-deck', 'music-room', 'theater-room', 'downstairs-hallway', 'guest-bathroom', 'master-bathroom', 'entryway'],
    blocks: [],
    familyGuide: {
      cardKind: 'light',
      purpose: 'Light cards provide two intentionally different room interactions. Header Light or Lights summaries open the room’s light sheet, where group and individual fixtures can be inspected, toggled, dimmed, and opened for deeper details. Bathroom Towel Rack cards use the light family styling but are immediate switch toggles with a warm active color and no light sheet.',
      appearsOn: {
        routeTypes: ['Room header summaries', 'Room body Climate sections'],
        explanation: 'Standard room light groups appear in the horizontally scrollable header. Heated towel controls appear in the Guest Bathroom and Master Bathroom body beside fan and vent controls. The generated room reference labels each instance so the opener and direct-toggle branches are not confused.',
      },
      actionSemantics: [
        'Selecting a standard Light or Lights header summary opens the focused room sheet; it does not toggle the entire room as a side effect of opening.',
        'Inside the sheet, the power area sends the configured light command, the brightness control adjusts level, and the dedicated detail opener leads to individual light information without shadow-clicking another control.',
        'Selecting Towel Rack immediately toggles its configured switch and opens no sheet or confirmation.',
      ],
      persistentStateMeanings: [
        { label: 'On', meaning: 'The group, fixture, or towel switch reports active; brightness may provide additional level context for lights.' },
        { label: 'Off', meaning: 'The controlled light or switch reports off and uses the muted treatment.' },
        { label: 'Partial group activity', meaning: 'A room group can be On because one or more individual fixtures are active; open the sheet to identify them.' },
        { label: 'Unavailable', meaning: 'The required entity cannot be read, so the opener or direct action is disabled.' },
      ],
      unavailableAndDisabledBehavior: 'An unavailable header group cannot open a misleading room sheet from that card. Within the sheet, unavailable individual fixtures remain identifiable but their power, brightness, or detail actions disable as appropriate. A Towel Rack card becomes non-clickable when its switch state is missing, unknown, or unavailable.',
      optimisticAndConfirmationBehavior: 'Shared light controls temporarily show the requested power or brightness while Home Assistant catches up, then clear when the live state changes or confirms and revert if it does not. The room header continues to summarize live group state. Direct towel toggles follow their returned switch state, so wait for the persistent warm or muted treatment to confirm.',
      safetyAndLimitations: {
        title: 'Opening details is different from changing power',
        text: 'Use the explicit detail control when you need more information; do not assume every part of a brightness card has the same action. A towel rack produces heat even though it uses the light card family, so check the room and do not leave it on unintentionally. Automations can also change lights after a manual command.',
      },
      troubleshootingChecks: [
        'If a room says Lights On, open the sheet and inspect individual fixtures before toggling the whole group.',
        'If brightness changes and then returns, wait for Home Assistant confirmation and check whether an automation or unsupported fixture rejected it.',
        'If the detail page does not open, use the dedicated detail target rather than the power or brightness gesture area.',
        'If a Towel Rack stays unchanged, wait for the live switch state and inspect that switch before toggling again.',
      ],
      screenshotIds: ['status-lights-detail'],
      relatedArticleIds: ['status-lights', 'custom-lights-page-guide', 'presence-based-lighting'],
    },
  },
  media: {
    id: roomCardFamilyArticleId('media'),
    kind: 'family-guide',
    sectionId: 'rooms',
    parentId: 'device-families',
    title: 'Media remote and app cards',
    summary: 'Distinguish remote-sheet openers from immediate room scripts and direct streaming-app launch tiles.',
    icon: 'mdi:remote',
    status: 'current',
    aliases: ['media card', 'SHIELD remote', 'Apple TV card', 'app shortcut'],
    visibleLabels: ['Living Room SHIELD', 'Theater Room', 'Apple TV', 'Controls', 'Apps', 'Devices'],
    ownsSurfaceIds: [roomCardFamilySurfaceId('media')],
    keywords: ['media', 'remote', 'app', 'script', 'shield', 'apple tv', 'projector', 'direct launch'],
    tasks: [
      'Which media cards open a remote?',
      'Which media cards launch an app immediately?',
      'How do I tell a script card from a remote opener?',
    ],
    coversRoutes: ['living-room', 'master-bedroom', 'theater-room'],
    blocks: [],
    familyGuide: {
      cardKind: 'media',
      purpose: 'Media cards cover three distinct branches while preserving one visual family. A card with a configured remote destination opens a focused media sheet. A room activity card runs a Home Assistant script immediately. A branded app tile launches that app through the configured media script without opening the remote first. The generated reference states which branch each card uses.',
      appearsOn: {
        routeTypes: ['Room body Media sections', 'Room body remote sections', 'Media feature pages'],
        explanation: 'Living Room and Theater room pages contain remote openers plus direct app shortcuts. Theater also contains immediate activity scripts such as the SHIELD movie setup and Nintendo Switch setup. Master Bedroom exposes an Apple TV remote opener. The separate Media page reuses the same remote behavior.',
      },
      actionSemantics: [
        'Remote openers display a disclosure and open Controls plus Apps, with Devices available when the remote configuration provides device cards.',
        'Activity cards immediately run their configured Home Assistant script, and branded app tiles immediately call the app-launch script. Neither branch opens a sheet or asks for confirmation first.',
        'Commands inside a remote remain scoped to the configured player, remote, volume device, and supporting equipment for that room.',
      ],
      persistentStateMeanings: [
        { label: 'Playing, paused, or idle', meaning: 'The media player is active enough to report a session state; the remote may expose more controls based on supported features.' },
        { label: 'On activity helper', meaning: 'A configured room activity such as SHIELD or Nintendo Switch currently reports active.' },
        { label: 'Off', meaning: 'The player or activity helper reports inactive; direct scripts can still be available when configured.' },
        { label: 'Unavailable', meaning: 'The required player, helper, or remote source cannot be used, so the affected card or control is muted.' },
      ],
      unavailableAndDisabledBehavior: 'A remote opener or direct card is disabled when its displayed source is missing, unknown, or unavailable. Inside a remote, direction, playback, keyboard, volume, Apps, or Devices can disable independently based on player power and supporting entities. An app image can fall back to its icon and label without changing the launch semantics.',
      optimisticAndConfirmationBehavior: 'Media commands are sent immediately, but player, activity, and device highlights remain tied to Home Assistant state. App launches and room scripts do not claim success solely because the command was sent. Wait for the player, source, or activity helper to update before repeating a launch. Remote tab selection is local navigation, not device confirmation.',
      safetyAndLimitations: {
        title: 'Direct launches can interrupt current media',
        text: 'An app shortcut or room script can power equipment, change inputs, or replace what someone is watching without another confirmation. Check the room first. The dashboard coordinates only the configured Home Assistant command; it cannot guarantee every television, receiver, projector, console, or streaming service completed its part.',
      },
      troubleshootingChecks: [
        'If you expected a remote but an app launched, use the generated room reference to verify whether the card is a remote opener or direct app tile.',
        'If remote controls are disabled, confirm the player and supporting remote or receiver are powered and available.',
        'If a script starts only part of a room, inspect the Devices tab and the Home Assistant script rather than repeatedly running the whole activity.',
        'If an app does not appear, wait for the player state to settle, then check the configured launch script and remote connection.',
      ],
      screenshotIds: ['media-page-context'],
      relatedArticleIds: ['media-page-guide', 'media-appliances-vehicle', 'room-theater-room'],
    },
  },
  occupancy: {
    id: roomCardFamilyArticleId('occupancy'),
    kind: 'family-guide',
    sectionId: 'rooms',
    parentId: 'device-families',
    title: 'Occupancy summary cards',
    summary: 'Read Clear and Occupied summaries, open room sensor details, and recognize status-only occupancy cards.',
    icon: 'mdi:motion-sensor',
    status: 'current',
    aliases: ['occupancy card', 'presence card', 'motion summary', 'room occupied'],
    visibleLabels: ['Occupancy', 'Occupied', 'Clear'],
    ownsSurfaceIds: [roomCardFamilySurfaceId('occupancy')],
    keywords: ['occupancy', 'presence', 'motion', 'clear', 'occupied', 'sensor', 'status only'],
    tasks: [
      'What does an Occupancy card summarize?',
      'How do I see the active room sensors?',
      'Why is some occupancy status not clickable?',
    ],
    coversRoutes: ['living-room', 'guest-room', 'master-bedroom', 'gym', 'hallway', 'office', 'kitchen', 'dining-room', 'back-deck', 'music-room', 'theater-room', 'downstairs-hallway', 'guest-bathroom', 'master-bathroom', 'entryway'],
    blocks: [],
    familyGuide: {
      cardKind: 'occupancy',
      purpose: 'Occupancy cards reduce one or more room sensors to a compact Clear or Occupied summary. Most configured room headers open a focused sheet that lists the individual occupancy zones behind that summary. The Back Deck occupancy card intentionally has no destination and remains status-only, because its single camera-derived occupancy report has no configured room detail sheet.',
      appearsOn: {
        routeTypes: ['Room header summaries'],
        explanation: 'Occupancy appears in room headers when a room or area has a configured presence group or sensor. The number and names of sensors vary by room. The card is omitted where no occupancy source is configured rather than showing a synthetic Clear state.',
      },
      actionSemantics: [
        'Selecting a configured occupancy opener opens the room’s sensor-detail sheet; it does not enable, disable, or reset occupancy.',
        'A status-only occupancy card reports live state and has no disclosure or command. Presence-based lighting settings are managed in their own guide and controls.',
      ],
      persistentStateMeanings: [
        { label: 'Occupied', meaning: 'At least one represented sensor currently reports active occupancy or presence.' },
        { label: 'Clear', meaning: 'No represented sensor currently reports active occupancy. This is a sensor summary, not proof that nobody is present.' },
        { label: 'Mixed detail', meaning: 'A grouped card can read Occupied while only one zone is active; open the sheet to identify the contributing sensor.' },
        { label: 'Unavailable', meaning: 'The primary occupancy source cannot provide a reliable state, so the card is muted instead of assuming Clear.' },
      ],
      unavailableAndDisabledBehavior: 'An unavailable group disables its detail opener. Within an available detail sheet, individual sensors can still show unavailable independently. Status-only occupancy remains non-clickable in every state. The dashboard never clears a sensor, substitutes another room, or turns an unavailable result into Clear.',
      optimisticAndConfirmationBehavior: 'Occupancy is observation-only in the room card family, so there is no temporary user-requested state. Clear and Occupied change only when Home Assistant reports sensor updates. Automatic lighting may react separately, but its intended or delayed light state must not be confused with occupancy confirmation.',
      safetyAndLimitations: {
        title: 'Clear is not a security guarantee',
        text: 'Presence sensors can have blind spots, delays, and quiet periods. Do not use a Clear card as proof that a room, deck, or home is empty. Occupancy summaries inform comfort and lighting behavior but do not replace cameras, contact sensors, alarm systems, or direct visual checks.',
      },
      troubleshootingChecks: [
        'If a grouped card says Occupied unexpectedly, open the detail sheet and identify the active zone before changing automations.',
        'If it says Clear while someone is present, check sensor coverage, timeout behavior, and the Home Assistant group state.',
        'If the Back Deck card does not open, remember that it is intentionally status-only and inspect its source in Home Assistant when needed.',
        'If occupancy updates but lights do not, troubleshoot Presence-Based Lighting separately from the sensor card.',
      ],
      screenshotIds: ['gym-page-context', 'room-occupancy-sheet'],
      relatedArticleIds: ['presence-based-lighting', 'thermostat-and-contacts', 'device-families'],
    },
  },
  power: {
    id: roomCardFamilyArticleId('power'),
    kind: 'family-guide',
    sectionId: 'rooms',
    parentId: 'device-families',
    title: 'Computer power command cards',
    summary: 'Understand the exact On-to-Off and otherwise-to-On input-button branch used by room PC cards.',
    icon: 'mdi:power',
    status: 'current',
    aliases: ['PC power card', 'computer power', 'Wake-on-LAN', 'shutdown button'],
    visibleLabels: ["Stephen's PC", "Steph's PC", 'Theater Room PC'],
    ownsSurfaceIds: [roomCardFamilySurfaceId('power')],
    keywords: ['power', 'computer', 'pc', 'input button', 'on', 'off', 'state dependent'],
    tasks: [
      'How does a PC power card choose its command?',
      'What happens when the power helper is not On?',
      'Why does a PC card open no confirmation?',
    ],
    coversRoutes: ['office', 'theater-room'],
    blocks: [],
    familyGuide: {
      cardKind: 'power',
      purpose: 'Power cards are state-dependent command surfaces for the configured Office and Theater computers. They display a power helper plus an optional human-readable status, then choose one of two Home Assistant input-button commands. The branch is exact: when the displayed power helper is On, the card presses Off; in every other state, it presses On.',
      appearsOn: {
        routeTypes: ['Room body computer sections'],
        explanation: 'Two PC cards appear in the Office PCs section and one appears in the Theater Room PCs section. They are body actions rather than header summaries because selecting them can wake or shut down equipment immediately.',
      },
      actionSemantics: [
        'If the live helper state equals On, selecting the card presses the configured Off input button.',
        'If the helper is Off or any other non-On value, selecting the card presses the configured On input button. No detail sheet or confirmation dialog opens.',
        'Home Assistant scripts or automations behind those input buttons own Wake-on-LAN, shutdown, and any multi-device side effects.',
      ],
      persistentStateMeanings: [
        { label: 'On', meaning: 'The helper reports the PC on, so the next selection is the Off command.' },
        { label: 'Off', meaning: 'The helper reports the PC off, so the next selection is the On command.' },
        { label: 'Any other available state', meaning: 'The branch still chooses On. Read the supporting status subtitle before deciding that is safe.' },
        { label: 'Unavailable or unknown display source', meaning: 'The card is muted and non-clickable, preventing a blind input-button press.' },
      ],
      unavailableAndDisabledBehavior: 'The card disables when the effective displayed entity is missing, unknown, or unavailable. The state-dependent resolver does not run and neither input button is pressed. A supporting subtitle can be unavailable without changing the exact branch, so the primary helper remains the decision source.',
      optimisticAndConfirmationBehavior: 'The card does not temporarily flip the power helper after pressing an input button. Its active or muted treatment follows the state Home Assistant reports. Wake and shutdown can take time; wait for the helper and status subtitle to confirm before selecting again. A repeated selection after delayed reporting can send the opposite command.',
      safetyAndLimitations: {
        title: 'The non-On branch always requests On',
        text: 'Do not assume an unusual helper state is treated as Off for every purpose; it specifically selects the On input button. The command can wake equipment or the Off path can interrupt work. Save work, check who is using the computer, and rely on Home Assistant to own the actual shutdown or wake sequence.',
      },
      troubleshootingChecks: [
        'If the unexpected command runs, verify the exact primary helper state immediately before selection; On is the only value that chooses Off.',
        'If the helper remains unchanged, wait for the computer and Home Assistant automation before pressing the card again.',
        'If the card is unavailable, check the helper and input-button automation rather than the room layout.',
        'If Wake-on-LAN or shutdown only partly completes, inspect the Home Assistant script or automation behind the pressed button.',
      ],
      screenshotIds: ['office-page-context'],
      relatedArticleIds: ['media-appliances-vehicle', 'room-office', 'room-theater-room'],
    },
  },
  vacuum: {
    id: roomCardFamilyArticleId('vacuum'),
    kind: 'family-guide',
    sectionId: 'rooms',
    parentId: 'device-families',
    title: 'Robot vacuum cards and sheets',
    summary: 'Open the correct robot, use its five tabs, and understand cleaning-controller-owned automatic cleaning.',
    icon: 'mdi:robot-vacuum',
    status: 'current',
    aliases: ['vacuum card', 'robot vacuum sheet', 'Auto-Clean', 'vacuum cleaning controller'],
    visibleLabels: ['Robot Vacuum', 'Controls', 'Zones', 'Auto-Clean', 'Actions', 'Info'],
    ownsSurfaceIds: [roomCardFamilySurfaceId('vacuum')],
    keywords: ['vacuum', 'robot', 'controls', 'zones', 'area', 'auto-clean', 'cleaning controller', 'dock'],
    tasks: [
      'How do I open a room robot vacuum?',
      'What do the vacuum sheet tabs control?',
      'How does the automatic cleaning controller use room settings?',
    ],
    coversRoutes: ['living-room', 'music-room', 'theater-room'],
    blocks: [],
    familyGuide: {
      cardKind: 'vacuum',
      purpose: 'Vacuum cards are room-specific openers for the Main Floor, Music Room, and Theater Room robots. They show robot and battery context, then open the full shared sheet. That sheet separates Controls, Zones, Auto-Clean, Actions, and Info so immediate movement commands, selected-room cleaning, automatic-run exclusions, maintenance actions, and read-only status are not mixed together.',
      appearsOn: {
        routeTypes: ['Room body Device sections', 'Vacuums feature page'],
        explanation: 'The three room routes each expose their matching robot in a Devices section. The Vacuums feature page presents the same robots together plus the top-level Auto-Clean controls. Opening from either location reaches the same family behavior for that robot.',
      },
      actionSemantics: [
        'Selecting a room card opens the vacuum sheet; it does not start movement or cleaning from the page card.',
        'Controls owns basic robot commands and cleaning setup. Zones owns selected rooms and the rectangular Area workflow. Auto-Clean chooses rooms to skip when the cleaning controller starts an away clean.',
        'Actions owns supported dock or maintenance commands, while Info reports battery, consumables, errors, and other state.',
      ],
      persistentStateMeanings: [
        { label: 'Docked or idle', meaning: 'The robot is not actively cleaning and may be ready for a new supported command.' },
        { label: 'Cleaning or returning', meaning: 'The robot is moving through an active task or returning to its dock; conflicting controls can disable.' },
        { label: 'Paused', meaning: 'An active task is paused and should be resumed, stopped, or reviewed rather than started again blindly.' },
        { label: 'Error or unavailable', meaning: 'The robot needs attention or its connection is missing; movement and cleaning controls are limited or disabled.' },
      ],
      unavailableAndDisabledBehavior: 'A missing or unavailable robot disables its room opener. Inside the sheet, command availability depends on current state, supported features, selected rooms or area, and cleaning-controller progress. The Area action remains disabled until a valid rectangle is drawn. Auto-Clean exclusions can remain editable without immediately starting a manual clean.',
      optimisticAndConfirmationBehavior: 'Vacuum commands briefly show Start, Pause, Return, and cleaning requests while the robot and cleaning controller update. Commands are queued or disabled when necessary to avoid conflicting service calls. The temporary requested state clears on live confirmation and reverts on timeout or error. Map selection is local preparation until Use This Area and the final clean command are accepted.',
      safetyAndLimitations: {
        title: 'Clear the floor before moving a robot',
        text: 'A vacuum command can move equipment immediately. Remove cables, liquids, fragile items, pet hazards, and blocked-door risks first. Auto-Clean is Home Assistant-owned and can run while away; room skip settings affect cleaning-controller runs but do not replace a physical safety check or change manual selected-room cleaning.',
      },
      troubleshootingChecks: [
        'If the card is unavailable, check that specific robot and battery connection rather than all three vacuum routes.',
        'If Start is disabled, review robot state, selected rooms or area, and any pending cleaning-controller command.',
        'If an automatic run includes or skips the wrong room, inspect the Auto-Clean exclusions and cleaning-controller state, not the manual Zones selection.',
        'If a temporary requested state reverts, read the displayed error or live robot state before sending another command.',
      ],
      screenshotIds: ['music-room-page-context'],
      relatedArticleIds: ['vacuum-cleaning', 'vacuum-area-cleaning', 'vacuums-page-guide'],
    },
  },
  vent: {
    id: roomCardFamilyArticleId('vent'),
    kind: 'family-guide',
    sectionId: 'rooms',
    parentId: 'device-families',
    title: 'Vent group cards',
    summary: 'Open one- or two-vent group sheets, read position state, and keep vent status separate from thermostat commands.',
    icon: 'mdi:air-filter',
    status: 'current',
    aliases: ['vent card', 'room vent', 'vent group', 'register position'],
    visibleLabels: ['Vent', 'Vents', 'Vent 1', 'Vent 2'],
    ownsSurfaceIds: [roomCardFamilySurfaceId('vent')],
    keywords: ['vent', 'vents', 'cover', 'open', 'closed', 'position', 'climate'],
    tasks: [
      'How do I open a room vent group?',
      'What does a vent card position mean?',
      'Why is a vent sheet separate from the climate sheet?',
    ],
    coversRoutes: ['living-room', 'guest-room', 'master-bedroom', 'gym', 'office', 'kitchen', 'dining-room', 'music-room', 'theater-room', 'guest-bathroom', 'master-bathroom'],
    blocks: [],
    familyGuide: {
      cardKind: 'vent',
      purpose: 'Vent cards summarize one or more configured room registers and open a focused group sheet. The group sheet names each physical vent and reports its current cover state. It is intentionally separate from the header Climate sheet: the climate summary explains thermostat and room comfort, while the vent card identifies the actual vent members behind a combined room state.',
      appearsOn: {
        routeTypes: ['Room body Climate sections'],
        explanation: 'Rooms with controllable vents show Vent or Vents in their Climate body section. A singular label represents one configured register; a plural label represents a group such as Vent 1 and Vent 2. Rooms without configured vents omit this family.',
      },
      actionSemantics: [
        'Selecting an available Vent or Vents card opens the configured group sheet; the room card itself does not toggle every vent.',
        'The current group sheet presents compact member states. Thermostat setpoints, whole-home mode, and predictive comfort remain in climate controls rather than this vent inventory.',
      ],
      persistentStateMeanings: [
        { label: 'Open', meaning: 'The represented cover or group reports open and can pass conditioned air according to the physical system.' },
        { label: 'Closed', meaning: 'The represented vent reports closed; this can be an intentional Home Assistant climate decision.' },
        { label: 'Partially open or positioned', meaning: 'A cover can report an intermediate position or mixed group state rather than a simple binary result.' },
        { label: 'Unavailable', meaning: 'The cover state cannot be trusted, so the opener or affected member is muted.' },
      ],
      unavailableAndDisabledBehavior: 'An unavailable primary vent group disables the room opener. In a group sheet, one unavailable member is shown as unavailable without fabricating the state of the others. The sheet does not expose a fallback whole-group toggle, and it does not bypass Home Assistant’s thermostat or vent coordination.',
      optimisticAndConfirmationBehavior: 'The room vent family currently treats its cards and group members as live status surfaces. Opening the sheet creates no temporary requested state, and member positions change only when Home Assistant reports them. If another climate control commands a vent, wait for the returned Open, Closed, or position state before assuming the register moved.',
      safetyAndLimitations: {
        title: 'Do not fight automatic vent coordination',
        text: 'Vent position can be chosen by Home Assistant to protect comfort or equipment behavior. Repeated manual changes outside the documented controls can create poor airflow or pressure. The card cannot confirm physical airflow, a blocked register, or mechanical movement; inspect the room when reported position and comfort disagree.',
      },
      troubleshootingChecks: [
        'If a plural Vents card looks wrong, open the group and compare each named member instead of relying only on the combined state.',
        'If one member is unavailable, troubleshoot that vent connection without assuming the entire climate system is unavailable.',
        'If a vent state changes back, review the room thermostat and automatic vent logic before repeating a command elsewhere.',
        'If the state says Open but airflow is weak, inspect the physical register and HVAC operation because the card reports position only.',
      ],
      screenshotIds: ['guest-room-page-context', 'room-vent-sheet'],
      relatedArticleIds: ['thermostat-and-contacts', 'thermostat-page-guide', 'device-families'],
    },
  },
} satisfies Record<RoomSourceKind, ManualFamilyGuideArticle>

export const ROOM_CARD_FAMILY_GUIDE_ARTICLES: ManualFamilyGuideArticle[] = Object.values(ROOM_CARD_FAMILY_GUIDE_ARTICLES_BY_KIND)
export const ROOM_CARD_FAMILY_GUIDE_IDS = ROOM_CARD_FAMILY_GUIDE_ARTICLES.map((article) => article.id)

export function isManualFamilyGuideArticle(article: ManualArticle): article is ManualFamilyGuideArticle {
  return article.kind === 'family-guide'
}

export function manualFamilyGuideAuthoredTextValues(article: ManualFamilyGuideArticle) {
  const guide = article.familyGuide
  return [
    guide.purpose,
    ...guide.appearsOn.routeTypes,
    guide.appearsOn.explanation,
    ...guide.actionSemantics,
    ...guide.persistentStateMeanings.flatMap((item) => [item.label, item.meaning]),
    guide.unavailableAndDisabledBehavior,
    guide.optimisticAndConfirmationBehavior,
    guide.safetyAndLimitations.title,
    guide.safetyAndLimitations.text,
    ...guide.troubleshootingChecks,
  ]
}

export function manualFamilyGuideWordCount(article: ManualFamilyGuideArticle) {
  return manualFamilyGuideAuthoredTextValues(article).join(' ').trim().split(/\s+/).filter(Boolean).length
}
