import type { ManualPageGuideArticle } from './types'

export const ROOM_PAGE_GUIDE_IDS = [
  'room-living-room',
  'room-guest-room',
  'room-master-bedroom',
  'room-gym',
  'room-hallway',
  'room-office',
  'room-kitchen',
  'room-dining-room',
  'room-back-deck',
  'room-music-room',
  'room-theater-room',
  'room-downstairs-hallway',
  'room-garage',
  'room-guest-bathroom',
  'room-master-bathroom',
  'room-entryway',
] as const

export const ROOM_PAGE_GUIDE_ARTICLES: ManualPageGuideArticle[] = [
  {
    id: 'room-living-room',
    kind: 'page-guide',
    sectionId: 'rooms',
    parentId: 'browse-pages',
    title: 'Living Room page guide',
    summary: 'Lights, comfort, air quality, the main-floor vacuum, and SHIELD media controls in the busiest shared room.',
    icon: 'mdi:sofa',
    status: 'current',
    aliases: ['living room controls', 'living room shield', 'main floor vacuum'],
    visibleLabels: ['Lights', 'Climate', 'Occupancy', 'Window', 'Air Quality', 'Vents', 'Air Purifier', 'Main Floor', 'Remote', 'Living Room SHIELD', 'Quick App Launch'],
    ownsSurfaceIds: ['route:living-room'],
    keywords: ['living room', 'vents', 'air purifier', 'vacuum', 'shield', 'plex', 'youtube', 'netflix'],
    tasks: [
      'How do I control the Living Room lights?',
      'Where do I open the main-floor robot vacuum?',
      'How do I launch an app on the Living Room SHIELD?',
      'What should I check when Living Room air quality changes?',
    ],
    coversRoutes: ['living-room'],
    blocks: [],
    pageGuide: {
      routePath: 'living-room',
      complexity: 'complex',
      generatedRoomPath: 'living-room',
      orientation: 'The Living Room page combines a horizontally scrollable header with four body groups. The header is the quickest way into lights, the room climate sheet, four occupancy zones, the window contact, or air-quality detail. Below it, Climate separates the two physical vents from purifier information, Devices opens the Main Floor robot vacuum, Remote holds the Living Room SHIELD remote opener, and Quick App Launch keeps the branded app tiles that act immediately in their own responsive grid.',
      visiblePageSectionNames: ['Header Summaries', 'Climate', 'Devices', 'Remote', 'Quick App Launch'],
      whatYouCanDo: [
        'Open Lights to work with the complete Living Room light group and its individual fixtures. The header summary opens a sheet first; it is not a one-tap group toggle.',
        'Use Climate to compare the room range and sensor readings, then inspect the Window sheet when an open contact may be affecting comfort behavior. Occupancy opens the four named sensing zones rather than a single generic motion value.',
        'Open Vents to inspect Vent 1 and Vent 2, and open Air Purifier or the Air Quality header summary for particulate, air-quality, fan-mode, and purifier-state information.',
        'Select Main Floor to open the robot-vacuum sheet. From that sheet you can review state and battery, choose supported cleaning behavior, or move into the shared area-cleaning workflow.',
        'Open Living Room SHIELD in the Remote group for the remote sheet with Controls and Apps tabs, directional navigation, playback, keyboard input when available, and Sonos volume actions.',
        'Choose Plex, YouTube, Netflix, Prime Video, Paramount+, or Disney+ from Quick App Launch to launch that app immediately through the configured media command. Those app tiles do not open the remote sheet first.',
      ],
      whatHappensAutomatically: {
        mode: 'automatic',
        items: [
          'Light, climate, occupancy, contact, particulate, purifier, vacuum, and media subtitles refresh as Home Assistant reports new state. An unavailable source is muted so the page does not present a working opener when its required Home Assistant source is missing.',
          'When Presence-Based Lighting is enabled for this room, its occupancy zones can participate in automatic lighting and later clearing behavior without this page remaining open.',
          'An open living-room window can participate in the whole-home contact safeguard that pauses or changes automatic climate decisions until the contact clears.',
          'The Main Floor cleaning controller and media devices continue their Home Assistant-owned routines independently of this page; the cards report the resulting state rather than reproducing that logic locally.',
        ],
      },
      lookHereFirst: [
        { label: 'Scrollable header', explanation: 'Air Quality sits after the other summaries on a phone. Swipe sideways before deciding that a header control is missing.' },
        { label: 'Window contact', explanation: 'Open is a physical condition, not a climate command. Check the actual window before overriding a comfort response.' },
        { label: 'Main Floor vacuum state', explanation: 'Cleaning, paused, docked, battery, and error information belong in the vacuum sheet; the room card is only the entry point.' },
        { label: 'SHIELD card versus app tile', explanation: 'The large SHIELD card opens remote controls. A branded app tile launches its app immediately and should be treated as a direct command.' },
        { label: 'Air-quality reading', explanation: 'Particulate and the derived air-quality summary can change independently of fan mode, so open the sheet when the compact subtitle needs context.' },
      ],
      safetyAndLimitations: {
        title: 'Media launches and vacuum commands have real effects',
        text: 'A SHIELD app tile can interrupt the current television activity without another confirmation, and commands inside the vacuum sheet can move equipment. Check who is using the room, clear the floor, and distinguish a detail opener from an immediate app launch before selecting it. The reused screenshots illustrate shared controls and are not Living Room route captures.',
      },
      troubleshootingChecks: [
        'If Air Quality or another header summary is off-screen, swipe the header rail horizontally and reopen the intended item once.',
        'If both Air Quality and Air Purifier appear to open the same sheet, that is expected: they are two entry points to the same purifier detail destination.',
        'If a SHIELD app does not appear, open the SHIELD remote and confirm the player and remote are available before repeating the launch.',
        'If the vacuum card is unavailable, inspect its connection and battery state rather than repeatedly selecting the muted card.',
        'If climate behavior looks wrong, compare the room range, the physical window, occupancy zones, and the whole-home thermostat mode in that order.',
      ],
      screenshotIds: ['section-rooms-context', 'status-lights-detail', 'vacuum-area-editor'],
      relatedArticleIds: ['status-lights', 'thermostat-and-contacts', 'vacuum-cleaning', 'media-appliances-vehicle', 'presence-based-lighting'],
    },
  },
  {
    id: 'room-guest-room',
    kind: 'page-guide',
    sectionId: 'rooms',
    parentId: 'browse-pages',
    title: 'Guest Room page guide',
    summary: 'A quiet-room guide to lighting, two-zone occupancy, window comfort, the vent, purifier, and guest safeguards.',
    icon: 'mdi:bed',
    status: 'current',
    aliases: ['guest bedroom controls', 'guest room purifier', 'guest room safeguards'],
    visibleLabels: ['Lights', 'Climate', 'Occupancy', 'Window', 'Air Quality', 'Vent', 'Air Purifier'],
    ownsSurfaceIds: ['route:guest-room'],
    keywords: ['guest room', 'guest stay', 'closet occupancy', 'window', 'vent', 'purifier'],
    tasks: [
      'How do I prepare the Guest Room for someone staying over?',
      'Which Guest Room sensors report occupancy?',
      'Where can I check the Guest Room purifier and vent?',
      'Why might Guest Room automation behave differently during a visit?',
    ],
    coversRoutes: ['guest-room'],
    blocks: [],
    pageGuide: {
      routePath: 'guest-room',
      complexity: 'simple',
      generatedRoomPath: 'guest-room',
      orientation: 'Guest Room keeps routine comfort information in the header and reserves its body for Climate equipment. The header opens the two-light group, room temperatures, a combined occupancy view for the sleeping area and closet-facing zone, the window contact, and purifier air quality. The Climate section then gives separate entry points to the single vent and the purifier. Treat this page as the room check, while guest-stay safeguards are configured from Guest Controls.',
      visiblePageSectionNames: ['Header Summaries', 'Climate'],
      whatYouCanDo: [
        'Open Lights to adjust the Guest Room light group or individual fixtures without changing the guest-mode setting itself.',
        'Open Occupancy to distinguish activity in the main room from the closet-facing sensor. The compact header state only says whether at least one configured zone is active.',
        'Use Climate and Window together when the room feels uncomfortable: Climate shows the sensed range, while Window reveals whether the physical contact is open.',
        'Open Vent for its current position and availability, then use Air Purifier or Air Quality to review particulate, fan mode, and purifier state.',
        'Before a visitor arrives, open the separate Guest Controls guide and enable the intended guest room so security, thermostat, lighting-reset, and automatic-cleaning safeguards can use the correct house mode.',
      ],
      whatHappensAutomatically: {
        mode: 'automatic',
        items: [
          'The two occupancy zones roll up into the header summary, while their individual states remain visible inside the occupancy sheet.',
          'If Presence-Based Lighting is enabled, room and closet-facing activity can influence automatic lighting; the configured clear delay prevents a brief sensor gap from immediately darkening the room.',
          'The window contact can participate in climate contact protection, and its state updates separately from the temperature range.',
          'When this room is marked for guests, Home Assistant can preserve thermostat participation, avoid disruptive overnight lighting resets, and pause automatic vacuuming in affected sleeping areas.',
        ],
      },
      lookHereFirst: [
        { label: 'Guest-mode setting', explanation: 'The room page does not show whether the house has been told a visitor is staying. Check Guest Controls when safeguards matter.' },
        { label: 'Two occupancy zones', explanation: 'A single Occupied summary may come from the main room or the closet-facing sensor; open the sheet to identify which one.' },
        { label: 'Window state', explanation: 'An open window can explain climate changes even when the temperature card itself looks normal.' },
        { label: 'Purifier fan mode', explanation: 'Air-quality readings and the selected fan mode answer different questions. Review both before assuming the purifier failed.' },
      ],
      safetyAndLimitations: {
        title: 'Guest comfort settings do not replace a physical room check',
        text: 'A sensor can report clear while someone is still sleeping, and guest safeguards intentionally change away assumptions. Confirm the window, vent, purifier, bedding area, and guest-room selection before relying on automatic lighting, climate, or cleaning. The route image shows the Guest Room page; the additional thermostat image demonstrates shared control behavior.',
      },
      troubleshootingChecks: [
        'If Occupancy says Clear unexpectedly, open the sheet and compare both configured zones instead of testing only the main sensor.',
        'If climate control pauses, check the Window contact and the whole-home Open Contact Sensors notice.',
        'If the purifier sheet is unavailable, verify both its air-quality sensor and purifier entities because the summary and fan controls use different sources.',
        'If guest safeguards did not apply, confirm the Guest Room is enabled in Guest Controls and review the guest-security summary before leaving.',
      ],
      screenshotIds: ['section-rooms-context', 'thermostat-options'],
      relatedArticleIds: ['guest-and-vacation', 'thermostat-and-contacts', 'presence-based-lighting', 'status-lights'],
    },
  },
  {
    id: 'room-master-bedroom',
    kind: 'page-guide',
    sectionId: 'rooms',
    parentId: 'browse-pages',
    title: 'Master Bedroom page guide',
    summary: 'Bedroom lighting and comfort plus separate SleepyPod sides, Apple TV, air equipment, and humidifier schedules.',
    icon: 'mdi:bed-king',
    status: 'current',
    aliases: ['primary bedroom', 'sleepypod room', 'bedroom humidifier', 'bedroom apple tv'],
    visibleLabels: ["Stephen's Bed", "Steph's Bed", 'Apple TV', 'Vents', 'Air Purifier', 'Humidifier'],
    ownsSurfaceIds: ['route:master-bedroom'],
    keywords: ['master bedroom', 'sleepypod', 'bed alarm', 'temperature stage', 'apple tv', 'humidifier', 'vents'],
    tasks: [
      'How do I change one side of the SleepyPod?',
      'Where do I edit a Master Bedroom wake alarm?',
      'How do I schedule the bedroom humidifier?',
      'Which Master Bedroom card opens the Apple TV remote?',
    ],
    coversRoutes: ['master-bedroom'],
    blocks: [],
    pageGuide: {
      routePath: 'master-bedroom',
      complexity: 'complex',
      generatedRoomPath: 'master-bedroom',
      orientation: 'Master Bedroom is organized around sleeping systems rather than a generic device list. Five header summaries cover lights, room climate, three occupancy zones, the street-window contact group, and purifier air quality. SleepyPod gives Stephen and Steph separate sheets, Media opens the bedroom Apple TV remote, and Climate contains the two vents, purifier, and the LV600S humidifier. Bed schedules and humidifier activities are independent systems, so use the card for the device you actually intend to schedule.',
      visiblePageSectionNames: ['Header Summaries', 'SleepyPod', 'Media', 'Climate'],
      whatYouCanDo: [
        'Open either named bed card to control only that side. The sheet provides pod power, the current target, Away Mode, sleep-schedule stages, wake alarms, active-alarm actions, and supported health or pump status.',
        'When changing a SleepyPod target during Bedtime, Asleep, or Dawn, choose whether the adjustment is for Tonight or All Nights. Outside a scheduled stage, the dial changes the current device target directly.',
        'Add, edit, enable, disable, or delete per-side wake alarms from the Alarms tab. If an alarm is actively ringing, use Snooze or Stop Alarm for the selected side.',
        'Open Apple TV for Controls and Apps. Directional commands, playback, power, bedroom audio volume, and the Plex launcher live in that sheet.',
        'Open Vents to inspect both bedroom vents, or use Air Purifier and Air Quality to compare particle readings with fan mode and purifier state.',
        'Open Humidifier for Controls, Schedules, and Info. Set power, mode, mist, target humidity, warm mist, display, or a one-shot timer; use Schedules for recurring activities rather than the device timer.',
      ],
      whatHappensAutomatically: {
        mode: 'automatic',
        items: [
          'Each SleepyPod side follows its own saved stages and alarms. The active stage determines whether a target change needs Tonight or All Nights scope, and alarm records continue without the room page open.',
          'Humidifier activities can apply saved modes and levels on their selected days, recover an active profile after Home Assistant or the device reconnects, then verify restoration of the earlier state after the final block. Vacation Mode can pause that schedule.',
          'The humidifier card prioritizes Tank Removed and Water Low warnings over its normal On, Off, Humidifying, and current-humidity summary.',
          'Bedroom occupancy, window, climate, purifier, media, and bed states stream back from Home Assistant; availability and card color change as those systems report transitions.',
        ],
      },
      lookHereFirst: [
        { label: 'Correct bed side', explanation: 'Stephen and Steph have independent targets, schedules, alarms, and active-alarm commands. Confirm the sheet title before editing.' },
        { label: 'Temperature scope prompt', explanation: 'Tonight is temporary for the current night; All Nights rewrites the recurring stage for that side.' },
        { label: 'Humidifier warning text', explanation: 'Tank Removed or Water Low blocks normal output controls and should be resolved at the device before raising mist.' },
        { label: 'Street-window contact', explanation: 'The header represents the configured bedroom window group. Open it when climate behavior changes unexpectedly.' },
        { label: 'Apple TV state', explanation: 'The remote sheet is useful only when the player and supporting remote are available; app launch and audio are separate commands.' },
      ],
      safetyAndLimitations: {
        title: 'Bed and humidity schedules can affect an entire night',
        text: 'Verify the person, side, stage scope, enabled days, and alarm time before saving. Confirm the humidifier tank is seated, avoid sustained targets above the recommended comfort range, and remember that a one-shot timer is not a recurring activity. The route image shows the bedroom Media section; the additional thermostat and humidifier images explain their shared workflows.',
      },
      troubleshootingChecks: [
        'If a bed card is unavailable, check that side’s control source and schedule data before changing the other side as a workaround.',
        'If a target change did not persist, confirm whether Tonight or All Nights was selected and whether the active schedule phase changed during the request.',
        'If an alarm is missing, open the correct side, inspect the expected day, and verify that the alarm editor was saved rather than only toggled.',
        'If the humidifier will not respond, resolve Tank Removed or Water Low, then check power, mode, Vacation Mode, and schedule enablement.',
        'If Apple TV controls are muted, confirm player, remote, and bedroom audio availability before repeating power or app commands.',
      ],
      screenshotIds: ['humidifier-schedule', 'thermostat-options'],
      relatedArticleIds: ['wake-alarms', 'humidifier-schedule', 'schedule-systems', 'thermostat-and-contacts', 'media-appliances-vehicle'],
    },
  },
  {
    id: 'room-gym',
    kind: 'page-guide',
    sectionId: 'rooms',
    parentId: 'browse-pages',
    title: 'Gym page guide',
    summary: 'A compact workout-room page for one light, temperature, occupancy, the window, and a single vent.',
    icon: 'mdi:dumbbell',
    status: 'current',
    aliases: ['workout room', 'gym vent', 'gym window'],
    visibleLabels: ['Light', 'Climate', 'Occupancy', 'Window', 'Vent'],
    ownsSurfaceIds: ['route:gym'],
    keywords: ['gym', 'workout', 'light', 'presence', 'window', 'vent'],
    tasks: [
      'How do I adjust the Gym light?',
      'Where can I see whether the Gym window is open?',
      'How do I inspect the Gym vent?',
    ],
    coversRoutes: ['gym'],
    blocks: [],
    pageGuide: {
      routePath: 'gym',
      complexity: 'simple',
      generatedRoomPath: 'gym',
      orientation: 'Gym is intentionally small: four header summaries and one body card cover the entire room. The header opens the single light, the Gym climate sensor range, the one presence sensor, and the window contact. The Climate body section contains only the room vent. This makes the page useful as a fast pre-workout check rather than a general equipment dashboard.',
      visiblePageSectionNames: ['Header Summaries', 'Climate'],
      whatYouCanDo: [
        'Open Light to turn the Gym fixture on or off and use any supported detail controls without changing the room’s presence-lighting policy.',
        'Open Climate to read the Gym temperature source and its relationship to whole-home comfort decisions.',
        'Open Occupancy to confirm the single configured presence sensor instead of interpreting the compact Occupied or Clear subtitle as a multi-zone count.',
        'Open Window before changing comfort settings when the room is unusually warm or cold; the contact sheet reports the physical opening separately from temperature.',
        'Open Vent to inspect its current state and availability. The vent card is a detail opener, not a direct position toggle on the room page.',
      ],
      whatHappensAutomatically: {
        mode: 'automatic',
        items: [
          'When Gym Presence-Based Lighting is enabled, the single presence sensor can start the lighting response and the configured clear timing can later return the room to its automatic state.',
          'The Gym window may participate in open-contact climate protection, so comfort behavior can pause or change while the contact remains open.',
          'Header subtitles and the vent card follow live Home Assistant state; unavailable values mute the affected item rather than inventing a fallback reading.',
        ],
      },
      lookHereFirst: [
        { label: 'Single occupancy sensor', explanation: 'There is no second zone to inspect. If the state is wrong, focus troubleshooting on the Gym presence sensor itself.' },
        { label: 'Window before thermostat', explanation: 'An open window is a likely explanation for unusual temperature or paused climate behavior.' },
        { label: 'Vent availability', explanation: 'The vent sheet can show the configured vent even when it cannot currently report a usable state.' },
        { label: 'Light automation state', explanation: 'Manual light control and the separate Presence-Based Lighting mode can produce different next-step behavior after the room clears.' },
      ],
      safetyAndLimitations: {
        title: 'Do not rely on one sensor while someone is using equipment',
        text: 'The occupancy summary comes from one presence sensor and can be obstructed by position or equipment. Confirm the room physically before allowing an automatic light-off, and avoid changing vent or climate behavior solely to compensate for an open window. The thermostat screenshot is a shared control example, not a Gym route image.',
      },
      troubleshootingChecks: [
        'If the light changes again after a manual action, review the Gym Presence-Based Lighting state and clear delay.',
        'If Occupancy remains Clear during use, inspect sensor placement and availability rather than looking for another configured zone.',
        'If the climate range appears stale, compare the Gym sensor with the whole-home Climate page and check the Window contact.',
        'If the Vent card is muted, verify the vent entity is available before reopening its sheet.',
      ],
      screenshotIds: ['thermostat-options'],
      relatedArticleIds: ['status-lights', 'presence-based-lighting', 'thermostat-and-contacts', 'device-families'],
    },
  },
  {
    id: 'room-hallway',
    kind: 'page-guide',
    sectionId: 'rooms',
    parentId: 'browse-pages',
    title: 'Hallway page guide',
    summary: 'Header-only Hallway light, climate, and three-zone occupancy controls with an intentionally empty body.',
    icon: 'mdi:door-open',
    status: 'current',
    aliases: ['upstairs hallway', 'hallway empty page', 'hallway presence'],
    visibleLabels: ['Lights', 'Climate', 'Occupancy', 'Nothing Here Yet!'],
    ownsSurfaceIds: ['route:hallway'],
    keywords: ['hallway', 'empty body', 'entryway sensor', 'bathroom sensor', 'office sensor'],
    tasks: [
      'Why does the Hallway page say Nothing Here Yet?',
      'Which sensors are included in Hallway Occupancy?',
      'How do I open the Hallway lights?',
    ],
    coversRoutes: ['hallway'],
    blocks: [],
    pageGuide: {
      routePath: 'hallway',
      complexity: 'simple',
      generatedRoomPath: 'hallway',
      orientation: 'Hallway is a header-driven route. Lights, Climate, and Occupancy remain fully usable in the sticky header, while the scrolled body deliberately shows “Nothing Here Yet!” because no additional Hallway source sections are configured. The empty message is not a loading failure. Open the header summaries for the four-light group, the three temperature zones, or the three occupancy zones.',
      visiblePageSectionNames: ['Header Summaries', 'Nothing Here Yet!'],
      whatYouCanDo: [
        'Open Lights to work with the Entry, Gym, Guest Room, and Office hallway fixtures that belong to the Hallway light group.',
        'Open Climate to compare the configured Hallway temperature zones rather than expecting a thermostat card in the empty body.',
        'Open Occupancy to inspect Entryway, Bathroom, and Office-side presence zones separately when the rollup says Occupied.',
        'Swipe the header horizontally on a phone if Occupancy is not immediately visible; all three summaries remain in the header even though the body has no cards.',
        'Use the intentional empty state as confirmation that there are currently no extra Hallway devices such as a vent, purifier, vacuum, or appliance section.',
      ],
      whatHappensAutomatically: {
        mode: 'automatic',
        items: [
          'The header states continue updating from Home Assistant while the empty body stays unchanged until the room configuration gains a real source section.',
          'Hallway Presence-Based Lighting can use the configured occupancy zones and clear timing independently of whether any body cards exist.',
          'Individual fixture and sensor changes roll up into the group subtitles, so one active zone can make the whole Occupancy summary report Occupied.',
        ],
      },
      lookHereFirst: [
        { label: 'Nothing Here Yet!', explanation: 'This is the expected body for the current route configuration, not evidence that the header failed to load.' },
        { label: 'Three occupancy zones', explanation: 'Entryway, Bathroom, and Office-side activity are combined in the summary; open it to find the active zone.' },
        { label: 'Four-light group', explanation: 'The Hallway Lights sheet includes fixtures near several neighboring rooms, so its scope is wider than one ceiling point.' },
        { label: 'Sticky header rail', explanation: 'The useful controls remain above the empty state and may require a sideways swipe on narrow screens.' },
      ],
      safetyAndLimitations: {
        title: 'An empty body does not mean the hallway is unmonitored',
        text: 'Lighting, temperature, and occupancy still report and may participate in automation. Do not disable or override the group merely because no body section is present; first open the header sheet and identify the exact fixture or zone. The reused light-detail image demonstrates the shared sheet and is not a Hallway screenshot.',
      },
      troubleshootingChecks: [
        'If no header cards appear, reload the route and verify Home Assistant state rather than waiting for body cards to populate.',
        'If Occupancy seems too broad, open the sheet and check all three named zones.',
        'If a Hallway light behaves like a neighboring room fixture, compare the four configured group members before reporting a mapping problem.',
        'If someone expects another device in the body, confirm that it has actually been added to the Hallway source configuration.',
      ],
      screenshotIds: ['status-lights-detail'],
      relatedArticleIds: ['status-lights', 'presence-based-lighting', 'device-families', 'states-and-feedback'],
    },
  },
  {
    id: 'room-office',
    kind: 'page-guide',
    sectionId: 'rooms',
    parentId: 'browse-pages',
    title: 'Office page guide',
    summary: 'Office comfort and air controls plus two computers whose power cards choose On or Off commands from live state.',
    icon: 'mdi:desktop-tower',
    status: 'current',
    aliases: ['office pc power', 'stephen pc', 'steph pc', 'office purifier'],
    visibleLabels: ['Light', 'Climate', 'Occupancy', 'Windows', 'Air Quality', 'Vent', 'Air Purifier', "Stephen's PC", "Steph's PC"],
    ownsSurfaceIds: ['route:office'],
    keywords: ['office', 'computers', 'pc power', 'windows', 'closet occupancy', 'vent', 'purifier'],
    tasks: [
      'How does the Office PC power card decide what to do?',
      'Where do I check both Office windows?',
      'How can I inspect Office air quality and purifier mode?',
      'Which Office occupancy zones are combined in the header?',
    ],
    coversRoutes: ['office'],
    blocks: [],
    pageGuide: {
      routePath: 'office',
      complexity: 'complex',
      generatedRoomPath: 'office',
      orientation: 'Office mixes environmental detail with command-oriented computer cards. The header opens one light, the room climate group, a two-zone occupancy sheet, a two-window contact sheet, and purifier air quality. Climate contains the single vent and purifier entry. Office PCs contains Stephen’s PC and Steph’s PC; each card reads its own power helper before choosing a configured startup or shutdown button, so it is not a blind toggle.',
      visiblePageSectionNames: ['Header Summaries', 'Climate', 'Office PCs'],
      whatYouCanDo: [
        'Open Light for the Office fixture, then use Occupancy to distinguish the main Office sensor from the closet sensor when the rollup is active.',
        'Open Windows to inspect both configured contacts. The aggregate card can say an opening exists without identifying which window until the sheet is opened.',
        'Use Climate for room readings, Vent for the Office vent detail, and Air Quality or Air Purifier for particulate, fan-mode, and purifier status.',
        'Select Stephen’s PC when you intend to change that computer’s power. If its power helper reports On, the card presses the configured Off command; every other reported state selects the configured On command.',
        'Use Steph’s PC independently. It follows the same state branch but has separate helpers and command buttons, so one computer’s state never chooses the other computer’s action.',
        'Read the smaller PC power-state subtitle before acting. It supplies additional machine feedback while the main helper determines which command branch will be sent.',
      ],
      whatHappensAutomatically: {
        mode: 'automatic',
        items: [
          'Main-room and closet occupancy roll into one header state, and Presence-Based Lighting can use those zones when the Office room policy is enabled.',
          'The two window contacts can participate in climate protection; opening either contact may alter automatic comfort behavior while the combined Windows summary remains active.',
          'PC card appearance and subtitles update as Home Assistant receives helper and machine-state changes. The card resolves its On-versus-Off branch at selection time rather than when the page first loaded.',
          'Air-quality and purifier summaries update from separate sources, so a changed particle reading does not necessarily mean the selected purifier mode also changed.',
        ],
      },
      lookHereFirst: [
        { label: 'PC helper state', explanation: 'On means the next card selection requests shutdown. Off, unknown-to-the-helper, or another non-On value follows the startup branch.' },
        { label: 'Machine-state subtitle', explanation: 'This can provide richer progress information, but it does not replace the helper used to choose the command.' },
        { label: 'Two-window summary', explanation: 'Open the Windows sheet before assuming both contacts have the same state.' },
        { label: 'Closet occupancy', explanation: 'Closet activity can make the room summary Occupied even when the desk area appears clear.' },
        { label: 'Purifier sources', explanation: 'Particle level, fan mode, and purifier power are related but independently reported values.' },
      ],
      safetyAndLimitations: {
        title: 'PC cards can start or shut down equipment immediately',
        text: 'There is no detail sheet or confirmation between selecting a PC card and pressing its state-selected command. Save work, verify the person and machine, read the current helper and subtitle, then select once and wait for state confirmation. A stale helper can choose the wrong branch, so use the physical machine state when the two indicators disagree.',
      },
      troubleshootingChecks: [
        'If a PC received the opposite command, compare its power helper with the machine-state subtitle and correct the Home Assistant source before retrying.',
        'If a PC remains in a transitional state, wait for startup or shutdown to complete instead of repeatedly selecting the card.',
        'If Windows reports open, inspect both contacts individually and close the physical opening before overriding climate safeguards.',
        'If Air Purifier opens but controls are incomplete, verify the air sensor, fan-mode selector, and purifier fan are all available.',
        'If Office lights change unexpectedly after occupancy clears, review the main and closet sensors plus the room’s Presence-Based Lighting mode.',
      ],
      screenshotIds: ['section-rooms-context'],
      relatedArticleIds: ['media-appliances-vehicle', 'thermostat-and-contacts', 'presence-based-lighting', 'device-families', 'states-and-feedback'],
    },
  },
  {
    id: 'room-kitchen',
    kind: 'page-guide',
    sectionId: 'rooms',
    parentId: 'browse-pages',
    title: 'Kitchen page guide',
    summary: 'Kitchen light and comfort summaries, grocery destinations, a state-rich dishwasher sheet, and the room vent.',
    icon: 'mdi:stove',
    status: 'current',
    aliases: ['kitchen dishwasher', 'kitchen groceries', 'kitchen food scan'],
    visibleLabels: ['Lights', 'Climate', 'Occupancy', 'Door', 'Groceries', 'Grocery List', 'Food', 'Dishwasher', 'Vent'],
    ownsSurfaceIds: ['route:kitchen'],
    keywords: ['kitchen', 'dishwasher', 'grocery list', 'food inventory', 'scan item', 'door', 'vent'],
    tasks: [
      'How do I start or stop the Kitchen dishwasher?',
      'Where does the Kitchen Grocery List card go?',
      'How do I reach the food scanning workflow from Kitchen?',
      'Why does the Dishwasher card show progress sometimes?',
    ],
    coversRoutes: ['kitchen'],
    blocks: [],
    pageGuide: {
      routePath: 'kitchen',
      complexity: 'complex',
      generatedRoomPath: 'kitchen',
      orientation: 'Kitchen adds a runtime Groceries section before the two configured room sections. Its header opens Lights, Climate, the single Kitchen occupancy sensor, and the exterior-door contact. Groceries contains navigation cards for Grocery List and Food; those cards leave the room instead of changing an entity. Appliances contains the Dishwasher detail opener, whose subtitle and progress bar adapt to the current operation. Climate ends the page with the single vent.',
      visiblePageSectionNames: ['Header Summaries', 'Groceries', 'Appliances', 'Climate'],
      whatYouCanDo: [
        'Open Lights, Climate, Occupancy, or Door from the header to inspect the Kitchen group or sensor behind each compact summary.',
        'Choose Grocery List to navigate to the Home shopping list. The tile subtitle is a live item count, but selecting it does not complete or add an item by itself.',
        'Choose Food to open the Food & Recipes hub. From that destination, use its floating scan action to identify an item, select a storage location, review expiration details, and save through the EverShelf integration.',
        'Open Dishwasher to choose a program, start a cycle through the Home Assistant helper, resume or stop when those actions are valid, and adjust supported Power, Half Load, Zeolite Dry, or Hygiene options.',
        'Use the Dishwasher status area to check operation, clean-unopened state, progress, active program, door, connectivity, remote permissions, finish time, rinse aid, and salt before changing a cycle.',
        'Open Vent for the Kitchen vent detail. The vent tile opens a sheet and does not directly toggle the cover from the page body.',
      ],
      whatHappensAutomatically: {
        mode: 'automatic',
        items: [
          'Grocery List count and Food inventory summary are calculated from current Home Assistant and EverShelf-backed state, so their subtitles can change without returning to Kitchen.',
          'While the dishwasher operation is Running or Paused, the room card switches to program progress and displays a fill bar; outside those states it emphasizes selected program and operation summary instead.',
          'Dishwasher action choices change with operation state: Start, Resume, Stop, or a temporary Stopping status appears only when appropriate, while the requested state waits for Home Assistant confirmation.',
          'The Kitchen door contact can influence climate safeguards, and the presence sensor can participate in automatic lighting when that room policy is enabled.',
        ],
      },
      lookHereFirst: [
        { label: 'Navigation versus control', explanation: 'Grocery List and Food open other pages. Dishwasher and Vent open sheets. None of these four body cards is a direct one-tap toggle.' },
        { label: 'Dishwasher operation', explanation: 'Running, Paused, Aborting, Finished, and other states determine progress display and which cycle action is offered.' },
        { label: 'Remote permissions', explanation: 'Connectivity alone does not prove remote start is permitted. Check both Remote Control and Remote Start inside the sheet.' },
        { label: 'Clean Unopened', explanation: 'This status can preserve the useful “Clean” meaning after the operation state has moved on, until the door is opened.' },
        { label: 'Kitchen door', explanation: 'An open contact is a physical and climate-relevant condition; verify it before changing comfort settings.' },
      ],
      safetyAndLimitations: {
        title: 'Check the appliance and review step before sending commands',
        text: 'Confirm the dishwasher door, selected program, remote-start permission, contents, and option compatibility before Start. Stop can interrupt a cycle. Food scanning is completed on the Food page and requires a final review; the Kitchen Food card itself is only navigation. The scan screenshot shows the shared review step, not this route.',
      },
      troubleshootingChecks: [
        'If the Groceries section is missing, verify the runtime route is Kitchen; it is injected by SourceRoomPage and is not part of the static room sourceSections array.',
        'If Dishwasher shows Unavailable, check both selected-program and operation sources because the card remains usable when at least one is reporting.',
        'If Start is disabled or ineffective, review connectivity, remote-control permission, remote-start permission, door state, and the selected program.',
        'If the progress bar disappears, confirm whether the operation is still Running or Paused; other states intentionally use a plain summary.',
        'If food scanning is not visible, follow Food from Kitchen and use the destination page’s scan action rather than looking for a scanner inside the room page.',
      ],
      screenshotIds: ['food-scan-review'],
      relatedArticleIds: ['grocery-list-page-guide', 'food-scanning', 'food-inventory', 'media-appliances-vehicle', 'thermostat-and-contacts'],
    },
  },
  {
    id: 'room-dining-room',
    kind: 'page-guide',
    sectionId: 'rooms',
    parentId: 'browse-pages',
    title: 'Dining Room page guide',
    summary: 'A focused dining-area page for the dimmer, room temperature, presence, exterior door, and one vent.',
    icon: 'mdi:silverware-fork-knife',
    status: 'current',
    aliases: ['dining light', 'dining door', 'dining vent'],
    visibleLabels: ['Light', 'Climate', 'Occupancy', 'Door', 'Vent'],
    ownsSurfaceIds: ['route:dining-room'],
    keywords: ['dining room', 'dimmer', 'door contact', 'presence', 'vent'],
    tasks: [
      'How do I dim the Dining Room light?',
      'Where can I check the Dining Room door?',
      'How do I inspect Dining Room temperature and occupancy?',
    ],
    coversRoutes: ['dining-room'],
    blocks: [],
    pageGuide: {
      routePath: 'dining-room',
      complexity: 'simple',
      generatedRoomPath: 'dining-room',
      orientation: 'Dining Room is a concise comfort page built around one dimmer, one temperature zone, one presence sensor, one door contact, and one vent. Four summaries remain in the header, and the Climate section contains the vent card. There are no appliance or media sections here, so the page can be read quickly before a meal or when investigating a comfort change near the exterior door.',
      visiblePageSectionNames: ['Header Summaries', 'Climate'],
      whatYouCanDo: [
        'Open Light to turn the Dining Room dimmer on or off and adjust supported brightness from the shared light sheet.',
        'Open Climate to read the single Dining Room temperature source and understand how it contributes to room comfort reporting.',
        'Open Occupancy to verify the one configured presence sensor; the summary is not combining hidden dining-area zones.',
        'Open Door to see the contact state before deciding that a climate response or draft is caused by the thermostat.',
        'Open Vent to inspect the Dining Room vent and its availability. Its room card does not move the vent immediately.',
      ],
      whatHappensAutomatically: {
        mode: 'automatic',
        items: [
          'If Dining Room Presence-Based Lighting is enabled, the presence sensor can participate in automatic light-on and clear behavior while the dimmer remains manually controllable.',
          'The exterior-door contact can feed the open-contact climate safeguard, allowing a physical opening to pause or change automatic heating and cooling decisions.',
          'The light, temperature, presence, door, and vent summaries refresh independently as their devices report new state.',
        ],
      },
      lookHereFirst: [
        { label: 'Door contact', explanation: 'This is often the most important clue when the room temperature moves quickly or climate behavior pauses.' },
        { label: 'Single presence source', explanation: 'Occupied and Clear map to one configured sensor, which simplifies diagnosis but provides no second-zone confirmation.' },
        { label: 'Dimmer detail', explanation: 'Open the Light sheet for brightness; the header card is an opener rather than an immediate toggle.' },
        { label: 'Vent card', explanation: 'The detail sheet reports the vent separately from the room temperature sensor.' },
      ],
      safetyAndLimitations: {
        title: 'Separate drafts, occupancy, and lighting intent',
        text: 'Do not compensate for an open exterior door by forcing a climate or vent change, and confirm the dining area before allowing presence lighting to clear the dimmer during use. The thermostat image is a shared comfort example and should not be read as a current Dining Room state.',
      },
      troubleshootingChecks: [
        'If the dimmer changes after a manual adjustment, review the Dining Room Presence-Based Lighting mode.',
        'If the room feels wrong despite a normal Climate value, inspect the Door contact and physical vent.',
        'If Occupancy remains active, check the single presence sensor for motion, placement, and availability.',
        'If Vent opens an unavailable sheet, verify the vent source rather than repeatedly selecting the room card.',
      ],
      screenshotIds: ['thermostat-options'],
      relatedArticleIds: ['status-lights', 'thermostat-and-contacts', 'presence-based-lighting', 'device-families'],
    },
  },
  {
    id: 'room-back-deck',
    kind: 'page-guide',
    sectionId: 'rooms',
    parentId: 'browse-pages',
    title: 'Back Deck page guide',
    summary: 'Outdoor lights and doors, a camera-derived occupancy status, and grill detail that opens only while active.',
    icon: 'mdi:grill',
    status: 'current',
    aliases: ['deck controls', 'bear grills', 'upper deck occupancy'],
    visibleLabels: ['Lights', 'Occupancy', 'Doors', 'Bear Grills'],
    ownsSurfaceIds: ['route:back-deck'],
    keywords: ['back deck', 'outdoor lights', 'doors', 'camera occupancy', 'grill', 'pellets', 'probe'],
    tasks: [
      'Why can I not open Bear Grills while it is off?',
      'Is Back Deck Occupancy a control or only a status?',
      'How do I check both Back Deck doors?',
      'Where are the deck light controls?',
    ],
    coversRoutes: ['back-deck'],
    blocks: [],
    pageGuide: {
      routePath: 'back-deck',
      complexity: 'simple',
      generatedRoomPath: 'back-deck',
      orientation: 'Back Deck separates outdoor access from active cooking. The header opens the deck light group and a two-door contact sheet, while Occupancy only reports the upper-deck camera person state and has no destination. The Grill section contains Bear Grills. That card opens probe, pellet, Keep Warm, and Super Smoke detail only when the grill reports an active state; Off, Unknown, or Unavailable deliberately disables it.',
      visiblePageSectionNames: ['Header Summaries', 'Grill'],
      whatYouCanDo: [
        'Open Lights to control the configured deck fixtures from a detail sheet rather than toggling the entire outdoor area accidentally.',
        'Open Doors to identify which of the two configured deck contacts is open. The header rollup can show activity without naming the door until you enter the sheet.',
        'Read Occupancy as a status-only camera-derived signal. Selecting that card does not open a camera, occupancy sheet, or physical control.',
        'While Bear Grills is active, open its detail sheet to read grill state, Probe 1, and Pellet Level.',
        'Use Keep Warm or Super Smoke inside the active grill sheet when their switch sources are available. Those two internal cards toggle immediately.',
      ],
      whatHappensAutomatically: {
        mode: 'automatic',
        items: [
          'Camera person detection updates the Occupancy subtitle, but this room page does not expose the camera stream or use that status card as a command.',
          'Bear Grills changes from an active detail opener to a muted Off card when the grill state becomes Off, Unknown, or Unavailable.',
          'Door and light group summaries follow their physical devices; an active grill sheet also refreshes probe, pellet, and switch states as they report.',
        ],
      },
      lookHereFirst: [
        { label: 'Grill card enabled state', explanation: 'A muted Off card is intentional. Start and inspect the grill physically before expecting the detail sheet to open.' },
        { label: 'Camera-derived Occupancy', explanation: 'This only answers whether a person was detected; it does not provide a live image or guarantee the deck is clear.' },
        { label: 'Two-door rollup', explanation: 'Open Doors to locate the active contact rather than treating the combined state as one physical door.' },
        { label: 'Outdoor light scope', explanation: 'The shared light sheet contains the configured deck fixtures; its reused screenshot is illustrative, not route-specific.' },
      ],
      safetyAndLimitations: {
        title: 'Never treat the dashboard as the grill safety check',
        text: 'Confirm the grill, fuel, probe placement, surrounding deck, doors, children, pets, and weather in person. Occupancy can miss people, and an Off grill card intentionally provides no remote detail. Keep Warm and Super Smoke are immediate internal toggles once the sheet is open.',
      },
      troubleshootingChecks: [
        'If Bear Grills will not open, verify that its state is active; Off, Unknown, and Unavailable are configured disabled states.',
        'If Occupancy seems wrong, check the upper-deck camera detection source rather than tapping the status-only card.',
        'If Doors reports open, inspect both contacts in the sheet and then check the physical openings.',
        'If a grill metric is unavailable after the sheet opens, verify that specific probe, pellet, or switch source instead of restarting every grill control.',
      ],
      screenshotIds: ['status-lights-detail'],
      relatedArticleIds: ['media-appliances-vehicle', 'status-lights', 'thermostat-and-contacts', 'device-families'],
    },
  },
  {
    id: 'room-music-room',
    kind: 'page-guide',
    sectionId: 'rooms',
    parentId: 'browse-pages',
    title: 'Music Room page guide',
    summary: 'Multi-zone lights and occupancy, door and air monitoring, climate equipment, and the dedicated room vacuum.',
    icon: 'mdi:music',
    status: 'current',
    aliases: ['music room vacuum', 'music room purifier', 'downstairs music room'],
    visibleLabels: ['Lights', 'Climate', 'Occupancy', 'Door', 'Air Quality', 'Vents', 'Air Purifier', 'Music Room'],
    ownsSurfaceIds: ['route:music-room'],
    keywords: ['music room', 'lights', 'north wall', 'kitchenette', 'door presence', 'purifier', 'vacuum'],
    tasks: [
      'How do I clean the Music Room with its vacuum?',
      'Which Music Room occupancy zones are active?',
      'Where do I check Music Room air quality?',
      'How do guest settings affect Music Room cleaning?',
    ],
    coversRoutes: ['music-room'],
    blocks: [],
    pageGuide: {
      routePath: 'music-room',
      complexity: 'simple',
      generatedRoomPath: 'music-room',
      orientation: 'Music Room has a dense header for a ten-light group, room climate, three occupancy zones, the door contact, and air quality. The body divides comfort equipment from cleaning: Climate contains the single vent and purifier, while Devices opens the dedicated Music Room robot vacuum. This route is useful both for normal studio setup and for checking guest or project conditions before an automatic clean.',
      visiblePageSectionNames: ['Header Summaries', 'Climate', 'Devices'],
      whatYouCanDo: [
        'Open Lights to reach the Music Room fixture group and individual light controls without making the entire header card a direct toggle.',
        'Open Occupancy to distinguish North Wall, Kitchenette, and Door sensing zones. One active zone is enough for the compact summary to report Occupied.',
        'Use Climate and Door to compare room readings with the physical contact, then inspect Vent for the dedicated cover state.',
        'Open Air Quality or Air Purifier to review particles, the derived quality summary, selected fan mode, and purifier fan state.',
        'Select the Music Room device card to open its robot-vacuum sheet, review state and battery, choose supported cleaning controls, and enter the shared area workflow when appropriate.',
        'Before automatic or manual cleaning, use Guest Controls and the vacuum auto-clean exclusions when a visitor, instrument setup, cables, or a floor project should keep the robot out.',
      ],
      whatHappensAutomatically: {
        mode: 'automatic',
        items: [
          'Three presence zones and the configured clear behavior can drive Music Room Presence-Based Lighting when enabled, while the ten-light group reports its aggregate state.',
          'The room’s automatic-clean automation and guest exclusions are owned by Home Assistant; the vacuum card reflects the resulting cleaning, dock, battery, and error state.',
          'An open Music Room door can participate in climate contact handling, and purifier readings continue updating independently of vent position.',
          'Unavailable devices mute only their affected cards, so a purifier outage does not erase the vacuum or light controls.',
        ],
      },
      lookHereFirst: [
        { label: 'Floor and cables', explanation: 'Music equipment, stands, and leads can make an otherwise valid vacuum command unsafe. Inspect the route physically first.' },
        { label: 'Three occupancy zones', explanation: 'Open the sheet to identify whether North Wall, Kitchenette, or Door is holding the room active.' },
        { label: 'Guest-room selection', explanation: 'Music Room can be marked for guests, which changes automatic-cleaning and other house safeguards outside this page.' },
        { label: 'Vacuum mode and battery', explanation: 'The body card is only a summary; state-aware commands and area setup live inside the vacuum sheet.' },
        { label: 'Air Quality versus Vent', explanation: 'Particles, purifier mode, and vent position are separate signals and should be diagnosed separately.' },
      ],
      safetyAndLimitations: {
        title: 'Protect instruments and clear the cleaning path',
        text: 'Do not start the robot until cables, stands, pedals, rugs, and fragile equipment are secure. Guest exclusions affect automatic cleaning, while a manual selected-room run can still be requested. The reused vacuum image explains the shared area editor and does not show a Music Room map capture.',
      },
      troubleshootingChecks: [
        'If the vacuum is unavailable, check its battery, connection, and dock state before selecting another cleaning action.',
        'If an automatic clean skipped the room, review guest selection and the Music Room auto-clean exclusion instead of assuming route failure.',
        'If Occupancy remains active, inspect all three zones and any instrument movement near them.',
        'If air readings look stale, verify particle and purifier sources independently, then compare the Door contact and Vent.',
        'If lights change after a session, review the room clear delay and current Presence-Based Lighting mode.',
      ],
      screenshotIds: ['vacuum-area-editor'],
      relatedArticleIds: ['vacuum-cleaning', 'vacuum-area-cleaning', 'guest-and-vacation', 'presence-based-lighting', 'thermostat-and-contacts'],
    },
  },
  {
    id: 'room-theater-room',
    kind: 'page-guide',
    sectionId: 'rooms',
    parentId: 'browse-pages',
    title: 'Theater Room page guide',
    summary: 'Theater comfort, SHIELD remote tabs, direct source and app commands, state-aware PC power, and vacuum controls.',
    icon: 'mdi:movie-open',
    status: 'current',
    aliases: ['home theater', 'theater shield', 'projector remote', 'theater pc'],
    visibleLabels: ['Lights', 'Climate', 'Occupancy', 'Door', 'Air Quality', 'Remote', 'Theater Remote', 'Quick App Launch', 'Theater Room PCs', 'Devices'],
    ownsSurfaceIds: ['route:theater-room'],
    keywords: ['theater room', 'projector', 'shield', 'yamaha', 'nintendo switch', 'apps', 'pc power', 'vacuum'],
    tasks: [
      'How do I open the Theater Room remote?',
      'Which Theater media tiles act immediately?',
      'How does the Theater Room PC power command branch?',
      'Where can I start the Theater Room vacuum?',
    ],
    coversRoutes: ['theater-room'],
    blocks: [],
    pageGuide: {
      routePath: 'theater-room',
      complexity: 'complex',
      generatedRoomPath: 'theater-room',
      orientation: 'Theater Room is the most command-heavy room route. Its header covers lights, temperature, occupancy, door, and purifier air quality. Climate contains two vents and the purifier. Remote leads with a full-width Theater Remote button that opens the SHIELD remote sheet with Controls, Apps, and Devices tabs, and keeps Nintendo Switch and Theater SHIELD together in their own responsive grid directly underneath it, where both execute immediately. Quick App Launch keeps the six branded app tiles in their own responsive grid below that group. Theater Room PCs adds a state-dependent computer command, and Devices opens the dedicated vacuum.',
      visiblePageSectionNames: ['Header Summaries', 'Climate', 'Remote', 'Quick App Launch', 'Theater Room PCs', 'Devices'],
      whatYouCanDo: [
        'Open Theater Remote, the full-width button at the top of the Remote group, for directional navigation, playback, keyboard entry, Yamaha volume, app choices, and a Devices tab for Projector, Yamaha AVR, SHIELD, and Theater Room PC.',
        'Select Nintendo Switch to run the configured game-source command immediately, or Theater SHIELD to run the configured movie-source command. Both share the smaller grid directly below the full-width Theater Remote button, and neither opens a preview or confirmation sheet.',
        'Choose Plex, YouTube, Netflix, Prime Video, Paramount+, or Disney+ from Quick App Launch to launch that app and request projector startup through the media script.',
        'Use Theater Room PC only after reading its power helper and subtitle. An On helper chooses the Off command; every other state chooses the On command.',
        'Open Lights, Climate, Occupancy, Door, Air Quality, Vents, or Air Purifier for their focused sheets. Header and climate cards are detail openers, unlike the direct media and PC commands.',
        'Open the Theater Room vacuum sheet to review state, battery, cleaning mode, room selection, and supported area-cleaning setup.',
      ],
      whatHappensAutomatically: {
        mode: 'automatic',
        items: [
          'Media player, projector, receiver, SHIELD, PC helper, vacuum, environmental, and card-active states refresh from Home Assistant while equipment starts, switches inputs, or shuts down.',
          'Theater app-launch commands include the configured projector-start request, so choosing an app can affect more than the SHIELD application alone.',
          'The PC command branch is resolved from the latest helper state at the moment of selection; it is not a static power toggle decided when the page rendered.',
          'The Theater Room vacuum has its own automatic-clean behavior and can be excluded for guests or floor conditions while manual cleaning remains a separate choice.',
          'Presence-Based Lighting and the door-contact climate safeguard continue according to their Home Assistant settings without the remote sheet open.',
        ],
      },
      lookHereFirst: [
        { label: 'Remote opener versus direct tile', explanation: 'The full-width Theater Remote button opens tabs. The Theater SHIELD and Nintendo Switch buttons below it, every Quick App Launch tile, and the PC card send commands immediately.' },
        { label: 'Devices tab', explanation: 'Projector, receiver, SHIELD, and PC controls inside the remote sheet are separate from the similarly named cards in the Remote group and the Theater Room PCs group.' },
        { label: 'Current source and power', explanation: 'Wait for projector, receiver, and SHIELD state to settle before sending another source or power request.' },
        { label: 'PC helper', explanation: 'On selects shutdown; any other helper state selects startup. The richer subtitle is context, not the branch selector.' },
        { label: 'Vacuum floor readiness', explanation: 'Seating, cables, blankets, and guest use can make an available robot unsafe to run.' },
      ],
      safetyAndLimitations: {
        title: 'Several Theater tiles execute multi-device commands immediately',
        text: 'A source or app selection may power the projector, switch media activity, or interrupt viewers without confirmation. PC power and vacuum commands also have physical consequences. Read the active states, check the room, select once, and wait for equipment transitions. The shared vacuum screenshot is not a Theater Room route or map capture.',
      },
      troubleshootingChecks: [
        'If the remote opens but Controls are muted, verify SHIELD and remote availability before using a direct source tile as a workaround.',
        'If an app launches without the expected picture, inspect projector, receiver input, and SHIELD state before relaunching it.',
        'If the PC gets the wrong power request, compare its helper with the machine-state subtitle and fix the stale source.',
        'If media equipment remains in a transition, wait for confirmed state instead of stacking source, power, or app commands.',
        'If the vacuum is skipped or unavailable, review guest exclusions, room readiness, battery, connection, and dock status.',
      ],
      screenshotIds: ['vacuum-area-editor'],
      relatedArticleIds: ['media-appliances-vehicle', 'vacuum-cleaning', 'vacuum-area-cleaning', 'thermostat-and-contacts', 'states-and-feedback'],
    },
  },
  {
    id: 'room-downstairs-hallway',
    kind: 'page-guide',
    sectionId: 'rooms',
    parentId: 'browse-pages',
    title: 'Downstairs Hallway page guide',
    summary: 'Four distinct header sheets for light, climate, occupancy, and the garage-adjacent door, above an empty body.',
    icon: 'mdi:stairs',
    status: 'current',
    aliases: ['lower hallway', 'downstairs hallway door', 'hallway hash fix'],
    visibleLabels: ['Light', 'Climate', 'Occupancy', 'Door', 'Nothing Here Yet!'],
    ownsSurfaceIds: ['route:downstairs-hallway'],
    keywords: ['downstairs hallway', 'light sheet', 'door sheet', 'occupancy', 'empty body'],
    tasks: [
      'Why is the Downstairs Hallway body empty?',
      'Does the Downstairs Hallway Light open the Door sheet?',
      'Where do I check the garage-adjacent hallway door?',
    ],
    coversRoutes: ['downstairs-hallway'],
    blocks: [],
    pageGuide: {
      routePath: 'downstairs-hallway',
      complexity: 'simple',
      generatedRoomPath: 'downstairs-hallway',
      orientation: 'Downstairs Hallway deliberately has no body sections, but its four header summaries are independent working destinations. Light opens the light sheet, Climate opens the downstairs temperature view, Occupancy opens the single presence zone, and Door opens the garage-adjacent contact. The corrected light hash is no longer shared with Door, so the two cards should never resolve to the same detail after the route is current.',
      visiblePageSectionNames: ['Header Summaries', 'Nothing Here Yet!'],
      whatYouCanDo: [
        'Open Light for the downstairs hallway fixture. This is now a distinct light destination rather than an accidental alias of the Door sheet.',
        'Open Climate to inspect the presence-sensor temperature used for this hallway’s compact range.',
        'Open Occupancy to read the single Downstairs Hallway presence sensor without searching for additional zones.',
        'Open Door to inspect the contact between the garage area and hallway. Its physical state is separate from the light and occupancy values.',
        'Recognize “Nothing Here Yet!” as the complete configured body, not a pending list of cards or a failed modal load.',
      ],
      whatHappensAutomatically: {
        mode: 'automatic',
        items: [
          'All four header states update even though the body remains empty, and each hash change selects its own configured sheet.',
          'Downstairs Hallway presence can participate in room lighting behavior when its Presence-Based Lighting policy is enabled.',
          'The garage-adjacent contact can influence contact and climate summaries elsewhere in the app without adding a body section here.',
        ],
      },
      lookHereFirst: [
        { label: 'Light sheet title', explanation: 'It should identify the hallway light. If Door appears instead, the client is likely running an older cached route configuration.' },
        { label: 'Door contact', explanation: 'This reports a physical opening near the garage and should not be inferred from occupancy.' },
        { label: 'Single occupancy zone', explanation: 'There is one configured presence sensor, so troubleshooting stays focused on that source.' },
        { label: 'Empty-state message', explanation: 'The message is expected after the hash fix and does not invalidate the four header sheets.' },
      ],
      safetyAndLimitations: {
        title: 'Verify the physical door before changing nearby automation',
        text: 'The contact, light, temperature, and occupancy sources describe different conditions. Do not use one as proof of another, and do not repeat commands if an old cached build opens the wrong sheet. The thermostat screenshot is reused to explain shared climate behavior, not to depict this hallway.',
      },
      troubleshootingChecks: [
        'If Light opens Door, reload the latest app version and confirm the URL hash changes to the light-specific destination.',
        'If Door appears open unexpectedly, inspect the physical garage-adjacent contact and then compare the Contact Sensors overview.',
        'If Occupancy does not clear, verify the single presence source and its availability.',
        'If someone expects cards below the header, compare the current sourceSections configuration; it intentionally contains none.',
      ],
      screenshotIds: ['thermostat-options'],
      relatedArticleIds: ['status-lights', 'thermostat-and-contacts', 'presence-based-lighting', 'states-and-feedback'],
    },
  },
  {
    id: 'room-garage',
    kind: 'page-guide',
    sectionId: 'rooms',
    parentId: 'browse-pages',
    title: 'Garage page guide',
    summary: 'Door-contact detail, washer and dryer status, and immediate left and right garage-door movement commands.',
    icon: 'mdi:garage',
    status: 'current',
    aliases: ['garage doors', 'washer dryer status', 'left garage door', 'right garage door'],
    visibleLabels: ['Doors', 'Washing Machine', 'Dryer', 'Left Door', 'Right Door'],
    ownsSurfaceIds: ['route:garage'],
    keywords: ['garage', 'doors', 'washer', 'dryer', 'laundry status', 'immediate command'],
    tasks: [
      'Which Garage cards move a physical door immediately?',
      'Can I control the washer or dryer from Garage?',
      'What does the Garage header summary open?',
      'Why is there no separate Garage occupancy card?',
    ],
    coversRoutes: ['garage'],
    blocks: [],
    pageGuide: {
      routePath: 'garage',
      complexity: 'simple',
      generatedRoomPath: 'garage',
      orientation: 'Garage has one header summary and two body sections. The configured header is Doors, which opens the garage contact sheet; there is no separate occupancy summary in the room configuration. Appliances shows Washing Machine and Dryer as status-only helpers. Garage Doors contains Left Door and Right Door, and each of those cards immediately toggles its cover through Home Assistant instead of opening detail or asking for confirmation.',
      visiblePageSectionNames: ['Header Summaries', 'Appliances', 'Garage Doors'],
      whatYouCanDo: [
        'Open the Doors header summary to inspect the configured garage contact before deciding whether a moving-door command is appropriate.',
        'Read Washing Machine to see whether its started helper is active. The card has no action, so selecting it cannot start, pause, or stop the appliance.',
        'Read Dryer the same way: it is a live status indicator only and does not expose a cycle-control sheet.',
        'Select Left Door once to send an immediate toggle to the left garage cover. Closed requests opening, Open requests closing, and transitional reporting may make another toggle unsafe.',
        'Select Right Door once for the corresponding right cover. It is independent of the left card but uses the same no-confirmation interaction pattern.',
      ],
      whatHappensAutomatically: {
        mode: 'automatic',
        items: [
          'Washer and dryer helper states update as Home Assistant marks their cycles started or cleared; the page does not infer cycle control from those values.',
          'Each garage-door card updates through Closed, Opening, Open, Closing, or unavailable states as the physical cover reports movement.',
          'The header contact and the two movable covers are separate sources, so their summaries can disagree during travel or if one sensor is delayed.',
        ],
      },
      lookHereFirst: [
        { label: 'Physical doorway', explanation: 'Check for people, pets, vehicles, tools, and obstructions before touching Left Door or Right Door.' },
        { label: 'Movement state', explanation: 'Opening or Closing means the system is already moving. Wait for a stable Open or Closed report.' },
        { label: 'Laundry card semantics', explanation: 'Washing Machine and Dryer are status-only even though they use the same tile shape as actionable cards.' },
        { label: 'Header scope', explanation: 'The configured header is a Doors contact summary, not a garage occupancy control.' },
      ],
      safetyAndLimitations: {
        title: 'Garage door cards move equipment without confirmation',
        text: 'The left and right cards are immediate physical controls. Maintain sight of the doorway, select the intended side once, and wait for a stable state. Do not use laundry helper status as proof an appliance is safe to open. The reused Security image shows shared garage controls and is not a Garage route screenshot.',
      },
      troubleshootingChecks: [
        'If a door remains Opening or Closing, stop sending toggles and inspect the physical mechanism, obstruction sensors, and connection.',
        'If the header contact disagrees with a cover card, wait for movement to finish and identify which sensor is stale.',
        'If a washer or dryer card never changes, verify the corresponding started helper and its automation; tapping the card cannot repair it.',
        'If an expected occupancy header is absent, compare the current room configuration: only the Doors summary is configured in this runtime.',
      ],
      screenshotIds: ['section-security-context'],
      relatedArticleIds: ['security-access-controls', 'media-appliances-vehicle', 'device-families', 'states-and-feedback'],
    },
  },
  {
    id: 'room-guest-bathroom',
    kind: 'page-guide',
    sectionId: 'rooms',
    parentId: 'browse-pages',
    title: 'Guest Bathroom page guide',
    summary: 'Guest-bath light and two-zone presence detail, shared climate summary, vent sheet, and direct fan and towel heat.',
    icon: 'mdi:shower',
    status: 'current',
    aliases: ['guest bath fan', 'guest bath towel rack', 'guest bathroom entry sensor'],
    visibleLabels: ['Light', 'Climate', 'Occupancy', 'Vent', 'Fan', 'Towel Rack'],
    ownsSurfaceIds: ['route:guest-bathroom'],
    keywords: ['guest bathroom', 'entry occupancy', 'fan', 'heated towel rack', 'vent'],
    tasks: [
      'How do I turn on the Guest Bathroom fan?',
      'Which sensors make Guest Bathroom Occupancy active?',
      'Where can I inspect the Guest Bathroom vent?',
      'Does the Guest Bathroom Towel Rack act immediately?',
    ],
    coversRoutes: ['guest-bathroom'],
    blocks: [],
    pageGuide: {
      routePath: 'guest-bathroom',
      complexity: 'simple',
      generatedRoomPath: 'guest-bathroom',
      orientation: 'Guest Bathroom puts three summaries in the header and three different interaction types in Climate. Light opens the dimmer sheet. The Climate header displays the broad shared climate range, while its sheet resolves to Guest Bathroom readings for the Presence and Entry temperature zones plus the vent. Occupancy combines Guest Bathroom and Entry presence sensors. In the body, Vent opens detail, but Fan and Towel Rack toggle immediately.',
      visiblePageSectionNames: ['Header Summaries', 'Climate'],
      whatYouCanDo: [
        'Open Light for the Guest Bathroom dimmer and its supported brightness controls.',
        'Open Occupancy to distinguish the main bathroom sensor from the Entry sensor when the header reports Occupied.',
        'Open Climate to inspect both bathroom temperature zones and the vent rather than treating the broad header range as one local sensor.',
        'Open Vent for the dedicated vent detail sheet. Selecting the Vent card does not directly toggle it from the body.',
        'Select Fan to toggle the bathroom fan immediately, or select Towel Rack to toggle towel heat immediately. Neither direct card opens a sheet or confirmation.',
      ],
      whatHappensAutomatically: {
        mode: 'automatic',
        items: [
          'Main-room and Entry presence roll into one Occupancy summary, so someone crossing the doorway can keep the header active.',
          'The direct Fan and Towel Rack cards update their On or Off state after Home Assistant confirms the switch change; the warm towel color is a persistent state cue.',
          'Bathroom lighting can follow its Presence-Based Lighting configuration while fan and towel-heat choices remain explicit direct commands on this page.',
          'Climate readings for Presence and Entry continue updating independently of the vent state and the whole-home range shown in the header.',
        ],
      },
      lookHereFirst: [
        { label: 'Two occupancy sensors', explanation: 'Guest Bathroom differs from the Master Bathroom by including a separate Entry zone.' },
        { label: 'Fan card', explanation: 'This is an immediate toggle. Select only when you intend to change the physical fan.' },
        { label: 'Towel Rack color', explanation: 'The warm highlighted state means the heater is On; the tile is not merely a navigation card.' },
        { label: 'Climate header versus sheet', explanation: 'The compact header uses a broad climate summary, while the opened sheet contains room-specific Presence and Entry readings.' },
      ],
      safetyAndLimitations: {
        title: 'Fan and towel heat do not provide a confirmation step',
        text: 'Check whether the bathroom is occupied, dry, and safe before toggling equipment. The towel rack is a heater, not a light despite sharing the light control family, and it should not be left on based only on color. The reused thermostat image explains the shared climate sheet, not this bathroom’s current values.',
      },
      troubleshootingChecks: [
        'If Occupancy stays active, open the sheet and check both the bathroom and Entry sensors.',
        'If Fan or Towel Rack does not change, wait for Home Assistant confirmation and verify the corresponding switch before tapping again.',
        'If the Climate header seems unrelated to local readings, open it and compare the Guest Bathroom Presence and Entry zones.',
        'If Vent is unavailable, verify its cover source; the direct fan and towel controls may still remain usable.',
      ],
      screenshotIds: ['thermostat-options'],
      relatedArticleIds: ['thermostat-and-contacts', 'presence-based-lighting', 'status-lights', 'media-appliances-vehicle'],
    },
  },
  {
    id: 'room-master-bathroom',
    kind: 'page-guide',
    sectionId: 'rooms',
    parentId: 'browse-pages',
    title: 'Master Bathroom page guide',
    summary: 'Master-bath light and single presence sensor, local climate detail, vent sheet, and direct fan and towel heat.',
    icon: 'mdi:bathtub',
    status: 'current',
    aliases: ['master bath fan', 'master bath towel rack', 'primary bathroom'],
    visibleLabels: ['Light', 'Climate', 'Occupancy', 'Vent', 'Fan', 'Towel Rack'],
    ownsSurfaceIds: ['route:master-bathroom'],
    keywords: ['master bathroom', 'single occupancy sensor', 'fan', 'towel heater', 'vent'],
    tasks: [
      'How do I control the Master Bathroom towel heater?',
      'Does Master Bathroom Occupancy use one sensor?',
      'Where do I open the Master Bathroom vent?',
      'Which Master Bathroom controls toggle immediately?',
    ],
    coversRoutes: ['master-bathroom'],
    blocks: [],
    pageGuide: {
      routePath: 'master-bathroom',
      complexity: 'simple',
      generatedRoomPath: 'master-bathroom',
      orientation: 'Master Bathroom resembles the Guest Bathroom visually but uses a different sensor composition. The header opens the dimmer, a climate summary that resolves to the Master Bathroom Presence temperature and vent, and one occupancy sensor. Climate contains Vent, Fan, and Towel Rack. Vent opens a sheet; Fan and Towel Rack are direct switch toggles with no intervening detail or confirmation.',
      visiblePageSectionNames: ['Header Summaries', 'Climate'],
      whatYouCanDo: [
        'Open Light to adjust the Master Bathroom dimmer through the shared light detail controls.',
        'Open Climate to review the bathroom Presence temperature and vent in the room-specific climate sheet.',
        'Open Occupancy to inspect the single Master Bathroom presence sensor. Unlike the Guest Bathroom, this summary does not include a separate Entry zone.',
        'Open Vent to see the vent detail and availability without moving it directly from the page body.',
        'Select Fan when you intend to toggle ventilation now, and select Towel Rack when you intend to toggle towel heat now. Both act immediately.',
      ],
      whatHappensAutomatically: {
        mode: 'automatic',
        items: [
          'The single presence source updates the Occupancy header and can participate in Master Bathroom Presence-Based Lighting when that room behavior is enabled.',
          'Fan and Towel Rack tiles hold their requested appearance only until Home Assistant confirms or replaces the live switch state.',
          'The towel tile uses a warm persistent color while On, making heater state visible without changing its immediate-toggle behavior.',
          'Temperature, vent, light, and occupancy reporting continue independently; a missing vent does not convert the fan or towel rack into status-only cards.',
        ],
      },
      lookHereFirst: [
        { label: 'One occupancy zone', explanation: 'Troubleshoot the Master Bathroom presence sensor directly; there is no Entry sensor in this room group.' },
        { label: 'Direct Fan toggle', explanation: 'The card changes the fan immediately and does not open controls first.' },
        { label: 'Direct Towel Rack toggle', explanation: 'Warm color indicates active heat. Treat the tile as a heater command even though its family is styled like lighting.' },
        { label: 'Vent disclosure', explanation: 'The Vent card is the only body item here that opens a detail sheet rather than toggling immediately.' },
      ],
      safetyAndLimitations: {
        title: 'Confirm heat and ventilation at the fixture',
        text: 'A direct toggle can energize the fan or towel rack with one selection. Check occupancy, moisture, fabrics, and the physical heater before leaving it on. Do not infer an Entry zone from the Guest Bathroom layout; Master Bathroom uses one presence source. The thermostat screenshot is a shared illustration only.',
      },
      troubleshootingChecks: [
        'If Occupancy looks wrong, inspect the single Master Bathroom sensor instead of searching for a second configured zone.',
        'If Fan or Towel Rack remains unchanged, wait for confirmation and check the physical switch entity before another toggle.',
        'If the Climate sheet lacks expected values, verify the Master Bathroom Presence temperature and vent sources.',
        'If the warm towel color remains after the heater is physically off, compare the Home Assistant switch state and refresh the route.',
      ],
      screenshotIds: ['thermostat-options'],
      relatedArticleIds: ['thermostat-and-contacts', 'presence-based-lighting', 'status-lights', 'media-appliances-vehicle'],
    },
  },
  {
    id: 'room-entryway',
    kind: 'page-guide',
    sectionId: 'rooms',
    parentId: 'browse-pages',
    title: 'Entryway page guide',
    summary: 'Front-entry light, two-zone presence, door-area climate, and the front-door contact in a header-only route.',
    icon: 'mdi:door',
    status: 'current',
    aliases: ['front entry', 'front door room', 'entry light'],
    visibleLabels: ['Light', 'Occupancy', 'Climate', 'Door', 'Nothing Here Yet!'],
    ownsSurfaceIds: ['route:entryway'],
    keywords: ['entryway', 'front door', 'presence', 'entry light', 'empty body'],
    tasks: [
      'Why is the Entryway body empty?',
      'Which Entryway presence zones are shown?',
      'Where do I check the front-door contact?',
      'How do I open the Entryway light controls?',
    ],
    coversRoutes: ['entryway'],
    blocks: [],
    pageGuide: {
      routePath: 'entryway',
      complexity: 'simple',
      generatedRoomPath: 'entryway',
      orientation: 'Entryway is another intentional header-only page. Light opens the upper-entry switch detail, Occupancy combines Entryway and Front Door presence zones, Climate opens the front-door temperature group, and Door opens the front-door contact sheet. No sourceSections are configured, so “Nothing Here Yet!” fills the body while the four header destinations remain the complete current route.',
      visiblePageSectionNames: ['Header Summaries', 'Nothing Here Yet!'],
      whatYouCanDo: [
        'Open Light to inspect and control the Entryway switch through its focused light sheet.',
        'Open Occupancy to distinguish Entryway activity from Front Door presence instead of relying only on the combined header state.',
        'Open Climate to read the front-door-area temperature used by the Entryway climate group.',
        'Open Door to inspect whether the front-door contact is Open or Closed. This room sheet reports contact state; locking belongs to Security.',
        'Use the empty body as a clear boundary: there are currently no Entryway appliance, vent, camera, or device cards below the header.',
      ],
      whatHappensAutomatically: {
        mode: 'automatic',
        items: [
          'Both presence zones roll up into Occupancy and can support Entryway Presence-Based Lighting when enabled.',
          'The front-door contact contributes to contact and climate safeguards elsewhere while remaining a read-only detail on this room route.',
          'Header summaries keep receiving live state even though no body section is rendered, and the empty message stays until configuration changes.',
        ],
      },
      lookHereFirst: [
        { label: 'Door versus lock', explanation: 'This card reports and opens the contact sensor. Use Security for the immediate front-door lock command.' },
        { label: 'Two presence zones', explanation: 'Entryway and Front Door can activate separately; open Occupancy to identify the source.' },
        { label: 'Header order', explanation: 'Occupancy appears before Climate on this route, matching the actual runtime card order.' },
        { label: 'Nothing Here Yet!', explanation: 'The body is intentionally empty and should not be mistaken for a failed device fetch.' },
      ],
      safetyAndLimitations: {
        title: 'Contact state is not proof the front door is secured',
        text: 'Closed describes the contact, not the lock. Verify lock state from Security and check the physical doorway when access matters. Presence can miss or briefly retain activity, so do not use it as the only safety check. The reused light-detail screenshot demonstrates the shared control family rather than Entryway state.',
      },
      troubleshootingChecks: [
        'If Door is Closed but security is uncertain, open Security and inspect the front-door lock separately.',
        'If Occupancy remains active, check both Entryway and Front Door presence zones.',
        'If Light opens unavailable controls, verify the upper-entry switch and its mapping before retrying.',
        'If body controls are expected, compare the room configuration; Entryway currently has no source sections.',
      ],
      screenshotIds: ['status-lights-detail'],
      relatedArticleIds: ['security-access-controls', 'status-lights', 'presence-based-lighting', 'thermostat-and-contacts'],
    },
  },
]
