export const MANUAL_TASK_WORKFLOW_REGISTRY = [
  { id: 'find-page', title: 'Find a page' },
  { id: 'open-room', title: 'Open a room' },
  { id: 'arm-alarm', title: 'Arm the alarm' },
  { id: 'disarm-alarm', title: 'Disarm the alarm' },
  { id: 'lock-door', title: 'Lock the front door' },
  { id: 'unlock-door', title: 'Unlock the front door' },
  { id: 'open-garage', title: 'Open a garage door' },
  { id: 'close-garage', title: 'Close a garage door' },
  { id: 'open-camera', title: 'Open a security camera' },
  { id: 'camera-snapshot', title: 'Take a camera snapshot' },
  { id: 'camera-audio', title: 'Change camera audio' },
  { id: 'camera-record', title: 'Start or stop manual camera recording' },
  { id: 'adjust-whole-home-thermostat', title: 'Adjust the whole-home thermostat' },
  { id: 'adjust-room-thermostat', title: 'Adjust a room thermostat' },
  { id: 'investigate-contact-pause', title: 'Investigate a climate pause caused by an open contact' },
  { id: 'configure-predictive-comfort', title: 'Configure Predictive Comfort' },
  { id: 'change-sleepypod-temperature-scope', title: 'Choose a SleepyPod temperature scope' },
  { id: 'create-wake-alarm', title: 'Create a wake alarm' },
  { id: 'edit-wake-alarm', title: 'Edit a wake alarm' },
  { id: 'create-humidifier-activity', title: 'Create a humidifier activity' },
  { id: 'edit-humidifier-activity', title: 'Edit a humidifier activity' },
  { id: 'create-repeating-chore', title: 'Create a repeating chore' },
  { id: 'edit-repeating-chore', title: 'Edit a repeating chore' },
  { id: 'delete-repeating-chore', title: 'Delete a repeating chore' },
  { id: 'complete-task', title: 'Complete a household task' },
  { id: 'add-admin-todo', title: 'Add an Admin To-Do item' },
  { id: 'add-grocery', title: 'Add a grocery item' },
  { id: 'complete-grocery', title: 'Complete a grocery item' },
  { id: 'scan-food', title: 'Scan food into inventory' },
  { id: 'manually-add-food', title: 'Manually add food to inventory' },
  { id: 'edit-grouped-inventory', title: 'Edit grouped food inventory' },
  { id: 'change-inventory-quantity', title: 'Change food inventory quantity' },
  { id: 'change-inventory-expiration', title: 'Change food inventory expiration' },
  { id: 'change-prepared-state', title: 'Change prepared-food state' },
  { id: 'send-inventory-to-groceries', title: 'Send inventory to groceries' },
  { id: 'search-recipes', title: 'Search recipes' },
  { id: 'sort-recipes', title: 'Sort recipes' },
  { id: 'filter-recipes', title: 'Filter recipes' },
  { id: 'open-recipe', title: 'Open a recipe' },
  { id: 'add-missing-recipe-ingredients', title: 'Add supported missing recipe ingredients' },
  { id: 'control-room-light', title: 'Control a room light' },
  { id: 'change-presence-override', title: 'Change a presence-lighting override' },
  { id: 'configure-presence-auto-reset', title: 'Configure presence-lighting auto-reset' },
  { id: 'clean-vacuum-rooms', title: 'Clean selected vacuum rooms' },
  { id: 'clean-vacuum-zones', title: 'Clean selected vacuum zones' },
  { id: 'draw-vacuum-area', title: 'Draw a temporary vacuum area' },
  { id: 'use-vacuum-dock-controls', title: 'Use vacuum dock controls' },
  { id: 'use-vacuum-mop-controls', title: 'Use vacuum mop controls' },
  { id: 'handle-vacuum-error', title: 'Handle a robot vacuum error' },
  { id: 'use-media-remote', title: 'Use a media remote' },
  { id: 'launch-media-app', title: 'Launch a media app' },
  { id: 'choose-media-device', title: 'Control a media device' },
  { id: 'send-media-text', title: 'Send text to a media player' },
  { id: 'run-pc-power-command', title: 'Run a room computer power command' },
  { id: 'use-dishwasher', title: 'Use the dishwasher controls' },
  { id: 'use-grill', title: 'Use the grill controls' },
  { id: 'configure-guests', title: 'Configure guest rooms' },
  { id: 'start-vacation-mode', title: 'Start Vacation Mode' },
  { id: 'cancel-vacation-mode', title: 'Cancel Vacation Mode' },
  { id: 'run-living-room-recovery', title: 'Run Living Room power recovery' },
  { id: 'change-relay-control-mode', title: 'Change Relay Control Mode' },
  { id: 'troubleshoot-unavailable-control', title: 'Troubleshoot an unavailable control' },
  { id: 'troubleshoot-unconfirmed-control', title: 'Troubleshoot an unconfirmed control' },
] as const

export type ManualTaskWorkflowId = (typeof MANUAL_TASK_WORKFLOW_REGISTRY)[number]['id']
