import { roomCardFamilyArticleId } from './roomCardFamilies'
import type { ManualScreenshotConfig } from './screenshots'

export const MANUAL_WORKFLOW_SCREENSHOT_IDS = [
  'weather-sheet',
  'weather-precipitation',
  'weather-wind',
  'guest-presence-security',
  'rooms-picker',
  'room-air-sheet',
  'room-dishwasher-sheet',
  'room-climate-sheet',
  'room-contact-sheet',
  'room-grill-sheet',
  'room-humidifier-sheet',
  'humidifier-schedules',
  'humidifier-info',
  'room-occupancy-sheet',
  'room-vent-sheet',
  'sleepypod-main',
  'sleepypod-modes',
  'sleepypod-alarms',
  'sleepypod-status',
  'eight-sleep-schedule',
  'eight-sleep-modes',
  'eight-sleep-alarms',
  'eight-sleep-status',
  'eight-sleep-settings',
  'sleepypod-temperature-scope',
  'sleepypod-alarm-day',
  'sleepypod-alarm-editor',
  'media-remote-controls',
  'media-remote-apps',
  'media-remote-devices',
  'media-remote-text',
  'vacuum-controls',
  'vacuum-zones',
  'vacuum-auto-clean',
  'vacuum-actions',
  'vacuum-info-recovery',
  'presence-overrides-overview',
  'presence-auto-reset',
  'thermostat-controls-rooms',
  'thermostat-controls-automation',
  'thermostat-controls-tracking',
  'thermostat-room',
  'predictive-comfort',
  'thermostat-selected-rooms',
  'thermostat-critical-protection',
  'thermostat-occupied-only',
  'custom-light-detail',
  'vacation-active-cancel',
  'inventory-grouped-detail',
  'inventory-single-detail',
  'inventory-sort',
  'inventory-filter',
  'daily-report-overview',
  'daily-report-upcoming',
  'daily-report-expired-food',
  'daily-report-task-detail',
  'daily-report-inventory-detail',
  'recipe-detail-general',
  'recipe-detail-ingredients',
  'recipe-detail-instructions',
  'recipe-sort',
  'recipe-filter',
  'custom-light-mode-picker',
  'thermostat-hub-mode-picker',
  'thermostat-hub-fan-picker',
  'eco-critical-tracking-picker',
  'eco-away-behavior-picker',
  'create-task-floating-action',
  'grocery-add',
  'admin-todo-add',
] as const

const MANUAL_WORKFLOW_SCREENSHOT_DEFINITIONS: ManualScreenshotConfig[] = [
  {
    id: 'weather-sheet',
    articleId: 'weather-surface-guide',
    surfaceId: 'home.weather-sheet',
    coveredSurfaceIds: ['home.weather-mode-condition'],
    surfaceTargetEvidence: {
      'home.weather-sheet': ['Weather', 'Today', 'Partly Cloudy', '45°'],
      'home.weather-mode-condition': ['Conditions', 'Conditions conditions', 'Temperature (F)'],
    },
    role: 'modal',
    scenarioId: 'weather-sheet',
    requiredTargets: ['Weather', 'Today', 'Partly Cloudy', '45°', 'Conditions', 'Conditions conditions', 'Temperature (F)'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 820,
    alt: 'Weather sheet showing deterministic current conditions and the hourly conditions panel.',
    caption: 'What appears in the Weather sheet? Current synthetic conditions lead into the hourly mode controls without using live location data.',
  },
  {
    id: 'weather-precipitation',
    articleId: 'weather-surface-guide',
    surfaceId: 'home.weather-mode-precipitation',
    allowAnimations: true,
    role: 'modal',
    scenarioId: 'weather-precipitation',
    requiredTargets: ['Weather', 'Conditions', 'Precipitation conditions', 'Precipitation chance (%)', 'Now', '0%'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 820,
    alt: 'Weather sheet with the real Precipitation hourly mode selected and deterministic zero-percent synthetic periods.',
    caption: 'How do I compare hourly rain? Precipitation replaces the hourly condition values with probability and available accumulation.',
  },
  {
    id: 'weather-wind',
    articleId: 'weather-surface-guide',
    surfaceId: 'home.weather-mode-wind',
    allowAnimations: true,
    role: 'modal',
    scenarioId: 'weather-wind',
    requiredTargets: ['Weather', 'Conditions', 'Wind conditions', 'Speed (mph) · Gusts', 'Now'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 820,
    alt: 'Weather sheet with the real Wind hourly mode selected and deterministic speed, direction, and gust values.',
    caption: 'How do I compare hourly wind? Wind replaces the hourly condition values with direction, speed, and gust evidence.',
  },
  {
    id: 'guest-presence-security',
    articleId: 'guest-controls-page-guide',
    surfaceId: 'security.guest-presence-sheet',
    role: 'modal',
    scenarioId: 'guest-presence-security',
    requiredTargets: ['Guest Presence Security', 'Guest Rooms', 'Guest Room', 'Music Room', 'Theater Room'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 820,
    desktopCaptureWidth: 1280,
    cropSubject: true,
    cropHeight: 510,
    desktopCropHeight: 720,
    alt: 'Guest Presence Security sheet showing three synthetic guest-room states before security review.',
    caption: 'How do I review guest safeguards? Guest Presence Security begins with the synthetic room-presence choices that activate the guarded workflow.',
  },
  {
    id: 'rooms-picker',
    articleId: 'rooms-picker-guide',
    surfaceId: 'rooms.picker-sheet',
    role: 'modal',
    scenarioId: 'rooms-picker',
    requiredTargets: ['Rooms', 'Living Room', 'Guest Room', 'Gym', 'Master Bedroom'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 820,
    desktopCaptureWidth: 1280,
    mobileCropSubject: true,
    cropHeight: 380,
    desktopCropHeight: 820,
    alt: 'Rooms picker showing stable room cards for four representative dashboard destinations.',
    caption: 'How do I choose a room? The real Rooms picker presents every configured destination without changing device state.',
  },
  {
    id: 'room-air-sheet',
    articleId: roomCardFamilyArticleId('air'),
    surfaceId: 'room.air-sheet',
    role: 'modal',
    scenarioId: 'room-air-sheet',
    requiredTargets: ['Guest Room Air Quality', 'Fan Modes', 'Auto Modes', 'Auto', 'Quiet'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    cropSubject: true,
    cropHeight: 500,
    desktopCropHeight: 510,
    alt: 'Guest Room air purifier sheet showing synthetic Auto and Quiet mode choices.',
    caption: 'What controls are in a room air sheet? Fan mode and its Auto sub-mode remain separate, explicit choices.',
  },
  {
    id: 'room-dishwasher-sheet',
    articleId: roomCardFamilyArticleId('appliance'),
    surfaceId: 'room.dishwasher-sheet',
    role: 'modal',
    scenarioId: 'room-dishwasher-sheet',
    requiredTargets: ['Dishwasher', 'Status', 'Operation', 'Cleaning', 'Progress', '42%'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    alsoUsedByArticleIds: ['task-use-dishwasher'],
    alt: 'Dishwasher sheet showing a deterministic active cleaning operation at forty-two percent.',
    caption: 'How do I verify a dishwasher run? The Status section confirms the synthetic Cleaning branch and its reported progress.',
  },
  {
    id: 'room-climate-sheet',
    articleId: roomCardFamilyArticleId('climate'),
    surfaceId: 'room.climate-sheet',
    role: 'modal',
    scenarioId: 'room-climate-sheet',
    requiredTargets: ['Guest Room Climate', 'Temperature Sensors', 'Presence', 'Closet', 'Vent', 'Open'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    cropSubject: true,
    cropHeight: 340,
    desktopCropHeight: 340,
    alt: 'Guest Room climate sheet showing synthetic room sensors and the open vent state.',
    caption: 'What is inside a room climate sheet? The room range expands into contributing sensors and vent state.',
  },
  {
    id: 'room-contact-sheet',
    articleId: roomCardFamilyArticleId('contact'),
    surfaceId: 'room.contact-sheet',
    role: 'modal',
    scenarioId: 'room-contact-sheet',
    requiredTargets: ['Office Windows', 'PC Window', 'Open', 'Window', 'Closed'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    cropSubject: true,
    cropHeight: 250,
    desktopCropHeight: 250,
    alt: 'Office contact sheet identifying one synthetic open window and one closed window.',
    caption: 'How do I locate an open room contact? The Office sheet identifies the exact synthetic opening beside the closed contact.',
  },
  {
    id: 'room-grill-sheet',
    articleId: roomCardFamilyArticleId('grill'),
    surfaceId: 'room.grill-sheet',
    role: 'modal',
    scenarioId: 'room-grill-sheet',
    requiredTargets: ['Back Deck: Bear Grills', 'cooking', 'Probe 1', '225', 'Pellet Level', 'Keep Warm', 'Super Smoke'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    cropSubject: true,
    cropHeight: 330,
    desktopCropHeight: 330,
    alsoUsedByArticleIds: ['task-use-grill'],
    alt: 'Bear Grills sheet showing synthetic cooking, probe, pellet, Keep Warm, and Super Smoke states.',
    caption: 'How do I monitor an active grill? The real sheet displays deterministic cooking and probe values with both persistent smoke controls.',
  },
  {
    id: 'room-humidifier-sheet',
    articleId: 'humidifier-schedule',
    surfaceId: 'room.humidifier-sheet',
    coveredSurfaceIds: ['climate.humidifier-tab-controls'],
    surfaceTargetEvidence: {
      'room.humidifier-sheet': ['Master Bedroom Humidifier', 'Humidifying', 'Mode', 'Manual'],
      'climate.humidifier-tab-controls': ['Mode', 'Manual', 'Mist Output', 'Medium'],
    },
    role: 'modal',
    scenarioId: 'room-humidifier-sheet',
    requiredTargets: ['Master Bedroom Humidifier', 'Humidifying', 'Mode', 'Manual', 'Mist Output', 'Medium'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 820,
    desktopCaptureWidth: 1280,
    cropHeight: 600,
    desktopCropHeight: 590,
    alsoUsedByArticleIds: [roomCardFamilyArticleId('humidifier')],
    alt: 'Humidifier sheet showing deterministic Manual mode and medium mist output.',
    caption: 'What is on the humidifier main sheet? Current synthetic humidity leads into explicit mode and mist controls.',
  },
  {
    id: 'humidifier-schedules',
    articleId: 'humidifier-schedule',
    surfaceId: 'climate.humidifier-tab-schedules',
    role: 'modal',
    scenarioId: 'humidifier-schedules',
    requiredTargets: ['Master Bedroom Humidifier', 'Schedules', 'Scheduling On', '1 activity configured', 'Activities', 'Synthetic Night Profile', 'Weekdays', '10:00 PM–7:00 AM', 'Sleep'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 820,
    desktopCaptureWidth: 1280,
    cropSubject: true,
    cropHeight: 780,
    desktopCropHeight: 600,
    alt: 'Humidifier Schedules tab showing one enabled synthetic weekday overnight activity.',
    caption: 'What does Humidifier Schedules show? The real list pairs Home Assistant schedule state with one privacy-safe recurring profile.',
  },
  {
    id: 'humidifier-info',
    articleId: 'humidifier-schedule',
    surfaceId: 'climate.humidifier-tab-info',
    role: 'modal',
    scenarioId: 'humidifier-info',
    requiredTargets: ['Master Bedroom Humidifier', 'Master Bedroom humidifier info panel', 'Device State', 'Output', 'Humidifying', 'Water', 'OK', 'Tank', 'Installed', 'Environment', 'Humidity', '46%', 'Temperature', '72°F'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 820,
    desktopCaptureWidth: 1280,
    cropSubject: true,
    cropHeight: 780,
    desktopCropHeight: 780,
    alt: 'Humidifier Info tab showing deterministic healthy device and environmental readings.',
    caption: 'What does Humidifier Info report? Device condition and room readings stay read-only and visibly separate from Controls.',
  },
  {
    id: 'room-occupancy-sheet',
    articleId: roomCardFamilyArticleId('occupancy'),
    surfaceId: 'room.occupancy-sheet',
    role: 'modal',
    scenarioId: 'room-occupancy-sheet',
    requiredTargets: ['Guest Room Occupancy', 'Occupied', 'Guest Room', 'Detected', 'Closet', 'Clear'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    cropSubject: true,
    cropHeight: 250,
    desktopCropHeight: 250,
    alt: 'Guest Room occupancy sheet showing one synthetic detected sensor and one clear sensor.',
    caption: 'How do I identify room occupancy? The focused sheet traces the aggregate state to each contributing synthetic sensor.',
  },
  {
    id: 'room-vent-sheet',
    articleId: roomCardFamilyArticleId('vent'),
    surfaceId: 'room.vent-sheet',
    role: 'modal',
    scenarioId: 'room-vent-sheet',
    requiredTargets: ['Living Room: Vents', 'Vent 1', 'Open', 'Vent 2', 'Closed'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    cropSubject: true,
    cropHeight: 250,
    desktopCropHeight: 250,
    alt: 'Living Room vent sheet showing one synthetic open register and one closed register.',
    caption: 'What does a room vent sheet show? Each configured register keeps its own deterministic position.',
  },
  {
    id: 'sleepypod-main',
    articleId: 'wake-alarms',
    surfaceId: 'room.sleepypod-sheet',
    coveredSurfaceIds: ['climate.sleepypod-tab-schedule'],
    surfaceTargetEvidence: {
      'room.sleepypod-sheet': ['Synthetic Bed', 'Temperature', 'Sleep Schedule'],
      'climate.sleepypod-tab-schedule': ['Temperature', 'Sleep Schedule', 'Bedtime', 'Asleep', 'Dawn'],
    },
    role: 'modal',
    scenarioId: 'sleepypod-main',
    requiredTargets: ['Synthetic Bed', 'Temperature', 'Sleep Schedule', 'Bedtime', 'Asleep', 'Dawn'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    alsoUsedByArticleIds: ['task-change-sleepypod-temperature', 'task-manage-wake-alarm'],
    alt: 'SleepyPod main sheet with the private side name replaced and three synthetic schedule stages.',
    caption: 'What is on the SleepyPod main sheet? The selected synthetic side shows Bedtime, Asleep, and Dawn targets together.',
  },
  {
    id: 'sleepypod-modes',
    articleId: 'wake-alarms',
    surfaceId: 'climate.sleepypod-tab-modes',
    role: 'modal',
    scenarioId: 'sleepypod-modes',
    requiredTargets: ['Synthetic Bed', 'Temperature', 'Special Modes', 'Hot Flash Mode', 'Inactive', 'fifteen minutes'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    alt: 'SleepyPod climate-adapter Special Modes tab showing the deterministic inactive Hot Flash Mode state.',
    caption: 'What is in SleepyPod Special Modes? The climate-adapter sheet exposes temporary thermal behavior without changing the recurring stages.',
  },
  {
    id: 'sleepypod-alarms',
    articleId: 'wake-alarms',
    surfaceId: 'climate.sleepypod-tab-alarms',
    role: 'modal',
    scenarioId: 'sleepypod-alarms',
    requiredTargets: ['Synthetic Bed', 'Temperature', 'Alarms', 'Sunday Alarm', '6:30 AM', 'Enabled', 'Add Alarm'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    alt: 'SleepyPod climate-adapter Alarms tab showing one enabled synthetic Sunday wake alarm.',
    caption: 'What is on the SleepyPod Alarms tab? A privacy-safe day group exposes its time, enabled state, and Add Alarm action.',
  },
  {
    id: 'sleepypod-status',
    articleId: 'wake-alarms',
    surfaceId: 'climate.sleepypod-tab-status',
    role: 'modal',
    scenarioId: 'sleepypod-status',
    requiredTargets: ['Synthetic Bed', 'Status', 'Pump Status', 'OK', 'Loop Temp', '79', 'Pump RPM', '2450'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    cropHeight: 660,
    desktopCropHeight: 630,
    maxDiffPixelRatio: 0.025,
    alt: 'SleepyPod climate-adapter Status tab showing deterministic pump health, loop temperature, and pump speed.',
    caption: 'What does SleepyPod Status show? The adapter keeps current pump-health evidence together without changing it.',
  },
  {
    id: 'eight-sleep-schedule',
    articleId: 'wake-alarms',
    surfaceId: 'climate.eight-sleep-tab-schedule',
    role: 'modal',
    scenarioId: 'eight-sleep-schedule',
    requiredTargets: ['Synthetic Bed', 'Sleep Schedule', 'Settings', 'Bedtime', 'Asleep', 'Dawn'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    alt: 'Legacy-compatible Eight Sleep Schedule tab showing deterministic recurring Bedtime, Asleep, and Dawn stages.',
    caption: 'What is on the legacy Sleep Schedule tab? The fallback presentation exposes the same three recurring stages plus its Settings destination.',
  },
  {
    id: 'eight-sleep-modes',
    articleId: 'wake-alarms',
    surfaceId: 'climate.eight-sleep-tab-modes',
    role: 'modal',
    scenarioId: 'eight-sleep-modes',
    requiredTargets: ['Synthetic Bed', 'Sleep Schedule', 'Settings', 'Special Modes', 'Hot Flash Mode', 'Inactive'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    alt: 'Legacy-compatible Eight Sleep Special Modes tab showing deterministic inactive Hot Flash Mode.',
    caption: 'What is in legacy Special Modes? The fallback presentation reaches the real temporary-mode surface while retaining legacy Settings.',
  },
  {
    id: 'eight-sleep-alarms',
    articleId: 'wake-alarms',
    surfaceId: 'climate.eight-sleep-tab-alarms',
    role: 'modal',
    scenarioId: 'eight-sleep-alarms',
    requiredTargets: ['Synthetic Bed', 'Sleep Schedule', 'Settings', 'Alarms', 'Sunday Alarm', '6:30 AM', 'Enabled', 'Add Alarm'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    alt: 'Legacy-compatible Eight Sleep Alarms tab showing one enabled synthetic Sunday wake alarm.',
    caption: 'What is on legacy Alarms? The fallback adapter uses the real shared alarm records and day-group controls.',
  },
  {
    id: 'eight-sleep-status',
    articleId: 'wake-alarms',
    surfaceId: 'climate.eight-sleep-tab-status',
    role: 'modal',
    scenarioId: 'eight-sleep-status',
    requiredTargets: ['Synthetic Bed', 'Sleep Schedule', 'Settings', 'Status', 'Presence', 'In Bed', 'Time Remaining', '2h', 'Alarm', 'Idle'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    alt: 'Legacy-compatible Eight Sleep Status tab showing deterministic temperature, presence, remaining time, and alarm state.',
    caption: 'What does legacy Status report? The fallback presentation keeps its synthetic side state and alarm summary read-only.',
  },
  {
    id: 'eight-sleep-settings',
    articleId: 'wake-alarms',
    surfaceId: 'climate.eight-sleep-tab-settings',
    role: 'modal',
    scenarioId: 'eight-sleep-settings',
    requiredTargets: ['Synthetic Bed', 'Sleep Schedule', 'Settings', 'Bedtime', '9:30 PM', 'Controls', 'Away Mode', 'Off'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    alt: 'Legacy-compatible Eight Sleep Settings tab showing deterministic bedtime and Away Mode controls.',
    caption: 'What is in legacy Settings? The fallback-only tab keeps Bedtime and Away Mode controls on the selected synthetic side.',
  },
  {
    id: 'sleepypod-temperature-scope',
    articleId: 'wake-alarms',
    surfaceId: 'climate.sleepypod-temperature-scope-prompt',
    role: 'modal',
    scenarioId: 'sleepypod-temperature-scope',
    requiredTargets: ['Set Bed Temperature', 'Synthetic Bed', 'Bedtime', 'Tonight', 'All Nights', 'Cancel'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 440,
    alsoUsedByArticleIds: ['task-change-sleepypod-temperature'],
    alt: 'Set Bed Temperature prompt with a redacted bed name and Tonight or All Nights choices.',
    caption: 'How do I scope a SleepyPod change? The prompt distinguishes the current synthetic night from the recurring stage.',
  },
  {
    id: 'sleepypod-alarm-day',
    articleId: 'wake-alarms',
    surfaceId: 'climate.sleepypod-alarm-day',
    role: 'detail',
    scenarioId: 'sleepypod-alarm-day',
    requiredTargets: ['Synthetic Bed', 'Sunday Alarms', '6:30 AM', '7:15 AM', 'Add Alarm'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    alsoUsedByArticleIds: ['task-manage-wake-alarm'],
    alt: 'SleepyPod Sunday alarm page with a redacted side name and two synthetic wake times.',
    caption: 'How do I manage one wake-alarm day? The day page keeps both synthetic alarms and the day-scoped Add Alarm action together.',
  },
  {
    id: 'sleepypod-alarm-editor',
    articleId: 'wake-alarms',
    surfaceId: 'climate.sleepypod-alarm-editor',
    role: 'detail',
    scenarioId: 'sleepypod-alarm-editor',
    requiredTargets: ['Synthetic Bed', 'Sunday Alarm', 'Time', 'Alarm Enabled', 'Delete Alarm', 'Save Alarm'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    alsoUsedByArticleIds: ['task-manage-wake-alarm'],
    alt: 'SleepyPod alarm editor with a redacted side name, enabled state, and guarded save and delete actions.',
    caption: 'How do I edit a wake alarm? The same sheet exposes its synthetic time, enabled state, Save, and guarded Delete actions.',
  },
  {
    id: 'media-remote-controls',
    articleId: 'media-page-guide',
    surfaceId: 'media.remote-sheet',
    coveredSurfaceIds: ['media.remote-tab-controls'],
    surfaceTargetEvidence: {
      'media.remote-sheet': ['Theater Room SHIELD Remote', 'Yamaha Volume', 'Navigation', 'Controls'],
      'media.remote-tab-controls': ['Yamaha Volume', 'Navigation', 'Controls'],
    },
    role: 'modal',
    scenarioId: 'media-remote-controls',
    requiredTargets: ['Theater Room SHIELD Remote', 'Yamaha Volume', 'Navigation', 'Controls'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 820,
    desktopCaptureWidth: 1280,
    alsoUsedByArticleIds: ['task-use-media-remote'],
    alt: 'Theater remote Controls tab showing synthetic volume, navigation, and playback sections.',
    caption: 'What is on the media Controls tab? Power and directional controls stay with volume, navigation shortcuts, and playback.',
  },
  {
    id: 'media-remote-apps',
    articleId: 'media-page-guide',
    surfaceId: 'media.remote-tab-apps',
    role: 'modal',
    scenarioId: 'media-remote-apps',
    requiredTargets: ['Theater Room SHIELD Remote', 'Media'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 820,
    desktopCaptureWidth: 1280,
    alsoUsedByArticleIds: ['task-use-media-remote'],
    alt: 'Theater remote Apps tab showing the real app-launch grid with local deterministic artwork.',
    caption: 'Where are media app launchers? The Apps tab replaces lower controls with the configured local launcher grid.',
  },
  {
    id: 'media-remote-devices',
    articleId: 'media-page-guide',
    surfaceId: 'media.remote-tab-devices',
    role: 'modal',
    scenarioId: 'media-remote-devices',
    requiredTargets: ['Theater Room SHIELD Remote', 'Devices', 'Projector', 'On', 'Yamaha AVR', 'Theater Room PC', 'Off'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 820,
    desktopCaptureWidth: 1280,
    alsoUsedByArticleIds: ['task-use-media-remote'],
    alt: 'Theater remote Devices tab showing deterministic On and Off device branches.',
    caption: 'What can I control from Devices? Projector, receiver, SHIELD, and PC retain separate synthetic states and commands.',
  },
  {
    id: 'media-remote-text',
    articleId: 'media-page-guide',
    surfaceId: 'media.remote-text-prompt',
    role: 'detail',
    scenarioId: 'media-remote-text',
    requiredTargets: ['Theater Room SHIELD Remote', 'Navigation', 'Text to send', 'Send', 'Cancel'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 820,
    desktopCaptureWidth: 1280,
    alsoUsedByArticleIds: ['task-use-media-remote'],
    alt: 'Theater remote inline text prompt containing deterministic synthetic text and Send or Cancel actions.',
    caption: 'How do I send media text? Keyboard expands the real inline prompt without exposing household text.',
  },
  {
    id: 'vacuum-controls',
    articleId: 'vacuums-page-guide',
    surfaceId: 'cleaning.vacuum-tab-controls',
    role: 'modal',
    scenarioId: 'vacuum-controls',
    requiredTargets: ['Rooms', 'No rooms are selected', '1x', 'Clean', 'Power Settings', 'Mode', 'Fan'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 820,
    desktopCaptureWidth: 1280,
    cropSelector: '[role="dialog"] [data-tab="controls"]',
    cropSubject: true,
    cropHeight: 680,
    desktopCropHeight: 620,
    maxDiffPixelRatio: 0.025,
    alt: 'Main Floor vacuum Controls panel showing deterministic room-target, pass, mode, and fan settings before cleaning.',
    caption: 'What is on Vacuum Controls? The real panel keeps target, selected rooms, passes, power settings, and Clean together.',
  },
  {
    id: 'vacuum-zones',
    articleId: 'vacuums-page-guide',
    surfaceId: 'cleaning.vacuum-tab-zones',
    coveredSurfaceIds: ['cleaning.vacuum-sheet'],
    surfaceTargetEvidence: {
      'cleaning.vacuum-tab-zones': ['Main Floor Robot Vacuum', 'Zones', 'Kitchen', 'Living Room'],
      'cleaning.vacuum-sheet': ['Main Floor Robot Vacuum', 'Zones'],
    },
    role: 'modal',
    scenarioId: 'vacuum-zones',
    requiredTargets: ['Main Floor Robot Vacuum', 'Zones', 'Rooms are cleaned in the order you select them.', 'Kitchen', 'Living Room'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 820,
    desktopCaptureWidth: 1280,
    maxDiffPixelRatio: 0.025,
    alsoUsedByArticleIds: ['task-clean-vacuum-rooms'],
    alt: 'Main Floor vacuum Zones tab showing Kitchen first and Living Room second in a synthetic cleaning order.',
    caption: 'How do I order vacuum rooms? Numbered zone badges preserve the synthetic order selected in the real sheet.',
  },
  {
    id: 'vacuum-auto-clean',
    articleId: 'vacuums-page-guide',
    surfaceId: 'cleaning.vacuum-tab-autoClean',
    role: 'modal',
    scenarioId: 'vacuum-auto-clean',
    requiredTargets: ['Main Floor Robot Vacuum', 'Auto-Clean', 'Disabled Auto-Clean Rooms', 'Living Room', 'Master Bedroom', 'Kitchen', 'Office', 'manual selected-room cleans still use the Zones tab'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 820,
    desktopCaptureWidth: 1280,
    cropSubject: true,
    cropHeight: 720,
    desktopCropHeight: 700,
    maxDiffPixelRatio: 0.025,
    alt: 'Main Floor vacuum Auto-Clean tab showing deterministic excluded and included room choices.',
    caption: 'What does Vacuum Auto-Clean change? Checked rooms are skipped only by the away cleaning controller while manual Zones remain separate.',
  },
  {
    id: 'vacuum-actions',
    articleId: 'vacuums-page-guide',
    surfaceId: 'cleaning.vacuum-tab-more',
    role: 'modal',
    scenarioId: 'vacuum-actions',
    requiredTargets: ['Main Floor Robot Vacuum', 'Dock Controls', 'Dock Status', 'Idle', 'Clean Mop Dock', 'Dry Mops', 'Empty Bin'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 820,
    desktopCaptureWidth: 1280,
    maxDiffPixelRatio: 0.025,
    alsoUsedByArticleIds: ['task-use-vacuum-dock'],
    alt: 'Main Floor vacuum Actions tab showing deterministic dock status and three dock commands.',
    caption: 'Which dock actions are available? The Actions tab exposes mop cleaning, drying, and bin emptying only after prerequisites are met.',
  },
  {
    id: 'vacuum-info-recovery',
    articleId: 'vacuums-page-guide',
    surfaceId: 'cleaning.vacuum-tab-info',
    role: 'modal',
    scenarioId: 'vacuum-info-recovery',
    requiredTargets: ['Main Floor Robot Vacuum', 'Charging Before Resuming', 'Synthetic brush obstruction cleared', 'Consumables', 'Main Brush'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 820,
    desktopCaptureWidth: 1280,
    maxDiffPixelRatio: 0.025,
    alsoUsedByArticleIds: ['task-recover-vacuum-error'],
    alt: 'Main Floor vacuum Info tab showing a synthetic mapped error, charging recovery state, and consumables.',
    caption: 'How do I assess vacuum recovery? The status pane prefers a synthetic mapped error while Info keeps consumable evidence visible.',
  },
  {
    id: 'presence-overrides-overview',
    articleId: 'presence-based-lighting',
    surfaceId: 'admin.presence-overrides-sheet',
    role: 'modal',
    scenarioId: 'presence-overrides-overview',
    requiredTargets: ['Presence-Based Overrides', 'Living Room', 'Enabled', 'Kitchen', 'Paused', 'Hallway', 'Quieted'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 820,
    alt: 'Presence-Based Overrides overview showing deterministic Enabled, Paused, and Quieted room states.',
    caption: 'How do I compare presence overrides? The overview distinguishes persistent semantic states before a room is opened.',
  },
  {
    id: 'presence-auto-reset',
    articleId: 'presence-based-lighting',
    surfaceId: 'admin.presence-auto-reset-sheet',
    role: 'modal',
    scenarioId: 'presence-auto-reset',
    requiredTargets: ['Presence-Based Overrides Auto-Reset', 'Living Room', 'On', 'Kitchen', 'Off', 'Hallway'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 820,
    alt: 'Presence-Based Overrides Auto-Reset sheet showing deterministic room eligibility states.',
    caption: 'Where do I configure overnight presence recovery? Auto-Reset keeps each room eligibility switch independent.',
  },
  {
    id: 'thermostat-controls-rooms',
    articleId: 'thermostat-controls-guide',
    surfaceId: 'climate.thermostat-controls-sheet',
    coveredSurfaceIds: ['climate.thermostat-tab-rooms'],
    surfaceTargetEvidence: {
      'climate.thermostat-controls-sheet': ['Thermostat', 'Rooms', 'Living Room'],
      'climate.thermostat-tab-rooms': ['Rooms', 'Living Room', 'Office', 'Master Bedroom'],
    },
    role: 'modal',
    scenarioId: 'thermostat-controls-rooms',
    requiredTargets: ['Thermostat', 'Rooms', 'Living Room', 'Office', 'Master Bedroom'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 720,
    alsoUsedByArticleIds: ['thermostat-page-guide'],
    alt: 'Thermostat sheet open on Rooms with explanatory text and deterministic temperature and occupancy rows.',
    caption: 'Where are room thermostats? Rooms explains the list before opening each focused room detail.',
  },
  {
    id: 'thermostat-controls-automation',
    articleId: 'thermostat-controls-guide',
    surfaceId: 'climate.thermostat-tab-automation',
    role: 'modal',
    scenarioId: 'thermostat-controls-automation',
    requiredTargets: ['Automatic Thermostat', 'Eco Mode', 'Eco Mode Critical Tracking', 'Predictive Comfort'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 720,
    cropSubject: true,
    cropHeight: 1200,
    maxViewportHeightRatio: 1.5,
    alt: 'Thermostat Automation tab showing explanatory text above plain toggle and list controls.',
    caption: 'Where are automatic thermostat settings? Automation explains the master, Eco policy, and Predictive Comfort before each control.',
  },
  {
    id: 'thermostat-controls-tracking',
    articleId: 'thermostat-controls-guide',
    surfaceId: 'climate.thermostat-tab-tracking',
    role: 'modal',
    scenarioId: 'thermostat-controls-tracking',
    requiredTargets: ['Room Tracking', 'Track Selected Rooms', 'Selected Rooms', 'Critical Protection', 'Occupied Only'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 720,
    alt: 'Thermostat Tracking tab showing explanations above the three batch room-rule rows.',
    caption: 'Where are room participation rules? Tracking explains selected, critical-protection, and occupied-only batches before opening them.',
  },
  {
    id: 'thermostat-room',
    articleId: 'thermostat-controls-guide',
    surfaceId: 'climate.thermostat-room-detail',
    role: 'detail',
    scenarioId: 'thermostat-room',
    requiredTargets: ['Living Room', 'Living Room Vents', 'Vent 1', 'Open', 'Vent 2'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    alt: 'Living Room thermostat sheet showing a deterministic Heat/Cool target and both room vents.',
    caption: 'What is in a thermostat room sheet? The room dial and its configured vents stay in one focused control surface.',
  },
  {
    id: 'predictive-comfort',
    articleId: 'thermostat-controls-guide',
    surfaceId: 'climate.predictive-comfort-detail',
    role: 'detail',
    scenarioId: 'predictive-comfort',
    requiredTargets: ['Predictive Comfort', 'Controls', 'Auto Setpoint Adjustments', 'HVAC Mode Changes', 'Predictive Comfort While Away'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    mobileCropSubject: true,
    cropHeight: 700,
    desktopCropHeight: 810,
    alsoUsedByArticleIds: ['task-configure-predictive-comfort'],
    alt: 'Predictive Comfort sheet showing its three independently permissioned synthetic controls.',
    caption: 'How do I configure Predictive Comfort? Setpoint, HVAC-mode, and away permissions remain separate choices.',
  },
  {
    id: 'thermostat-selected-rooms',
    articleId: 'thermostat-controls-guide',
    surfaceId: 'climate.tracking-selected-rooms-detail',
    role: 'detail',
    scenarioId: 'thermostat-selected-rooms',
    requiredTargets: ['Selected Rooms', 'Living Room', 'Office', 'Master Bedroom', 'Kitchen'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 720,
    alt: 'Selected Rooms detail page showing a dynamic grid of tracked and untracked room checkboxes.',
    caption: 'Which rooms participate in selected-room tracking? This dynamic grid keeps every configured room in one checklist.',
  },
  {
    id: 'thermostat-critical-protection',
    articleId: 'thermostat-controls-guide',
    surfaceId: 'climate.tracking-critical-protection-detail',
    role: 'detail',
    scenarioId: 'thermostat-critical-protection',
    requiredTargets: ['Critical Protection', 'Music Room', 'Theater Room'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 720,
    alt: 'Critical Protection detail page showing a dynamic grid of eligible unselected rooms.',
    caption: 'Which unselected rooms retain critical protection? The dynamic grid excludes rooms already selected for normal participation.',
  },
  {
    id: 'thermostat-occupied-only',
    articleId: 'thermostat-controls-guide',
    surfaceId: 'climate.tracking-occupied-only-detail',
    role: 'detail',
    scenarioId: 'thermostat-occupied-only',
    requiredTargets: ['Occupied Only', 'Living Room', 'Guest Bathroom', 'Master Bathroom'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 720,
    alt: 'Occupied Only detail page showing deterministic occupancy-gated room choices.',
    caption: 'Which rooms participate only while occupied? This batch page keeps the occupancy gates together.',
  },
  {
    id: 'custom-light-detail',
    articleId: 'custom-lights-page-guide',
    surfaceId: 'custom-lights.detail-sheet',
    role: 'modal',
    scenarioId: 'custom-light-detail',
    requiredTargets: ['Left Door Light', 'R', 'G', 'B', 'Reset', 'Apply to All Lights'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    mobileCropSubject: true,
    cropHeight: 680,
    desktopCropHeight: 836,
    alt: 'Custom light detail sheet showing synthetic RGB controls and reset or apply-all actions.',
    caption: 'What can I change in Custom Light detail? Brightness and deterministic color controls stay scoped to the selected fixture.',
  },
  {
    id: 'vacation-active-cancel',
    articleId: 'vacation-page-guide',
    surfaceId: 'route:vacation',
    role: 'state',
    scenarioId: 'vacation-active-cancel',
    requiredTargets: ['Vacation', 'Vacation Mode', 'On', 'Vacation Dates', 'Start Date', 'End Date'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 820,
    desktopCaptureWidth: 1280,
    cropSelector: '[data-manual-route-context="vacation"]',
    cropHeight: 520,
    desktopCropHeight: 430,
    maxViewportHeightRatio: 0.7,
    alsoUsedByArticleIds: ['task-cancel-vacation-mode'],
    alt: 'Vacation route in a deterministic active state with inline dates and the On card used to cancel.',
    caption: 'How do I cancel an active vacation? Select the synthetic On card after reviewing the inline trip dates.',
  },
  {
    id: 'inventory-grouped-detail',
    articleId: 'food-inventory',
    surfaceId: 'food.inventory-detail-sheet',
    coveredSurfaceIds: ['food.inventory-grouped-detail'],
    surfaceTargetEvidence: {
      'food.inventory-detail-sheet': ['Synthetic Batch Item', 'Quantity', 'Expiration Date', 'Prepared Food Item'],
      'food.inventory-grouped-detail': ['Synthetic Batch Item', 'In the pantry', 'In the fridge', 'Prepared'],
    },
    role: 'detail',
    scenarioId: 'inventory-grouped-detail',
    requiredTargets: ['Synthetic Batch Item', 'In the pantry', 'In the fridge', 'Prepared', 'Quantity', 'Expiration Date', 'Prepared Food Item'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    alsoUsedByArticleIds: ['task-edit-food-inventory'],
    alt: 'Grouped synthetic inventory detail showing separate pantry and prepared fridge batches.',
    caption: 'How do I edit grouped inventory? Each synthetic location, expiration, quantity, and prepared batch remains independently addressable.',
  },
  {
    id: 'inventory-single-detail',
    articleId: 'food-inventory',
    surfaceId: 'food.inventory-single-detail',
    role: 'detail',
    scenarioId: 'inventory-single-detail',
    requiredTargets: ['Synthetic Single Item', 'In the pantry', 'Quantity', 'Expiration Date', 'Prepared Food Item'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    cropSubject: true,
    cropHeight: 480,
    desktopCropHeight: 480,
    alsoUsedByArticleIds: ['task-edit-food-inventory'],
    alt: 'Single synthetic inventory detail showing quantity, expiration, and prepared-food controls.',
    caption: 'How do I edit one inventory batch? The single-detail sheet keeps all editable synthetic batch fields together.',
  },
  {
    id: 'inventory-sort',
    articleId: 'food-inventory',
    surfaceId: 'food.inventory-sort-sheet',
    role: 'modal',
    scenarioId: 'inventory-sort',
    requiredTargets: ['Sort Inventory', 'Sort By', 'Title', 'Expiration Date', 'Sort Direction', 'Ascending'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 560,
    alsoUsedByArticleIds: ['task-edit-food-inventory'],
    alt: 'Sort Inventory sheet showing title or expiration ordering and ascending direction.',
    caption: 'How do I sort inventory? Choose the field and direction in a draft, then Apply.',
  },
  {
    id: 'inventory-filter',
    articleId: 'food-inventory',
    surfaceId: 'food.inventory-filter-sheet',
    role: 'modal',
    scenarioId: 'inventory-filter',
    requiredTargets: ['Filter Inventory', 'Filter Items', 'All Items', 'Expired', 'Expiring Within a Week'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 560,
    alsoUsedByArticleIds: ['task-edit-food-inventory'],
    alt: 'Filter Inventory sheet showing deterministic expiration filter choices.',
    caption: 'How do I filter inventory? The sheet preserves explicit expiration scopes until Apply.',
  },
  {
    id: 'daily-report-overview',
    articleId: 'daily-report',
    surfaceId: 'chores.daily-report-sheet',
    coveredSurfaceIds: ['chores.daily-report-tab-overdue'],
    surfaceTargetEvidence: {
      'chores.daily-report-sheet': ['Synthetic Resident Summary', 'Overdue Chores', 'Synthetic report chore'],
      'chores.daily-report-tab-overdue': ['Overdue Chores', 'Synthetic report chore'],
    },
    role: 'modal',
    scenarioId: 'daily-report-overview',
    requiredTargets: ['Synthetic Resident Summary', 'Overdue Chores', 'Synthetic report chore'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 620,
    alt: 'Daily Report overview with the resident name redacted and one synthetic overdue chore.',
    caption: 'What needs attention in Daily Report? The privacy-safe overview starts on the synthetic overdue work for the selected resident.',
  },
  {
    id: 'daily-report-upcoming',
    articleId: 'daily-report',
    surfaceId: 'chores.daily-report-tab-upcoming',
    role: 'modal',
    scenarioId: 'daily-report-upcoming',
    requiredTargets: ['Synthetic Resident Summary', 'Upcoming Chores', 'Synthetic upcoming chore', 'Edit Synthetic upcoming chore'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 620,
    alt: 'Daily Report Upcoming Chores tab with one privacy-safe synthetic task later today.',
    caption: 'What is coming up today? Upcoming Chores shows the selected resident’s remaining synthetic work without an attention badge.',
  },
  {
    id: 'daily-report-expired-food',
    articleId: 'daily-report',
    surfaceId: 'chores.daily-report-tab-expired-food',
    role: 'modal',
    scenarioId: 'daily-report-expired-food',
    requiredTargets: ['Synthetic Resident Summary', 'Expired Food', 'Synthetic Report Produce', 'Quantity 2'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 620,
    alt: 'Daily Report Expired Food tab showing one privacy-safe synthetic inventory row.',
    caption: 'What expired food needs attention? The report exposes the real inventory row before any batch detail is opened.',
  },
  {
    id: 'daily-report-task-detail',
    articleId: 'daily-report',
    surfaceId: 'chores.daily-report-task-detail',
    role: 'detail',
    scenarioId: 'daily-report-task-detail',
    requiredTargets: ['Edit Task', 'Task Name', 'Assignee', 'Priority', 'Recurrence', 'Save Task'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 620,
    alt: 'Daily Report task detail showing the complete synthetic task editor and Save action.',
    caption: 'How do I edit a report task? The summary opens the real full task form in the same open sheet.',
  },
  {
    id: 'daily-report-inventory-detail',
    articleId: 'daily-report',
    surfaceId: 'food.daily-report-inventory-detail',
    role: 'detail',
    scenarioId: 'daily-report-inventory-detail',
    requiredTargets: ['Synthetic Report Produce', 'In the pantry', 'Quantity', 'Expiration Date', 'Prepared Food Item'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 620,
    cropSubject: true,
    cropHeight: 480,
    desktopCropHeight: 480,
    alt: 'Daily Report expired-food detail showing a synthetic inventory batch editor.',
    caption: 'How do I inspect expired food from Daily Report? The selected synthetic row opens the shared inventory detail in place.',
  },
  {
    id: 'recipe-detail-general',
    articleId: 'recipes',
    surfaceId: 'food.recipe-detail-general',
    role: 'modal',
    scenarioId: 'recipe-detail-general',
    requiredTargets: ['Suggested Citrus Pantry Bowl with Roasted Garden Vegetables', 'General', 'Ingredients', 'Instructions', 'Yield', 'Serves 4', 'Active Time', '25 min', 'Total Time', '1 hr', 'Difficulty', 'Easy', 'Freshness', 'Current', 'Aug 7, 2026', 'Additional Equipment', 'Large bowl', 'Sheet pan', 'Open Source Recipe'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 720,
    maxDiffPixelRatio: 0.05,
    alt: 'Recipe detail General panel showing deterministic status pills and anchored icon-only footer tabs.',
    caption: 'What is on Recipe General? The real detail sheet shows factual status pills supplied by EverShelf, a clear freshness state and date, source information, and footer navigation.',
  },
  {
    id: 'recipe-detail-ingredients',
    articleId: 'recipes',
    surfaceId: 'food.recipe-detail-ingredients',
    coveredSurfaceIds: ['food.recipe-grocery-add'],
    surfaceTargetEvidence: {
      'food.recipe-detail-ingredients': ['Ingredients', 'Section 2', 'Yellow Onion · 1 small', 'Source: yellow onion, diced', 'Matched as Yellow onion', 'Missing from inventory', 'Add Missing Ingredients to Groceries'],
      'food.recipe-grocery-add': ['Add Missing Ingredients to Groceries', 'Missing ingredients were submitted.', 'EverShelf: 2 added.', 'Home Assistant mirror: 2 added.'],
    },
    role: 'modal',
    scenarioId: 'recipe-detail-ingredients',
    requiredTargets: ['Suggested Citrus Pantry Bowl with Roasted Garden Vegetables', 'Ingredients', 'Section 2', 'Yellow Onion · 1 small', 'Source: yellow onion, diced', 'Matched as Yellow onion', 'Missing from inventory', 'Add Missing Ingredients to Groceries', 'Missing ingredients were submitted.', 'EverShelf: 2 added.', 'Home Assistant mirror: 2 added.'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 720,
    maxDiffPixelRatio: 0.05,
    alt: 'Recipe detail Ingredients panel showing a grouped section, inline amount, source wording, explicit closest match, and confirmed grocery result.',
    caption: 'What happens after adding missing recipe ingredients? Group headings and inline source amounts keep the inventory rows readable while the submitted Home Assistant result remains visible.',
  },
  {
    id: 'recipe-detail-instructions',
    articleId: 'recipes',
    surfaceId: 'food.recipe-detail-instructions',
    role: 'modal',
    scenarioId: 'recipe-detail-instructions',
    requiredTargets: ['Catalog Recipe 1', 'General', 'Ingredients', 'Instructions', 'Prepare', 'Serve', '1.', '2.', '3.', 'Combine the prepared ingredients in a large bowl.', 'Divide into bowls and serve.'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 720,
    maxDiffPixelRatio: 0.05,
    alt: 'Local recipe Instructions panel showing labeled sections and semantic numbered rows.',
    caption: 'How are local instructions organized? Authorized groups keep their labels and render as vertically spaced numbered list rows without interactive control semantics.',
  },
  {
    id: 'recipe-sort',
    articleId: 'recipes',
    surfaceId: 'food.recipe-sort-sheet',
    role: 'modal',
    scenarioId: 'recipe-sort',
    requiredTargets: ['Sort Recipes', 'Sort By', 'Ingredients Available', 'Expiring Soon', 'Alphabetical'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 560,
    alt: 'Sort Recipes sheet showing the three server-owned ranking choices without recipe content.',
    caption: 'How do I sort recipes? Choose the ranking intent and Apply without locally reordering catalog results.',
  },
  {
    id: 'recipe-filter',
    articleId: 'recipes',
    surfaceId: 'food.recipe-filter-sheet',
    role: 'modal',
    scenarioId: 'recipe-filter',
    requiredTargets: ['Filter Recipes', 'Ingredient Coverage', 'Minimum Ingredients Available', 'Expiring Ingredients', 'Ranking Strength'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 700,
    alt: 'Filter Recipes sheet showing deterministic coverage, expiration, and ranking controls without recipe content.',
    caption: 'How do I filter recipes? Coverage, expiration horizon, and ranking strength stay explicit until Apply.',
  },
  {
    id: 'custom-light-mode-picker',
    articleId: 'custom-lights-page-guide',
    surfaceId: 'option-picker.custom-light-mode',
    role: 'modal',
    scenarioId: 'custom-light-mode-picker',
    requiredTargets: ['Lighting Mode', 'Default', 'Custom', 'Seahawks', "Valentine's Day"],
    privacyClass: 'synthetic',
    desktopMaxWidth: 500,
    cropHeight: 500,
    alt: 'Lighting Mode option sheet showing all four real front-yard mode choices with Custom selected.',
    caption: 'Which Custom Lights modes are available? The real picker exposes Default, Custom, Seahawks, and Valentine’s Day.',
  },
  {
    id: 'thermostat-hub-mode-picker',
    articleId: 'thermostat-page-guide',
    surfaceId: 'option-picker.thermostat-hub-mode',
    role: 'modal',
    scenarioId: 'thermostat-hub-mode-picker',
    requiredTargets: ['Thermostat Hub Mode', 'Off', 'Heat', 'Cool', 'Heat/Cool'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 500,
    cropHeight: 500,
    alt: 'Thermostat Hub Mode option sheet showing Off, Heat, Cool, and Heat/Cool with Heat selected.',
    caption: 'Which Thermostat Hub modes can I choose? The real picker lists the supported HVAC modes from Home Assistant.',
  },
  {
    id: 'thermostat-hub-fan-picker',
    articleId: 'thermostat-page-guide',
    surfaceId: 'option-picker.thermostat-hub-fan',
    role: 'modal',
    scenarioId: 'thermostat-hub-fan-picker',
    requiredTargets: ['Thermostat Hub Fan', 'Auto', 'On', 'Circulate'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 500,
    cropHeight: 500,
    alt: 'Thermostat Hub Fan option sheet showing Auto, On, and Circulate with Auto selected.',
    caption: 'Which Thermostat Hub fan modes can I choose? The real picker lists only the options reported by the physical hub.',
  },
  {
    id: 'eco-critical-tracking-picker',
    articleId: 'thermostat-controls-guide',
    surfaceId: 'climate.eco-critical-tracking-detail',
    role: 'detail',
    scenarioId: 'eco-critical-tracking-picker',
    requiredTargets: ['Eco Mode Critical Tracking', 'Do Not Track Critical', 'Track Select Critical', 'Track All Critical'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 720,
    cropHeight: 500,
    alt: 'Eco Mode Critical Tracking detail page showing a dynamic grid of three room-protection choices.',
    caption: 'How can Eco Mode track critical rooms? The dynamic grid separates no critical tracking, selected untracked rooms, and all rooms.',
  },
  {
    id: 'eco-away-behavior-picker',
    articleId: 'thermostat-controls-guide',
    surfaceId: 'climate.eco-away-behavior-detail',
    role: 'detail',
    scenarioId: 'eco-away-behavior-picker',
    requiredTargets: ['Eco Behavior When Away', 'Disable Eco When Away', 'Use Eco Away Targets', 'Keep Eco Active'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 720,
    cropHeight: 500,
    alt: 'Eco Behavior When Away detail page showing a dynamic grid of three away-policy choices.',
    caption: 'What can Eco Mode do while everyone is away? The dynamic grid exposes disable, away-target, and keep-active policies.',
  },
  {
    id: 'create-task-floating-action',
    articleId: 'chore-scheduling',
    surfaceId: 'floating-action.create-task',
    role: 'focused',
    scenarioId: 'create-task-floating-action',
    requiredTargets: ['Add Task', 'Synthetic recurring task'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 820,
    desktopCaptureWidth: 760,
    cropSelector: '[data-app-shell="true"]',
    cropFromBottom: true,
    cropHeight: 220,
    desktopCropHeight: 220,
    alsoUsedByArticleIds: ['task-manage-repeating-chore'],
    alt: 'Populated Chores list with the Add Task command fixed above the lower navigation.',
    caption: 'Where do I create a chore? Add Task stays fixed above the lower navigation while a populated chore list scrolls behind it.',
  },
  {
    id: 'grocery-add',
    articleId: 'groceries-page-guide',
    surfaceId: 'groceries.add-item-sheet',
    role: 'modal',
    scenarioId: 'grocery-add',
    requiredTargets: ['Add Grocery Item', 'Item'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 560,
    cropSubject: true,
    cropHeight: 250,
    desktopCropHeight: 250,
    alsoUsedByArticleIds: ['task-manage-grocery-item'],
    alt: 'Add Grocery Item sheet containing a deterministic synthetic item name.',
    caption: 'How do I add groceries? Enter one privacy-safe item and use the single Add Item action.',
  },
  {
    id: 'admin-todo-add',
    articleId: 'to-do-page-guide',
    surfaceId: 'admin.add-todo-sheet',
    role: 'modal',
    scenarioId: 'admin-todo-add',
    requiredTargets: ['Add Task', 'Task'],
    privacyClass: 'synthetic',
    desktopMaxWidth: 560,
    cropSubject: true,
    cropHeight: 250,
    desktopCropHeight: 250,
    alsoUsedByArticleIds: ['task-add-admin-todo'],
    alt: 'Admin To-Do Add Task sheet containing deterministic synthetic task text.',
    caption: 'How do I add an Admin To-Do? Enter one privacy-safe task in the separate Settings list sheet.',
  },
]

export const MANUAL_WORKFLOW_SCREENSHOTS: ManualScreenshotConfig[] = MANUAL_WORKFLOW_SCREENSHOT_DEFINITIONS.map((screenshot) => ({
  desktopCaptureWidth: 820,
  ...screenshot,
}))
