http_port 3128

acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl CONNECT method CONNECT
acl github dstdomain \
  .blob.core.windows.net \
  .github.com \
  .githubusercontent.com

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow github
http_access deny all

cache deny all
access_log stdio:/dev/stdout
cache_log /dev/stderr
cache_store_log none
pid_filename none
coredump_dir /tmp
