export type ModalOpenerAffordance = 'action-icon' | 'down-chevron' | 'edit-icon' | 'header-chip' | 'image-card' | 'native-control' | 'right-chevron' | 'stream-pill'

export interface ModalOpenerInventoryItem {
  affordance: ModalOpenerAffordance
  behavior: string
  id: string
  implementation: string
  instances: number | 'dynamic'
  label: string
  exceptionReason?: string
  sourceReference?: string
}

export const EXPECTED_MODAL_OPENER_FAMILY_COUNT = 37

export const MODAL_OPENER_INVENTORY = [
  {
    id: 'weather-hero',
    label: 'Home weather hero',
    instances: 1,
    affordance: 'right-chevron',
    implementation: 'WeatherSummary',
    behavior: 'Opens the local Weather ModalSheet without changing Home Assistant state.',
  },
  {
    id: 'daily-report-profile',
    label: 'Daily Report profile button',
    instances: 1,
    affordance: 'action-icon',
    implementation: 'AppHeader profile button',
    behavior: 'Opens the app-level Daily Report sheet for the current or requested Home Assistant user.',
    exceptionReason: 'The profile avatar and attention badge identify the personalized global report; a disclosure chevron would compete with the compact header action.',
    sourceReference: 'AppHeader and DailyReportModal focused tests.',
  },
  {
    id: 'overview-status-chips',
    label: 'Home status chips',
    instances: 6,
    affordance: 'header-chip',
    implementation: 'StatusRail with OVERVIEW_STATUS_CHIPS',
    behavior: 'Opens the matching hash-backed overview sheet.',
    exceptionReason: 'Header chips are compact summary pills where the icon, title, and live state are the whole affordance; a chevron crowds the pill at mobile widths.',
    sourceReference: 'Mobile header rail coverage in e2e/react-dash.spec.ts.',
  },
  {
    id: 'security-status-chips',
    label: 'Security status chips',
    instances: 2,
    affordance: 'header-chip',
    implementation: 'StatusRail with SECURITY_STATUS_CHIPS',
    behavior: 'Opens Security System or Contact Sensors.',
    exceptionReason: 'Header chips are compact summary pills where the icon, title, and live state are the whole affordance; a chevron crowds the pill at mobile widths.',
    sourceReference: 'Mobile header rail coverage in e2e/react-dash.spec.ts.',
  },
  {
    id: 'room-status-chips',
    label: 'Room header status chips',
    instances: 62,
    affordance: 'header-chip',
    implementation: 'StatusRail generated from ROOM_PAGE_CONFIGS.overviewCards',
    behavior: 'Opens the configured room hash sheet.',
    exceptionReason: 'Header chips are compact summary pills where the icon, title, and live state are the whole affordance; a chevron crowds the pill at mobile widths.',
    sourceReference: 'Mobile header rail coverage in e2e/react-dash.spec.ts.',
  },
  {
    id: 'overview-security-tile',
    label: 'Home Security System quick link',
    instances: 1,
    affordance: 'right-chevron',
    implementation: 'QuickAccessTile',
    behavior: 'Opens Security System.',
  },
  {
    id: 'overview-route-quick-links',
    label: 'Home route quick links',
    instances: 4,
    affordance: 'right-chevron',
    implementation: 'QuickAccessTile with QUICK_ACCESS_ITEMS route entries',
    behavior: 'Navigates to Food, Vacuums, Media, or Custom Lights; marked data-navigation-opener rather than data-modal-opener.',
  },
  {
    id: 'security-system-tile',
    label: 'Security page Security System tile',
    instances: 1,
    affordance: 'right-chevron',
    implementation: 'SecurityTile',
    behavior: 'Opens Security System; adjacent lock and garage tiles remain direct HA actions.',
  },
  {
    id: 'guest-presence-security',
    label: 'Guest Presence Security prompt',
    instances: 2,
    affordance: 'right-chevron',
    implementation: 'GuestPresenceSecuritySection with GlassTile',
    behavior: 'Conditionally appears on Home and Security and opens the guest security sheet.',
  },
  {
    id: 'camera-tiles',
    label: 'Home and Security camera tiles',
    instances: 8,
    affordance: 'stream-pill',
    implementation: 'CameraTile',
    behavior: 'Opens the matching camera sheet; stream state remains HA-owned.',
    exceptionReason: 'The live stream thumbnail plus its title and state pill is the affordance; a chevron competes with the stream and crowds the overlay pill.',
    sourceReference: 'Camera tile and camera sheet coverage in e2e/react-dash.spec.ts.',
  },
  {
    id: 'room-source-cards',
    label: 'Room body hash cards',
    instances: 28,
    affordance: 'right-chevron',
    implementation: 'RoomSourceCard generated from ROOM_PAGE_CONFIGS.sourceSections',
    behavior: 'Opens reusable room content, media, bed, appliance, or vacuum sheets when available.',
  },
  {
    id: 'media-page-remotes',
    label: 'Media page remote cards',
    instances: 2,
    affordance: 'right-chevron',
    implementation: 'MediaPage through RoomSourceCard',
    behavior: 'Opens living-room or theater remote sheets; app shortcut cards remain direct HA actions.',
  },
  {
    id: 'vacuum-page-cards',
    label: 'Vacuum page cards',
    instances: 3,
    affordance: 'right-chevron',
    implementation: 'VacuumCard',
    behavior: 'Opens a vacuum sheet only while the vacuum is available.',
  },
  {
    id: 'admin-config-rows',
    label: 'Admin configuration rows',
    instances: 2,
    affordance: 'right-chevron',
    implementation: 'AdminHashButton through ModalOpenerRow',
    behavior: 'Opens Presence-Based Overrides or Auto-Reset.',
  },
  {
    id: 'thermostat-controls',
    label: 'Thermostat tab entry tiles',
    instances: 3,
    affordance: 'right-chevron',
    implementation: 'ThermostatPageEntry through GlassTile',
    behavior: 'Opens the shared Thermostat sheet directly on Rooms, Automation, or Tracking without changing Home Assistant state.',
  },
  {
    id: 'thermostat-room-rows',
    label: 'Thermostat room rows',
    instances: 11,
    affordance: 'right-chevron',
    implementation: 'ThermostatRoomRow through ModalOpenerRow',
    behavior: 'Opens the selected room detail inside the existing Thermostat sheet.',
  },
  {
    id: 'predictive-comfort',
    label: 'Predictive Comfort active disclosure',
    instances: 1,
    affordance: 'right-chevron',
    implementation: 'PredictiveComfortCard',
    behavior: 'When active, main/disclosure opens the Predictive Comfort page inside the Thermostat sheet and power turns off; when inactive, main turns on.',
  },
  {
    id: 'custom-light-details',
    label: 'Custom light detail cards',
    instances: 8,
    affordance: 'right-chevron',
    implementation: 'LightBrightnessCard',
    behavior: 'Body/disclosure opens more-info, power toggles independently, and horizontal drag sets brightness.',
  },
  {
    id: 'vacation-mode-confirmation',
    label: 'Vacation Mode confirmation card',
    instances: 1,
    affordance: 'right-chevron',
    implementation: 'VacationModeCard through Card',
    behavior: 'Shows disclosure only when the next activation opens Confirm Vacation; other states cancel or disable HA state.',
  },
  {
    id: 'inventory-multi-item-row',
    label: 'Grouped inventory item rows',
    instances: 'dynamic',
    affordance: 'right-chevron',
    implementation: 'PantryRow',
    behavior: 'Row/disclosure opens individual inventory instances.',
  },
  {
    id: 'recipe-cards',
    label: 'Suggested and browse recipe cards',
    instances: 'dynamic',
    affordance: 'image-card',
    implementation: 'RecipeCard through ImageCard',
    behavior: 'Opens the shared Recipe Detail sheet without changing Home Assistant state.',
    exceptionReason: 'The recipe image, title, and ingredient coverage are the complete card affordance; an overlaid chevron would compete with the compact image copy.',
    sourceReference: 'Recipe card activation and detail-modal coverage in focused Vitest and Playwright tests.',
  },
  {
    id: 'recipe-sort-filter-floating-actions',
    label: 'Recipe Sort and Filter floating actions',
    instances: 2,
    affordance: 'action-icon',
    implementation: 'RecipeFloatingActions',
    behavior: 'Opens the Sort Recipes or Filter Recipes sheet without changing the applied query until Apply is selected.',
    exceptionReason: 'The sort and filter glyphs are compact floating commands with persistent active colors; adding a chevron would imply route navigation.',
    sourceReference: 'RecipeFloatingActions focused tests and Recipes route Playwright coverage.',
  },
  {
    id: 'rooms-floating-action',
    label: 'Rooms floating action buttons',
    instances: 17,
    affordance: 'action-icon',
    implementation: 'RoomPickerButton through FloatingActionButton',
    behavior: 'Opens the Rooms sheet.',
    exceptionReason: 'The source-shaped floating action is a launch command, not a content row; its floor-plan icon and Rooms label are the complete affordance.',
    sourceReference: 'At-a-glance route mapping and existing Rooms mobile Playwright baseline.',
  },
  {
    id: 'create-task-floating-actions',
    label: 'Create task floating action buttons',
    instances: 5,
    affordance: 'action-icon',
    implementation: 'CreateChoreButton through FloatingActionButton',
    behavior: 'Opens Create Task.',
    exceptionReason: 'The plus icon is the standard source-shaped create action and a right chevron would imply navigation rather than creation.',
    sourceReference: 'Source-shaped Create Task Playwright coverage in e2e/react-dash.spec.ts.',
  },
  {
    id: 'grocery-floating-actions',
    label: 'Add grocery floating action buttons',
    instances: 2,
    affordance: 'action-icon',
    implementation: 'CreateGroceryButton through FloatingActionButton',
    behavior: 'Opens Add Grocery Item.',
    exceptionReason: 'The plus icon is the create affordance; a navigation chevron would conflict with the action meaning.',
    sourceReference: 'Source-shaped grocery route and modal Playwright coverage.',
  },
  {
    id: 'admin-task-floating-action',
    label: 'Add admin task floating action button',
    instances: 1,
    affordance: 'action-icon',
    implementation: 'CreateAdminTodoButton through FloatingActionButton',
    behavior: 'Opens Add Task for the HA Admin todo list.',
    exceptionReason: 'The plus icon communicates creation and matches the shared floating-action family.',
    sourceReference: 'Admin todo route source mapping and shared FloatingActionButton treatment.',
  },
  {
    id: 'scan-floating-actions',
    label: 'Scan Item floating action buttons',
    instances: 8,
    affordance: 'action-icon',
    implementation: 'ScanItemButton through FloatingActionButton',
    behavior: 'Opens the scan camera sheet.',
    exceptionReason: 'The barcode icon is a direct scan command; icon-only placements cannot accommodate a trailing navigation glyph without obscuring the action.',
    sourceReference: 'Kitchen and inventory source-shaped scan controls in existing Playwright coverage.',
  },
  {
    id: 'inventory-sort-floating-actions',
    label: 'Inventory Sort floating action buttons',
    instances: 6,
    affordance: 'action-icon',
    implementation: 'EverShelfInventoryFloatingActions',
    behavior: 'Opens the Sort sheet.',
    exceptionReason: 'The sort glyph is the action and active-state indicator; a right chevron would weaken the compact toolbar semantics.',
    sourceReference: 'Existing mobile inventory floating-dock baseline and route coverage.',
  },
  {
    id: 'inventory-filter-floating-actions',
    label: 'Inventory Filter floating action buttons',
    instances: 6,
    affordance: 'action-icon',
    implementation: 'EverShelfInventoryFloatingActions',
    behavior: 'Opens the Filter sheet.',
    exceptionReason: 'The filter glyph is the action and active-state indicator; a right chevron would weaken the compact toolbar semantics.',
    sourceReference: 'Existing mobile inventory floating-dock baseline and route coverage.',
  },
  {
    id: 'thermostat-option-pickers',
    label: 'Thermostat option picker buttons',
    instances: 2,
    affordance: 'down-chevron',
    implementation: 'ThermostatSelectButton',
    behavior: 'Opens the Thermostat Hub mode or fan selection sheet and calls the selected HA climate service.',
    exceptionReason: 'A down chevron is the established select/menu affordance and distinguishes option expansion from detail navigation.',
    sourceReference: 'Thermostat Hub picker configuration and source-shaped option-sheet Playwright coverage.',
  },
  {
    id: 'thermostat-option-pages',
    label: 'Thermostat Eco option rows',
    instances: 2,
    affordance: 'right-chevron',
    implementation: 'ThermostatOptionOpener through ModalOpenerRow',
    behavior: 'Opens Critical Tracking or Away Behavior as a same-sheet Thermostat detail page.',
  },
  {
    id: 'thermostat-tracking-rows',
    label: 'Thermostat tracking policy rows',
    instances: 3,
    affordance: 'right-chevron',
    implementation: 'ThermostatTrackingOpener through ModalOpenerRow',
    behavior: 'Opens Selected Rooms, Critical Protection, or Occupied Only inside the existing Thermostat sheet.',
  },
  {
    id: 'custom-light-mode-picker',
    label: 'Custom Lights mode picker',
    instances: 1,
    affordance: 'down-chevron',
    implementation: 'ModeToggleCard',
    behavior: 'Opens Lighting Mode while the sibling control toggles manual lighting.',
    exceptionReason: 'A down chevron identifies the control as a mode selector and prevents confusion with the independent toggle.',
    sourceReference: 'Front-yard mode select configuration and current source-derived mode matrix.',
  },
  {
    id: 'inventory-single-item-edit',
    label: 'Single inventory item edit buttons',
    instances: 'dynamic',
    affordance: 'edit-icon',
    implementation: 'PantryRow',
    behavior: 'Opens the item details sheet directly in the editable single-instance state.',
    exceptionReason: 'The pencil communicates edit intent more precisely than a navigation chevron.',
    sourceReference: 'EverShelf row action mapping and source-shaped inventory behavior tests.',
  },
  {
    id: 'chore-row-edit',
    label: 'DoneTick chore row edit buttons',
    instances: 'dynamic',
    affordance: 'edit-icon',
    implementation: 'TodoListPanel',
    behavior: 'Loads the full DoneTick task and opens the shared task sheet in edit mode.',
    exceptionReason: 'The pencil communicates editing a task while the sibling checkbox remains the completion action.',
    sourceReference: 'Existing Create Task modal, pantry row edit treatment, and live DoneTick todo UID mapping.',
  },
  {
    id: 'native-date-time-controls',
    label: 'Native date and time picker controls',
    instances: 'dynamic',
    affordance: 'native-control',
    implementation: 'NativePickerField and SleepyPod time inputs',
    behavior: 'Opens the platform date/time picker.',
    exceptionReason: 'These are native form controls rather than disclosure rows; platform picker chrome owns the affordance.',
    sourceReference: 'Native input types and mobile picker behavior asserted by existing tests.',
  },
  {
    id: 'native-confirm-prompt-actions',
    label: 'Native confirmation and quantity prompt actions',
    instances: 'dynamic',
    affordance: 'native-control',
    implementation: 'SleepyPod and EverShelf action buttons',
    behavior: 'Opens a native confirmation or prompt before an HA action.',
    exceptionReason: 'The visible power/delete/cart action icon describes the command; the native dialog is a safety step, not a navigation destination.',
    sourceReference: 'Explicit state-to-service matrices and native-dialog tests.',
  },
] as const satisfies readonly ModalOpenerInventoryItem[]

export const MODAL_OPENER_EXCEPTIONS = MODAL_OPENER_INVENTORY.filter((item) => item.affordance !== 'right-chevron')
