export type ModalOpenerAffordance = 'action-icon' | 'down-chevron' | 'edit-icon' | 'native-control' | 'right-chevron'

export interface ModalOpenerInventoryItem {
  affordance: ModalOpenerAffordance
  behavior: string
  id: string
  implementation: string
  instances: number | 'dynamic'
  label: string
  exceptionReason?: string
  sourceReference?: string
}

export const MODAL_OPENER_INVENTORY: ModalOpenerInventoryItem[] = [
  {
    id: 'weather-hero',
    label: 'Home weather hero',
    instances: 1,
    affordance: 'right-chevron',
    implementation: 'WeatherSummary',
    behavior: 'Opens the local Weather ModalSheet without changing Home Assistant state.',
  },
  {
    id: 'overview-status-chips',
    label: 'Home status chips',
    instances: 6,
    affordance: 'right-chevron',
    implementation: 'StatusRail with OVERVIEW_STATUS_CHIPS',
    behavior: 'Opens the matching hash-backed overview sheet.',
  },
  {
    id: 'security-status-chips',
    label: 'Security status chips',
    instances: 2,
    affordance: 'right-chevron',
    implementation: 'StatusRail with SECURITY_STATUS_CHIPS',
    behavior: 'Opens Security System or Contact Sensors.',
  },
  {
    id: 'room-status-chips',
    label: 'Room header status chips',
    instances: 62,
    affordance: 'right-chevron',
    implementation: 'StatusRail generated from ROOM_PAGE_CONFIGS.overviewCards',
    behavior: 'Opens the configured room hash sheet.',
  },
  {
    id: 'overview-security-tile',
    label: 'Home Security System quick link',
    instances: 1,
    affordance: 'right-chevron',
    implementation: 'QuickAccessTile',
    behavior: 'Opens Security System; route-only quick links do not use modal disclosure.',
  },
  {
    id: 'security-system-tile',
    label: 'Security page Security System tile',
    instances: 1,
    affordance: 'right-chevron',
    implementation: 'SecurityTile',
    behavior: 'Opens Security System; adjacent lock and garage tiles remain direct HA actions.',
  },
  {
    id: 'guest-presence-security',
    label: 'Guest Presence Security prompt',
    instances: 2,
    affordance: 'right-chevron',
    implementation: 'GuestPresenceSecuritySection with GlassTile',
    behavior: 'Conditionally appears on Home and Security and opens the guest security sheet.',
  },
  {
    id: 'camera-tiles',
    label: 'Home and Security camera tiles',
    instances: 8,
    affordance: 'right-chevron',
    implementation: 'CameraTile',
    behavior: 'Opens the matching camera sheet; stream state remains HA-owned.',
  },
  {
    id: 'room-source-cards',
    label: 'Room body hash cards',
    instances: 28,
    affordance: 'right-chevron',
    implementation: 'RoomSourceCard generated from ROOM_PAGE_CONFIGS.sourceSections',
    behavior: 'Opens reusable room content, media, bed, appliance, or vacuum sheets when available.',
  },
  {
    id: 'media-page-remotes',
    label: 'Media page remote cards',
    instances: 2,
    affordance: 'right-chevron',
    implementation: 'MediaPage through RoomSourceCard',
    behavior: 'Opens living-room or theater remote sheets; app shortcut cards remain direct HA actions.',
  },
  {
    id: 'vacuum-page-cards',
    label: 'Vacuum page cards',
    instances: 3,
    affordance: 'right-chevron',
    implementation: 'VacuumCard',
    behavior: 'Opens a vacuum sheet only while the vacuum is available.',
  },
  {
    id: 'admin-config-rows',
    label: 'Admin configuration rows',
    instances: 2,
    affordance: 'right-chevron',
    implementation: 'AdminHashButton through ModalOpenerRow',
    behavior: 'Opens Presence-Based Overrides or Auto-Reset.',
  },
  {
    id: 'thermostat-room-rows',
    label: 'Thermostat room rows',
    instances: 11,
    affordance: 'right-chevron',
    implementation: 'ThermostatRoomRow through ModalOpenerRow',
    behavior: 'Opens the selected room thermostat sheet.',
  },
  {
    id: 'predictive-comfort',
    label: 'Predictive Comfort active disclosure',
    instances: 1,
    affordance: 'right-chevron',
    implementation: 'PredictiveComfortCard',
    behavior: 'When active, main/disclosure opens details and power turns off; when inactive, main turns on.',
  },
  {
    id: 'custom-light-details',
    label: 'Custom light detail cards',
    instances: 8,
    affordance: 'right-chevron',
    implementation: 'LightBrightnessCard',
    behavior: 'Body/disclosure opens more-info, power toggles independently, and horizontal drag sets brightness.',
  },
  {
    id: 'vacation-mode-confirmation',
    label: 'Vacation Mode confirmation card',
    instances: 1,
    affordance: 'right-chevron',
    implementation: 'VacationModeCard through Card',
    behavior: 'Shows disclosure only when the next activation opens Confirm Vacation; other states cancel or disable HA state.',
  },
  {
    id: 'inventory-multi-item-row',
    label: 'Grouped inventory item rows',
    instances: 'dynamic',
    affordance: 'right-chevron',
    implementation: 'PantryRow',
    behavior: 'Row/disclosure opens individual inventory instances.',
  },
  {
    id: 'rooms-floating-action',
    label: 'Rooms floating action buttons',
    instances: 17,
    affordance: 'action-icon',
    implementation: 'RoomPickerButton through FloatingActionButton',
    behavior: 'Opens the Rooms sheet.',
    exceptionReason: 'The source-shaped floating action is a launch command, not a content row; its floor-plan icon and Rooms label are the complete affordance.',
    sourceReference: 'At-a-glance route mapping and existing Rooms mobile Playwright baseline.',
  },
  {
    id: 'create-task-floating-actions',
    label: 'Create task floating action buttons',
    instances: 5,
    affordance: 'action-icon',
    implementation: 'CreateChoreButton through FloatingActionButton',
    behavior: 'Opens Create Task.',
    exceptionReason: 'The plus icon is the standard source-shaped create action and a right chevron would imply navigation rather than creation.',
    sourceReference: 'Source-shaped Create Task Playwright coverage in e2e/react-dash.spec.ts.',
  },
  {
    id: 'grocery-floating-actions',
    label: 'Add grocery floating action buttons',
    instances: 2,
    affordance: 'action-icon',
    implementation: 'CreateGroceryButton through FloatingActionButton',
    behavior: 'Opens Add Grocery Item.',
    exceptionReason: 'The plus icon is the create affordance; a navigation chevron would conflict with the action meaning.',
    sourceReference: 'Source-shaped grocery route and modal Playwright coverage.',
  },
  {
    id: 'admin-task-floating-action',
    label: 'Add admin task floating action button',
    instances: 1,
    affordance: 'action-icon',
    implementation: 'CreateAdminTodoButton through FloatingActionButton',
    behavior: 'Opens Add Task for the HA Admin todo list.',
    exceptionReason: 'The plus icon communicates creation and matches the shared floating-action family.',
    sourceReference: 'Admin todo route source mapping and shared FloatingActionButton treatment.',
  },
  {
    id: 'scan-floating-actions',
    label: 'Scan Item floating action buttons',
    instances: 8,
    affordance: 'action-icon',
    implementation: 'ScanItemButton through FloatingActionButton',
    behavior: 'Opens the scan camera sheet.',
    exceptionReason: 'The barcode icon is a direct scan command; icon-only placements cannot accommodate a trailing navigation glyph without obscuring the action.',
    sourceReference: 'Kitchen and inventory source-shaped scan controls in existing Playwright coverage.',
  },
  {
    id: 'inventory-sort-floating-actions',
    label: 'Inventory Sort floating action buttons',
    instances: 6,
    affordance: 'action-icon',
    implementation: 'EverShelfInventoryFloatingActions',
    behavior: 'Opens the Sort sheet.',
    exceptionReason: 'The sort glyph is the action and active-state indicator; a right chevron would weaken the compact toolbar semantics.',
    sourceReference: 'Existing mobile inventory floating-dock baseline and route coverage.',
  },
  {
    id: 'inventory-filter-floating-actions',
    label: 'Inventory Filter floating action buttons',
    instances: 6,
    affordance: 'action-icon',
    implementation: 'EverShelfInventoryFloatingActions',
    behavior: 'Opens the Filter sheet.',
    exceptionReason: 'The filter glyph is the action and active-state indicator; a right chevron would weaken the compact toolbar semantics.',
    sourceReference: 'Existing mobile inventory floating-dock baseline and route coverage.',
  },
  {
    id: 'thermostat-option-pickers',
    label: 'Thermostat option picker buttons',
    instances: 4,
    affordance: 'down-chevron',
    implementation: 'ThermostatSelectButton',
    behavior: 'Opens an option-selection sheet and calls the selected HA climate/select service.',
    exceptionReason: 'A down chevron is the established select/menu affordance and distinguishes option expansion from detail navigation.',
    sourceReference: 'Thermostat picker configuration and source-shaped option-sheet Playwright coverage.',
  },
  {
    id: 'custom-light-mode-picker',
    label: 'Custom Lights mode picker',
    instances: 1,
    affordance: 'down-chevron',
    implementation: 'ModeToggleCard',
    behavior: 'Opens Lighting Mode while the sibling control toggles manual lighting.',
    exceptionReason: 'A down chevron identifies the control as a mode selector and prevents confusion with the independent toggle.',
    sourceReference: 'Front-yard mode select configuration and current source-derived mode matrix.',
  },
  {
    id: 'inventory-single-item-edit',
    label: 'Single inventory item edit buttons',
    instances: 'dynamic',
    affordance: 'edit-icon',
    implementation: 'PantryRow',
    behavior: 'Opens the item details sheet directly in the editable single-instance state.',
    exceptionReason: 'The pencil communicates edit intent more precisely than a navigation chevron.',
    sourceReference: 'EverShelf row action mapping and source-shaped inventory behavior tests.',
  },
  {
    id: 'native-date-time-controls',
    label: 'Native date and time picker controls',
    instances: 'dynamic',
    affordance: 'native-control',
    implementation: 'NativePickerField and SleepyPod time inputs',
    behavior: 'Opens the platform date/time picker.',
    exceptionReason: 'These are native form controls rather than disclosure rows; platform picker chrome owns the affordance.',
    sourceReference: 'Native input types and mobile picker behavior asserted by existing tests.',
  },
  {
    id: 'native-confirm-prompt-actions',
    label: 'Native confirmation and quantity prompt actions',
    instances: 'dynamic',
    affordance: 'native-control',
    implementation: 'SleepyPod and EverShelf action buttons',
    behavior: 'Opens a native confirmation or prompt before an HA action.',
    exceptionReason: 'The visible power/delete/cart action icon describes the command; the native dialog is a safety step, not a navigation destination.',
    sourceReference: 'Explicit state-to-service matrices and native-dialog tests.',
  },
]

export const MODAL_OPENER_EXCEPTIONS = MODAL_OPENER_INVENTORY.filter((item) => item.affordance !== 'right-chevron')
