export type ResponsiveCoverage = 'direct' | 'not-applicable' | 'owned'

export interface PlaywrightSpecCoverage {
  area: string
  landscape: ResponsiveCoverage
  landscapeOwner?: string
  note?: string
  safeArea: ResponsiveCoverage
  safeAreaOwner?: string
  spec: string
}

export const PLAYWRIGHT_SPEC_COVERAGE = [
  {
    area: 'Native phone, foldable, tablet and fine-pointer navigation, boundaries, rotation and focus',
    landscape: 'direct',
    safeArea: 'owned',
    safeAreaOwner: 'safe-area-responsive.spec.ts',
    spec: 'adaptive-navigation.spec.ts',
  },
  {
    area: 'Admin relay warning state and modal copy',
    landscape: 'owned',
    landscapeOwner: 'responsive-modal-inventory.spec.ts',
    safeArea: 'owned',
    safeAreaOwner: 'safe-area-responsive.spec.ts',
    spec: 'admin-relay-warning.spec.ts',
  },
  {
    area: 'Bathroom fan cards, timers, and services',
    landscape: 'owned',
    landscapeOwner: 'responsive-modal-inventory.spec.ts',
    safeArea: 'owned',
    safeAreaOwner: 'safe-area-responsive.spec.ts',
    spec: 'bathroom-fans.spec.ts',
  },
  {
    area: 'Fine-pointer Chores title wrapping',
    landscape: 'not-applicable',
    note: 'Desktop-only geometry is covered by desktop-responsive.spec.ts.',
    safeArea: 'not-applicable',
    spec: 'battery-title-desktop-responsive.spec.ts',
  },
  {
    area: 'Fine-pointer route, navigation, focus, Food, and vacuum behavior',
    landscape: 'direct',
    note: 'Desktop safe-area geometry remains the zero-inset baseline.',
    safeArea: 'not-applicable',
    spec: 'desktop-responsive.spec.ts',
  },
  {
    area: 'Cross-page layout, Chores, Security, media, and regression coverage',
    landscape: 'direct',
    safeArea: 'owned',
    safeAreaOwner: 'safe-area-responsive.spec.ts',
    spec: 'feedback-regressions.spec.ts',
  },
  {
    area: 'Garage optimistic state and service failures',
    landscape: 'owned',
    landscapeOwner: 'responsive-pages-all.spec.ts',
    safeArea: 'owned',
    safeAreaOwner: 'safe-area-responsive.spec.ts',
    spec: 'garage-doors.spec.ts',
  },
  {
    area: 'Fine-pointer Home hydration without a second loader or lost chrome',
    landscape: 'not-applicable',
    note: 'Desktop-only hydration lifecycle has separate responsive coverage in home-route-hydration.spec.ts.',
    safeArea: 'not-applicable',
    spec: 'home-route-hydration-desktop.spec.ts',
  },
  {
    area: 'Warm Home navigation across phone orientations, tablet, desktop and mounted resize',
    landscape: 'direct',
    safeArea: 'owned',
    safeAreaOwner: 'safe-area-responsive.spec.ts',
    spec: 'home-route-hydration.spec.ts',
  },
  {
    area: 'Real HAKit iframe replacement lifecycle',
    landscape: 'not-applicable',
    note: 'Subscription lifecycle is geometry-independent.',
    safeArea: 'not-applicable',
    spec: 'iframe-lifecycle-real-hakit.spec.ts',
  },
  {
    area: 'Wrapper and custom-panel iframe disposal lifecycle',
    landscape: 'not-applicable',
    note: 'Host disposal bookkeeping is geometry-independent.',
    safeArea: 'not-applicable',
    spec: 'iframe-lifecycle.spec.ts',
  },
  {
    area: 'Non-room modal landscape chrome, measured tiers, pane layouts, media caps, and portrait rotation',
    landscape: 'direct',
    safeArea: 'direct',
    spec: 'landscape-modal-adaptation.spec.ts',
  },
  {
    area: 'Clean-baseline visual parity for every route',
    landscape: 'direct',
    safeArea: 'owned',
    safeAreaOwner: 'safe-area-responsive.spec.ts',
    spec: 'mobile-parity-all-routes.spec.ts',
  },
  {
    area: 'Named iPhone and Android descriptor geometry smoke',
    landscape: 'direct',
    safeArea: 'direct',
    spec: 'mobile-device-smoke.spec.ts',
  },
  {
    area: 'Modal gesture arbitration and dismissal',
    landscape: 'owned',
    landscapeOwner: 'responsive-modals.spec.ts',
    safeArea: 'owned',
    safeAreaOwner: 'safe-area-responsive.spec.ts',
    spec: 'modal-sheet-gestures.spec.ts',
  },
  {
    area: 'Mounted modal open, close, hash, and rapid-reopen lifecycle',
    landscape: 'owned',
    landscapeOwner: 'responsive-modal-inventory.spec.ts',
    safeArea: 'owned',
    safeAreaOwner: 'safe-area-responsive.spec.ts',
    spec: 'modal-sheet-lifecycle.spec.ts',
  },
  {
    area: 'Modal animation performance and blur cost',
    landscape: 'not-applicable',
    note: 'Frame timing intentionally runs in one stable geometry.',
    safeArea: 'not-applicable',
    spec: 'modal-sheet-performance.spec.ts',
  },
  {
    area: 'Intent-stable modal geometry, identity resets, loading, details, and rotation',
    landscape: 'direct',
    safeArea: 'direct',
    spec: 'modal-geometry-stability.spec.ts',
  },
  {
    area: 'Mounted rotation typography, equal-width tiles, cross-family frames, configured room openers, and every rendered tab',
    landscape: 'direct',
    note: 'Runs in mobile Chromium, fine-pointer Chrome, and opt-in WebKit. Native iOS text inflation and physical display masks still require a real device.',
    safeArea: 'direct',
    spec: 'modal-rotation-regressions.spec.ts',
  },
  {
    area: 'WebKit modal scrolling and touch action',
    landscape: 'direct',
    safeArea: 'direct',
    spec: 'modal-sheet-webkit.spec.ts',
  },
  {
    area: 'Dashboard preload I/O invariants',
    landscape: 'not-applicable',
    note: 'Hidden inert preload geometry performs no responsive runtime work.',
    safeArea: 'direct',
    spec: 'preload-inert.spec.ts',
  },
  {
    area: 'Broad functional dashboard, route, modal, and service behavior',
    landscape: 'direct',
    safeArea: 'owned',
    safeAreaOwner: 'safe-area-responsive.spec.ts',
    spec: 'react-dash.spec.ts',
  },
  {
    area: 'Real HAKit dial semantics and focus',
    landscape: 'not-applicable',
    note: 'Opt-in live-backend semantics are geometry-independent.',
    safeArea: 'not-applicable',
    spec: 'real-hakit-dials.spec.ts',
  },
  {
    area: 'Recipe touch and keyboard focus behavior',
    landscape: 'owned',
    landscapeOwner: 'responsive-modal-inventory.spec.ts',
    safeArea: 'owned',
    safeAreaOwner: 'safe-area-responsive.spec.ts',
    spec: 'recipe-keyboard-focus.spec.ts',
  },
  {
    area: 'Exact shell and navigation breakpoints',
    landscape: 'direct',
    safeArea: 'direct',
    spec: 'responsive-layout.spec.ts',
  },
  {
    area: 'Physical callsites, landscape opener/kind rows, and literal portrait tile families',
    landscape: 'direct',
    safeArea: 'direct',
    spec: 'responsive-modal-inventory.spec.ts',
  },
  {
    area: 'Modal sizes, scroll owners, grids, workspaces, and resizing',
    landscape: 'direct',
    safeArea: 'direct',
    spec: 'responsive-modals.spec.ts',
  },
  {
    area: 'All-route canonical viewport and mounted-resize acceptance',
    landscape: 'direct',
    safeArea: 'owned',
    safeAreaOwner: 'safe-area-responsive.spec.ts',
    spec: 'responsive-pages-all.spec.ts',
  },
  {
    area: 'All-route synthetic insets, phone shapes, modals, and rotation',
    landscape: 'direct',
    safeArea: 'direct',
    spec: 'safe-area-responsive.spec.ts',
  },
  {
    area: 'Sprinkler cards and same-sheet schedule details',
    landscape: 'owned',
    landscapeOwner: 'responsive-modal-inventory.spec.ts',
    safeArea: 'owned',
    safeAreaOwner: 'safe-area-responsive.spec.ts',
    spec: 'sprinklers.spec.ts',
  },
  {
    area: 'Vacuum outcome cards, wrapping, and compact geometries',
    landscape: 'direct',
    safeArea: 'owned',
    safeAreaOwner: 'safe-area-responsive.spec.ts',
    spec: 'vacuum-outcomes.spec.ts',
  },
  {
    area: 'Vacuum state truthfulness, maps, all viewports, and resizing',
    landscape: 'direct',
    safeArea: 'owned',
    safeAreaOwner: 'safe-area-responsive.spec.ts',
    spec: 'vacuum-status.spec.ts',
  },
  {
    area: 'Weather carousel complete-page sizing, touch swipes, mouse and keyboard controls',
    landscape: 'direct',
    safeArea: 'owned',
    safeAreaOwner: 'safe-area-responsive.spec.ts',
    spec: 'weather-carousel.spec.ts',
  },
] as const satisfies readonly PlaywrightSpecCoverage[]
